### ISSUE TITLE
Install with dependencies

### ISSUE THREAD

**Issue by mattloose** [nanoporetech/tombo#1]
The basic install works but none of the others appear to - I'm on OSX  - I get an error:

build failed with error code 128 in None

Any suggestions?

**Comment by marcus1487** [comment]
Ah! I think this is an issue with the pip+git install combination. In short these additional installation options just install rpy2 and scikit-learn via pip. Installing these two packages (along with ggplot2 and cowplot in R) should enable all tombo subcommands. 

I will work on a more robust solution to this shortly.
