### ISSUE TITLE
Failed assertion

### ISSUE THREAD

**Issue by rasto2211** [nanoporetech/tombo#10]
I can see quite a lot of reads to fail because of this assertion:
```
assert len(qSeq) == qLen, 'Read sequence from SAM and ' + \
            'cooresponding cigar string do not agree.'
```
What could be the reason why this is failing? As far as I understand the code correctly, `qSeq` is query sequence extracted from SAM file and `qLen` is estimated length of the query sequence from the CIGAR string. Is this a bug in BWA-MEM?

**Comment by marcus1487** [comment]
Yes, I believe this is a bug in bwa. Have you tried to update your bwa version and try running the `resquiggle` command again?

**Comment by rasto2211** [comment]
I think it's a bug in tombo, not in BWA-MEM. I looked at the SAM specs and the code again and I see couple problems:

1. In the part of the code when you remove all the operations from cigar string that are not `M=X` you have this if:
```
  if cigar[0][1] in 'IP':                                                                                                                                                                                                            
                tSeq = tSeq[cigar[0][0]:]                                                                                                                                                                                                      
            else:                                                                                                                                                                                                                              
                qSeq = qSeq[cigar[0][0]:]                                                                                                                                                                                                      
                start_clipped_bases += cigar[0][0]                                                                                                                                                                                                                             
```
but the SAM specs says that 

> I is insertion to the reference

It's insertion in the alignment -- reference contains gap and query read contains a nucleotide in the alignment column. So the the code should look like this:
```
 if cigar[0][1] in 'IP':                                                                                                                                                                                                             
                qSeq = qSeq[cigar[0][0]:]                                                                                                                                                                                                      
                start_clipped_bases += cigar[0][0]                                                                                                                                                                                                                
            else:                                                                                                                                                                                                                              
                tSeq = tSeq[cigar[0][0]:]
```
The same for the part of the code which removes operations from the end of cigar.

2. Why are you removing operations from the beginning and end until you reach match/mismatch? Can you justify this decision?

3. SAM specs says:

> Sum of lengths of the M/I/S/=/X operations shall equal the length of SEQ

Why do you include to the sum padding operations (P) ?

**Comment by marcus1487** [comment]
Okay, so I think this is actually a bug in both tombo and bwa-mem. I now remember running into this a while back, when working on nanoraw, and apparently I did not fix it correctly.

I'll first answer question 2. The reason for clipping non-matching matching positions is that an insertion of deletion before a matching base does not really make much sense. Insertions should just be added to the soft/hard clipping of the read and deletions/skips should be a shift in the mapped start/end position. So the fact that any of these cigar types exist before a match/mismatch is, IMO, a bug in bwa-mem.

Thus I do think that your first point is valid, but in order to handle internal hard/soft clipping (again a behavior that should not happen, but should be treated as an insertion wrt the read sequence) I think the fix should be to change "IP" to "ND".

As for the third point, I think this is a bug in tombo, but I never tested against a padded reference.

I will push a fix for this shortly. Thank you for your interest in tombo and the bug reports!

**Comment by rasto2211** [comment]
I agree that insertions to the reference (I) at the end/beginning of the alignment could be marked as soft clips (S) because S is kind of like insertion to the reference. So you can basically merge the block of insertions with doft clips. And I also agree that deletions from the reference at the end or beginning of the alignment could be just discarded from the mapping. Did you discuss this problem with @lh3 (Heng Li), the author of bwa?

**Comment by lh3** [comment]
The long-read support of bwa-mem is largely deprecated by minimap2. I am still responsible for fixing critical issues in bwa-mem, but as leading/trailing `I`/`D` is minor and has a workaround, I will not come to the issue any time soon. If you see leading/trailing `I`/`D` from minimap2 SAM, let me know. I will fix that soon.

**Comment by marcus1487** [comment]
Thank you for your response @lh3. I was aware that the long read support had shifted to minimap2, and so I did not raise this issue for bwa mem. As for minimap2, I have not heard any users report this error. Given that this bug would have shown up for minimap2 alignments as well I think it is safe to say that minimap2 does not produce leading/training `I`/`D`.

I will push a fix for this bug in Tombo shortly.
