### ISSUE TITLE
Where is segment/event mapping information generated?

### ISSUE THREAD

**Issue by rstraver** [nanoporetech/tombo#103]
I'm trying to use the Tombo resquiggle API functionality. Due to the type of fragments we sequence I need to make several changes to make it applicable, so using Tombo as a tool and reading the fast5 won't work. 
What I can't figure out is how to obtain the data Tombo seems to create as it is written in the fast5, but not returned by the resquiggle function.

If I follow the guide here:
https://nanoporetech.github.io/tombo/tombo.html#python-api-examples

I run the resquiggle command:
```
# run full re-squiggle
rsqgl_results = resquiggle.resquiggle_read(
    map_results, std_ref, rsqgl_params, all_raw_signal=all_raw_signal)
```

And that gives me a bunch of things but nothing that I could reconstruct the  'resquiggle' from. Stuff like normalization information and segmentation is there, but not the actual mapping from the segments to the fasta sequence. 

What I'm looking for is where I can obtain this information, as I can see in the fast5 file using h5dump:
```
 DATASET "Events" {
               DATATYPE  H5T_COMPOUND {
                  H5T_IEEE_F64LE "norm_mean";
                  H5T_IEEE_F64LE "norm_stdev";
                  H5T_STD_U32LE "start";
                  H5T_STD_U32LE "length";
                  H5T_STRING {
                     STRSIZE 1;
                     STRPAD H5T_STR_NULLPAD;
                     CSET H5T_CSET_ASCII;
                     CTYPE H5T_C_S1;
                  } "base";
               }
               DATASPACE  SIMPLE { ( 3121 ) / ( 3121 ) }
               DATA {
               (0): {
                     0.909729,
                     nan,
                     0,
                     4,
                     "C"
                  },
               (1): {
                     0.763667,
                     nan,
                     4,
                     3,
                     "A"
                  },
```

So that data is generated by resquiggling, but not by the resquiggle command shown in the documentation. I've been trying to figure out the scripts for several days and tracing where pieces come from. While I can see how the resquiggle command works and what is does, it's a complete mystery for me where the actual aligment between the segments and the fasta sequence comes from.

Can someone point out where I can find the function that actually gets that information? Or if I misinterpreted some of this, how do I determine the actual segment/raw-to-fasta mapping from the data the resquiggle command returns?

**Comment by marcus1487** [comment]
The segments (`segs` attribute) produced here are actually the re-squiggle results. These are not the initial event boundaries, but the final genomic base assignment positions (so these are the base positions found within the FAST5s). The length of the `segs` attribute should be one more than the length of the `genome_seq` attribute (to give last end point). Thus the segments (along with the `read_start_rel_to_raw` attribute) define the mapping of signal to genomic sequence. The sequence from the `genome_seq` attribute should also match up with the `genome_loc` attribute to anchor the read to the actual genome positions as well.

So to get the sequence, raw signal position (starting from `read_start_rel_to_raw`) and base raw length portion of the FAST5 output you could run:
```
for base, raw_signal_position, base_raw_length in zip(
        rsqgl_results.genome_seq, 
        rsqgl_results.segs[:-1], 
        np.diff(rsqgl_results.segs)):
    # do stuff
```

The additional event means could be extracted by running:
```
norm_signal = norm_signal[
    rsqgl_results.read_start_rel_to_raw:
    rsqgl_results.read_start_rel_to_raw + rsqgl_results.segs[-1]]
base_means = tombo_stats.compute_base_means(norm_signal, rsqgl_results.segs)
```

If you have a look at the step-by-step re-squiggle instructions (in the API examples), initial event boundaries are computed (`resquiggle.segment_signal` step) and these event boundaries are passed to the `resquiggle.find_adaptive_base_assignment` function where the events are assigned to genomic positions (thus collapsing some events and adding some new segments). Thus the segments returned from the `resquiggle.find_adaptive_base_assignment` function are not the event boundaries, but the genomic base assignment positions.

Hopefully this helps to clear this up a bit, but do post again if this is still confusing. I will add a note to the [`resquiggleResults`](https://nanoporetech.github.io/tombo/tombo.html#tombo.tombo_helper.resquiggleResults) object docs to make it more clear that the segments correspond to genomic positions and not "event" boundaries.

**Comment by rstraver** [comment]
Thanks a lot, I believe I got what I needed for now.  

However, I get the impression that this:
```
norm_signal = norm_signal[
    rsqgl_results.read_start_rel_to_raw:
    rsqgl_results.read_start_rel_to_raw + rsqgl_results.segs[-1]]
base_means = tombo_stats.compute_base_means(norm_signal, rsqgl_results.segs)
```
causes the segments to end beyond the final raw positions, are you sure you need to remove `read_start_rel_to_raw` values from the raw datas beginning after resquiggling step-by-step? Running it without that seems to provide me correct results right now, although I had to calculate the means myself as the `tombo_stats.compute_base_means` function kept failing with zero division errors.

Also, the `norm_signal` information appears to be inaccessible if you don't run the step-by-step way for resquiggling. Perhaps returning it in the resquiggle function could be an enhancement as I seem to have to go with the step-by-step approach just to get this part.

Lastly, I'm still curious where the `"Events"` information as stated in the starting post is added to the fast5 files, as I have still no clue where that even happens (I lose track of the program flow at some multi processing queue-ing).

**Comment by rstraver** [comment]
>My best guess is that the resolve_skipped_bases_with_raw function was not called on the segments before computing base means. Check that the segments don’t include zero length bases before computing base means. 

I think you are correct, I noticed several occasions where consecutive values in `segs` were the same. Looking back I did run `resolve_skipped_bases_with_raw` but the results were probably never actually used: I blindly assumed `resolve_skipped_bases_with_raw` would update `segs` in `dp_results` but it seems it does not. However in my own little implementation I did use the `segs` variable it returned so I guess I already solved that for now. I'll try running `tombo_stats.compute_base_means` again later with an updated `segs`.

I'm not sure how much sense I can make out of that fast5 writing function as I have yet to discover where the calculations for that data are actually done, but it seems I can already obtain that information from the data so I don't really need to understand that for now.

Thanks a lot for your answers!

**Comment by marcus1487** [comment]
Yes the resquiggle results are actually just a wrapper around a nanedtuple, so nothing gets changed in place there. 

For the fast5 writing, yes it is a bit of a maze with the multiprocessing, iterative scaling and error handling, but here is where that information is passed right before the fast5 writing connection (https://github.com/nanoporetech/tombo/blob/master/tombo/resquiggle.py#L1509) and here is where that rsqgl_res is actually computed (so the logic is right above; https://github.com/nanoporetech/tombo/blob/master/tombo/resquiggle.py#L1149).

**Comment by marcus1487** [comment]
One additional note on this issue is that the `norm_signal` is actually available from the `resquiggle_read` results object. The returned [resquiggleResults object](https://nanoporetech.github.io/tombo/tombo.html#tombo.tombo_helper.resquiggleResults) contains a `raw_signal` slot. When returned from the `resquiggle_read` function this slot contains the normalized signal from the portion of raw signal matched to genomic bases. This allows access to the normalized signal without performing the step-by-step re-squiggle process.

**Comment by rstraver** [comment]
Not sure if I'll need that now but that's good to know. A little note though, the variable name `raw_signal` might be a bit confusing if it's not really raw anymore when it comes back

**Comment by marcus1487** [comment]
In my mind "raw" refers to the per-observation values as opposed to events or segments of signal. Since this attribute is used for both original (data acquisition values) raw signal values as well as normalized raw signal values I think `raw_signal` might still be a useful title. Do let me know if this distinction still seems off. I will add a note to the docs on this object to make this clear.

**Comment by rstraver** [comment]
I'm not the expert here so I'm sure others may have a better idea but to me 'raw' means something that is unprocessed, after normalization I'd consider it somewhat processed so seeing the information in this variable has changed is rather unexpected for me.
