### ISSUE TITLE
how can I get the correspondence between the raw signals and the base called read?

### ISSUE THREAD

**Issue by huangnengCSU** [nanoporetech/tombo#104]
Hi:
from the tool codes, I have learned that it first segments the raw signals into events and then maps events to the genome reference. I'm trying to extract the raw signal of each base from base called read.  how can i do it?

**Comment by marcus1487** [comment]
The result of the re-squiggle procedure found in the [API examples](https://nanoporetech.github.io/tombo/tombo.html#python-api-examples) contains the raw signal to genomic sequence correspondence. This is discussed in issue #103 as well.

There is no mapping between raw signal and base calls as basecalls are only used for genomic mapping in the Tombo framework.

**Comment by marcus1487** [comment]
I have put together a gist to perform this task using the Tombo API. Please find that [here](https://gist.github.com/marcus1487/5cf083644143aafc770dceb213783346).
