### ISSUE TITLE
what is the meaning of expected signal levels, and how to get them?

### ISSUE THREAD

**Issue by huangnengCSU** [nanoporetech/tombo#105]
In the document, algorithm details - Sequence to Signal Assignment,  it says "_This matching is found by a dynamic programming/dynamic time warpping algorithm to match event signal levels with expected signal levels given genomic sequence_".  I'm confused, what is the meaning of excepted signal levels of given genomic sequence? The only information of genome sequence is nucleotide sequence, how can i calculate the excepted signal levels of genomic sequence?

**Comment by marcus1487** [comment]
Expected signal levels are looked up from a 6-mer (or 5-mer for RNA) of local sequence context. You can use the [`get_ref_from_seq`](https://nanoporetech.github.io/tombo/tombo.html#tombo.tombo_stats.get_ref_from_seq) function to extract these expected (median-normalized) levels from a bit of sequence.
