### ISSUE TITLE
How to set a coverage threshold for a max_difference plot?

### ISSUE THREAD

**Issue by Shin-Kawa** [nanoporetech/tombo#107]
Hi,

I have two sets of Direct-RNA results from Nanopore and would like to compare the base modification between two samples. I did;
tombo resquiggle --rna
tombo detect_modifications de_novo
for each sample.

And performed;
tombo plot max_difference

Pdf file was generated. But, for the most of the plot, the coverage was very low (coverage=1).
Can I set the threshold of the coverage for the plot?

Thanks

ShinKawa

**Comment by marcus1487** [comment]
There is not currently an option to set a minimum threshold for the max difference command. Unfortunately, this plot type does have a tendency to identify lower coverage sites. The ‘tombo plot most_significant’ command would be more likely to produce the best results here (especially in combination with the ‘tombo detect_modifications sample_compare’ command output).
