### ISSUE TITLE
Extracting fasta/fastq from corrected reads?

### ISSUE THREAD

**Issue by smm19900210** [nanoporetech/tombo#108]
Hello,
Is there a simple way to extract fasta/fastq files with the corrected data after we run genome_resquiggle on some reads files? (I examined the .fast5 files with HDF viewer after resquiggle and didn't see anything useful, I saw the aligned read sequence but I'm not sure how to extract it to a usable fasta/fastq)

**Comment by marcus1487** [comment]
The aligned sequences within the reads are simply a range of the provided reference sequence (so containing no more information than the reference sequence and mapping coordinates), so extracting these sequences did not seem particularly useful. If there is a use case that would make extraction of these sequence beneficial it could be considered as an enhancement.
