### ISSUE TITLE
preprocessing issues - warning and multiple fast5 & fastq files

### ISSUE THREAD

**Issue by Nastiya** [nanoporetech/tombo#112]
Hi Marcus,

I've encounter two issues, and would appreciate your help
1. I performed a successful sequencing, following that I run albacore for basecalling, then Nanoplot to check the sequencing quality (looks ok) and when trying to run "annotate_raw_with_fastq", I keep getting a warning and 0 adding sequences.

`[17:10:35] Annotating FAST5s with sequence from FASTQs.
0it [00:00, ?it/s]******************** WARNING ********************
              Some records contain read identifiers not found in any FAST5 files or sequencing summary files.
0it [00:00, ?it/s]
**[17:10:35] Added sequences to a total of 0 reads.**`

How can I solve this issue? Why does it happen?

2. How can I run run annotate_raw_with_fastq on a multiple fast5 directories and multiple fastq files in one run?

Thank you.
Nastya

**Comment by marcus1487** [comment]
This warning indicates that the `annotate_raw_with_fastq` command is not able to identify the read ids found in either the provided FAST5 reads (from within the fast5s base directory) or the provided `--sequencing-summary-filenames`. Ensure that all of the provided files are from the same run and that this is the full output of the albacore run. If you are passing a single (or small test) output fastq or sequencing summary files it is likely that the reads within these locations to not correspond with the fast5 read files provided.

This is related to your second question. Both the `--fastq-filenames` and `--sequencing-summary-filenames` accept multiple arguments. So you can pass many fastqs and sequencing summary files to these arguments of this command. Only a single fast5s base directory can be passed, so this should be the top level of the raw reads (FAST5 files) location.

**Comment by Nastiya** [comment]
Thank you for your valuable input. 

I indeed try to run it on a small test: 
After the sequencing was finished I received two separate folders with fast5 files.
I run the `read_fast5_basecaller.py` command only on one of them, and received one fastq file for it.
On the generated fastq I run the `annotate_raw_with_fastq` command. 

I did manual cross-checking of the read_ids for a few reads, and made sure that these reads from the the fastq file , have a fast5 file in that specific directory.

Then I've tried to re-run the `annotate_raw_with_fastq` command again, but I still got the same results. 
I guess I'm missing something , although everything seems OK, and it is not the first time I'm running the command on partial results.

**Comment by marcus1487** [comment]
If you could post the exact command you entered this might help to identify the error here.

**Comment by Nastiya** [comment]
Good idea :) I've tried these two commands; one with `--sequencing-summary-filenames` , and one without.

`(user) userc:$ tombo preprocess annotate_raw_with_fastqs --fast5-basedir /home/user/Nanopore_files/reads/20180819_1123sample1/fast5/0/ --fastq-filenames /home/user/NanoPore_1123/workspace/pass/pass.fastq  --processes 4
/home/user/.conda/envs/user/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
[12:20:37] Getting read filenames.
[12:20:37] Preparing reads and extracting read identifiers.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2331/2331 [00:09<00:00, 245.01it/s]
[12:20:47] Annotating FAST5s with sequence from FASTQs.
0it [00:00, ?it/s]******************** WARNING ********************
	Some records contain read identifiers not found in any FAST5 files or sequencing summary files.

[12:20:47] Added sequences to a total of 0 reads.


(user) userc: tombo preprocess annotate_raw_with_fastqs --fast5-basedir /home/user/Nanopore_files/reads/20180819_1123sample1/fast5/0/ --fastq-filenames /home/user/NanoPore_1123/workspace/pass/pass.fastq --sequencing-summary-filenames /home/user/NanoPore_1123/sequencing_summary.txt  --processes 4
/home/user/.conda/envs/user/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
[12:39:21] Getting read filenames.
[12:39:21] Parsing sequencing summary files.
[12:39:21] Annotating FAST5s with sequence from FASTQs.
  0%|                                                                                                                                                                                     | 0/2331 [00:00<?, ?it/s]******************** WARNING ********************
	Some read files that could not be accessed.
  0%|                                                                                                                                                                                     | 0/2331 [00:00<?, ?it/s]
[12:39:22] Added sequences to a total of 0 reads.`

**Comment by marcus1487** [comment]
These commands look correct. Can I ask how you performed the manual cross-checking for read_ids in the FASTQ and FAST5 files? I am thinking that these values are not corresponding, but from standard albacore basecalling this should not generally happen.

**Comment by Nastiya** [comment]
Hi,

I chose several fastq sequences, and open their FAST5 files using HDF5 Viewer ( based on read and ch values). Then I compared their read_id.
Attached an example.

<img width="924" alt="tombo issue" src="https://user-images.githubusercontent.com/24778316/46004078-ac2ed300-c0ba-11e8-92d8-4936345ae2dc.png">

**Comment by marcus1487** [comment]
I think in most cases this would result in a different error, but could you check that the FAST5 files are write-able?

**Comment by Nastiya** [comment]
You were right. 
There was a problem with the permissions. Maybe it is better to raise a different error in this case.

Thank you for your help!

**Comment by PanZiwei** [comment]
@Nastiya Hi Nastiya, I have the same issue as you described. How do you solve the problem finally?
