### ISSUE TITLE
Interpretation of most significant sites graphic

### ISSUE THREAD

**Issue by wod31** [nanoporetech/tombo#113]
Hello! I am new to nanopore and tombo and I have some issues interpreting the results of the most significant sites graphic when looking for modified bases. Can anyone explain me how are those interpreted? I've been looking for information but I found nothing... 

Many thanks!
![screenshot from 2018-09-18 12-25-11](https://user-images.githubusercontent.com/35917727/45681518-fbff1e80-bb3d-11e8-9209-2aebb4bdaea7.png)

**Comment by marcus1487** [comment]
Tombo plots are described to some degree [here](https://nanoporetech.github.io/tombo/plotting.html#genome-anchored-plotting), though some notes about the plot basics could certainly help on this page. 

In these plots, each red line represents the normalized raw electric current signal from a single read. The grey distributions represent the expected level for this signal from canonical bases derived from the reference sequence. The red distributions represent the expected level for the alternate base. Read more about the identification of these regions on the [modified base detection documentation page](https://nanoporetech.github.io/tombo/modified_base_detection.html).

**Comment by wod31** [comment]
Thanks for your answer. But I think it still is a little bit confusing for me. 

In this case (image) where there is no difference between canonical signal and alternate base signal, how do you know it's a modified base? Is it because the 6-mer mode of calculating the statistic and the surrounding bases are affecting the signal so it's called a modified base generating an Est. Frac. Alternative = 1? 

![image](https://user-images.githubusercontent.com/35917727/45737792-0f1df700-bbef-11e8-9076-7c611f35e972.png)

**Comment by marcus1487** [comment]
Yes. I think you have the right idea here. Note that the alternative (red) distributions shift away from the canonical distributions (and match the raw signal shifts) for several bases around the central (most significant) adenine. These shifts are indicative of the modified adenine in this central position.

You can see more details on the alternate base testing method [docs page here](https://nanoporetech.github.io/tombo/modified_base_detection.html#specific-alternate-base-detection-recommended). The main point to note here is this: 

> This statistic is computed and summed over all positions where the base of interest is included in the modeled k-mer. The default DNA model is a 6-mer, so the signal at the six surrounding genomic bases contribute to the resulting statistic at any one position.

So the positions showing little or no difference between the canonical and alternative distributions do not contribute much to the overall test statistic at this position, but the upstream (in read centric position) positions cause this site to be identified as highly significant for the alternate base at this position.

**Comment by LeilyR** [comment]
Hi, I think I have a similar question for RNA data. I have plotted the significant regions but I really cannot see any difference between red lines and the black distribution on the modified base, Does that mean that there are not really significant modifications and I should not consider them as modified bases? I am not sure how much shift I expect to see. How can I interpret the values on the Y-axis? Is there any way that I can visualise their p values? Thanks!

These are two of them as  examples:
![ev owa](https://user-images.githubusercontent.com/25766687/82800338-d2060f80-9e7b-11ea-829e-c2403cf50d0b.jpeg)
![ev owa](https://user-images.githubusercontent.com/25766687/82799224-fcef6400-9e79-11ea-9f92-facde0767396.jpeg)
![ev owa-2](https://user-images.githubusercontent.com/25766687/82799234-0082eb00-9e7a-11ea-8c5b-42a312f38865.jpeg)
