### ISSUE TITLE
detect_modifications de_novo

### ISSUE THREAD

**Issue by achilles1989** [nanoporetech/tombo#114]
￼Hi, I try to detect modifications in native RNA with Tombo but something weird happened. After resquiggle my fast5 reads, I tried "tombo detect_modifications de_novo" several times but it always stuck at 99% or 100% with no exception informations. I want to know if I missed something. Thank you.

<img width="575" alt="eec30948-34fa-4195-ae59-543aaa4d78c4" src="https://user-images.githubusercontent.com/8258430/45791741-83bf6700-bcbd-11e8-913e-6cfa85068d16.png">

<img width="571" alt="ca63e58e-2cda-4a33-8601-b0e75b1378e3" src="https://user-images.githubusercontent.com/8258430/45791749-8fab2900-bcbd-11e8-9db1-9523597cda16.png">

<img width="562" alt="8052185d-d8aa-4b22-be9f-674aa2055688" src="https://user-images.githubusercontent.com/8258430/45801136-8afa6b00-bce5-11e8-839d-3081aab79f2a.png">

**Comment by marcus1487** [comment]
I believe that this may be due to a poor design choice in the per-read data storage. We are working on a fix for this problem, but for now if you run without the per-read statistics output the command should complete much more quickly.

**Comment by achilles1989** [comment]
After about an hour and a half, tombo finally completed the detection without the per-read statistics output. Thank your again for your advice. I am looking forward to the improvement of efficiency of tombo in the future.
