### ISSUE TITLE
Doubt about  identifying of 5mC from Direct RNA nanopore sequencing data

### ISSUE THREAD

**Issue by wlhCNU** [nanoporetech/tombo#116]
Hi，
  
 Recently,I try to  identify of 5mC from Direct RNA nanopore sequencing data by Tombo and encount 
  some problems.
  

First, when running  preprocess  annotate_raw_with_fastqs ,the log information  as follows:
               Added sequences to a total of 240910 reads
               [10:09:48] Getting read filenames.
               [10:13:52] Parsing sequencing summary files.
               [10:13:55] Annotating FAST5s with sequence from FASTQs.
               ****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 
              files or sequencing summary files 
              98%|█████▋  | 236300/240910 [3:28:42<04:04, 18.87it/s]
              [14:35:33] Added sequences to a total of 240910 reads.
  Why will appear this kind of warning that Some FASTQ records contain read identifiers not found in any 
  FAST5 files or sequencing summary files.
 

Second, run resquiggle analysis with the following command:  
             tombo resquiggle --rna --ignore-read-locks --overwrite --processes 30 
            /00.ONT_Tombo_test/ont/rice/20170124-R1704026-
           A1/GA10000/reads/fast5/  /Nanopore.tombo/1.data/rice_rna.fasta
  the log information  as follows:
            [16:30:43] Final unsuccessful reads summary (100.0% reads unsuccessfully processed; 417352 
            total reads):  57.7% ( 240814 reads) : Alignment not produced                                                          
           42.3% ( 176502 reads) : Analysis group not found at root of FAST5                                       
            0.0% (     27 reads) : Read failed sequence-based signal re-scaling parameter estimation.              
            0.0% (      9 reads) : Too much raw signal for mapped sequence                                         
           [16:30:43] Saving Tombo reads index to file.
We find that 100.0% reads unsuccessfully processed.In addition, 240910 reads were added sequences to analyze at  the  preprocess annotate_raw_with_fastqs step,which is contradictory to resquiggle analysis unsuccessful reads(100% reads;41752 total reads). How to reconcile this paradox?

Third, run detect_modifications  analysis with the following command: 
         tombo detect_modifications alternative_model --fast5-basedirs 
        /00.ONT_Tombo_test/ont/rice/20170124-R1704026-A1/GA10000/reads/fast5/     --statistics-file-
        basename sample.alt_modified_base_detection    --per-read-statistics-basename 
       sample.alt_modified_base_detection  --alternate-bases 5mC --processes 30
the log information  as follows:
        [17:15:13] Parsing Tombo index file(s).
        [17:15:16] Performing alternative model testing.
        [17:15:16] Performing alternative model testing against 5mC model.
        [17:15:16] Performing modified base detection across genomic regions.
       ^M  0%|          | 0/2 [00:00<?, ?it/s]^M100%|##########| 2/2 [00:04<00:00,  2.25s/it]
       Neither minus.wig  nor plus.wig  files have  Meaningful results.
 What could be causing these  troubles ? 

Thanks

**Comment by marcus1487** [comment]
For the first issue, as the warning indicates there are read id values from the provided fastq files that were not found in the provided sequencing summary files. It does appear as though all records found in the sequencing summary files were found in the fastqs and successfully added the to FAST5 files (from matching progress total and final added totals).

For the second point, the error types indicate the error "Analysis group not found at root of FAST5" which occurs for read files that have not had base calls added. These probably correspond to the read ids found in the FASTQ in the first step, but not found in the sequencing summary files. The re-squiggle step looks for all fast5 files in this directory, while the pre-process step only looks at reads found within the provided sequencing summary files. This is the reason for the discrepancy.

The second point here is that the most common error (among the read which do contain basecalls) is that the basecalls do not map to the provided reference sequence. This is quite hard to diagnose without further knowledge of the sample, but tombo cannot continue to process a read without a successful reference mapping. Note that for direct RNA spliced mappings are not allowed, so it is possible that this is causing the unaligned reads. See more on RNA processing here: https://nanoporetech.github.io/tombo/rna.html

For the final step, only successfully re-squiggled reads are processed in the detect_modifications steps. Thus there are no reads to process here. Fixing the upstream issues should fix these final steps.

**Comment by wlhCNU** [comment]
Thank you for your detailed answer. In addition, I have another question to  consult you. Because the direct RNA nanopore sequencing data comtain "U"  bases. Is it necessary to replace the "T" bases in the transcriptome reference sequences with  "U" bases before resquiggle analysis  ?

**Comment by marcus1487** [comment]
Tombo should work with either base ("U" or "T") in the reference transcriptome for direct RNA samples.
