### ISSUE TITLE
Whether the new version tombo is compatible with index files made by old version tombo

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#118]
Hi:
     I wonder whether I can continue to use existing tombo index files(produced by tombo1.4) in latest tombo environment.If it is not backward compatible,I am afraid I have to take a few days for Rebuilding the index.
thanks!

**Comment by marcus1487** [comment]
Tombo v1.4 index files are compatible with Tombo v1.5 index files. A small change to the re-squiggle procedure was made (first bullet in [release note](https://github.com/nanoporetech/tombo/releases/tag/1.5)), but this should have a very small impact on the results. Practically, the index file is compatible with the new v1.5. Best of luck!
