### ISSUE TITLE
Question about read lengths

### ISSUE THREAD

**Issue by JohnUrban** [nanoporetech/tombo#12]
Hi Marcus,

I was perusing the code pertaining to ``tombo test_significance``` when comparing a test and control while trying to debug Issue #11. 

I saw some code that made me wonder about read length -- specifically are reads longer than region size, excluded from the analysis?

Lines 1357-1359 in file ```tombo_stats.py``` in function ```_test_signif_worker()```
```
        reg_reads = [r_data for r_data in raw_read_coverage[(chrm, strand)]
                     if not (r_data.start >= reg_start + region_size or
                             r_data.end <= reg_start)]
```

Perhaps this has nothing to do with read length or the start/end positions of where reads/events were aligned. However, on a first pass it looked suspiciously like it is saying to include ```r_data``` only if the start and end positions are within the region -- which would exclude reads that spanned across the region (start < reg_start and end > reg_start+region_size) as well as reads that only started or ended in the region.

Apologies if I'm overlooking something obvious. It just made me curious. Any feedback about it would be appreciated.

Best,

  John

**Comment by marcus1487** [comment]
Hi John,

The short answer is that reads are not discarded by read length for significance testing.

This check is filtering for reads that overlap a region and not whether it is contained in the region. The first check `r_data.start >= reg_start + region_size` determines whether a read starts after the region and the second check `r_data.end <= reg_start` determines if a read ends before the beginning of the region. Thus if neither of these conditions are met (the `not`), the read overlaps the region being processed.
 
This does mean that several different processes (processing different regions) will be accessing the same read (possibly at the same time), but this is only a read operation, so access conflicts are not an issue. 

I hope this helps!

**Comment by JohnUrban** [comment]
Got it - yeah. Some how the Not(A or B) logic threw me for a minute, but it is clear now. Thanks.

**Comment by marcus1487** [comment]
Ya. It took me a little while to wrap my head around how the "does interval overlap other interval" check only takes two checks (making it much more efficient than the somewhat more straightforward test with 4 checks). Anyways glad you are finding all these edge cases; it really helps!
