### ISSUE TITLE
Difference between model_sample_compare and level_sample_compare for tombo detect_modifications?

### ISSUE THREAD

**Issue by BisonKok** [nanoporetech/tombo#120]
Hi Marcus. `sample_compare` option for `tombo detect_modifications` in v1.4 was divided into `model_sample_compare` and `level_sample_compare` in v1.5. Can I know what the difference is between `model_sample_compare` and `level_sample_compare`? Thanks in advance.

**Comment by marcus1487** [comment]
The documentation spells this out in more detail [here](https://nanoporetech.github.io/tombo/modified_base_detection.html#canonical-sample-comparison-methods), but briefly, the v1.4 `sample_compare` method is the same as the `model_sample_compare` method. The `level_sample_compare` method performs a test of the levels from two groups directly against one another, thus not performing a per-read test as the `model_sample_compare` method does.
