### ISSUE TITLE
Is there  a coverage requirement for ONT dataset?

### ISSUE THREAD

**Issue by cjchen5** [nanoporetech/tombo#122]
Hi,
I noticed that de_novo method works best with high >50X coverage.
Is there a coverage requirement for ONT dataset for alternative model?
THX!

**Comment by marcus1487** [comment]
Most all methods work better with more coverage, but the alternative (especially motif specific models) model testing works quite well at lower coverage (and even on per-read basis). The amount of coverage can also depend quite heavily on the biological question and the nature of the interaction of a particular alternate base with the nanopore. Thus defining coverage thresholds to cover all use cases for each method is quite difficult.

Is the 50X coverage noted from your experience? 50X coverage is noted for the `level_sample_compare` method on the documentation page, but there is currently no recommendation for the `de_novo` method specifically (or any other method). The recommendation for the `level_sample_compare` method should be considered a minimum and results do improve here with increased coverage as well.

**Comment by cjchen5** [comment]
Thank you marcus!
Do you any experimental data (Preferably, insects, eg. fruitfly) using ONT to test the prediction accuracy for methylation sites predicting? Because the species I sequencing don't have any experimental data for methylation sites. If you could give me ONT data which already have experimental data for methylation sites, I could use Tombo build my own pipline to training, predicting and testing the accuracy of my pipline. If the accuracy is high, I could use this pipline on my data and do some experimental verification with the predicted sites.

**Comment by marcus1487** [comment]
I do not have any methylated test data available for release at this time, but the tutorials in the Tombo docs ([here](https://nanoporetech.github.io/tombo/tutorials.html)) have instructions on building, running and validating Tombo models in a number of settings. Hopefully this page will help you with your task.

**Comment by cjchen5** [comment]
Yes, I followed the tutorials and get some results but I think I need to set some cutoff to get the results more convincing. Do you have any ONT data for any model species available for release? I could search methylated sites already verified by experimentl from database as if it have. 
Thank you again!

**Comment by marcus1487** [comment]
I do not have any methylated test data available for release at this time. You may be able to find publicly available data sets available online (e.g. https://github.com/nanopore-wgs-consortium/NA12878) in order to test a pipeline on model organism data.

**Comment by cjchen5** [comment]
Thanks!
