### ISSUE TITLE
Doubt on whether these fast5 files in "fail" folder which was generated by Albacore should  be used?

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#123]
Hi:
    I always had this question.
    If I want to detect modified base,Should I just utilize` "pass"` folder as input argument  of `--fast5-basedirs`  option?Due to the lower quality score,Maybe a number of  reads that contain potential modified base was assigned to `"fail"` folder
    thanks!

**Comment by marcus1487** [comment]
Most often the pass folder should contain most relevant reads even with a moderate level of alternative bases. There may be some specific biological applications where reads are sent to the fail folder, but most often this is likely not the case. In most cases the fail folder reads will either not map to the reference or fail the signal matching score threshold. In either case these reads will not be used in downstream analysis. So using these reads will likely result in more computing time, with little gain (again with some exceptions).

**Comment by weir12** [comment]
Many thanks
