### ISSUE TITLE
Issue with index and plot

### ISSUE THREAD

**Issue by lfaino** [nanoporetech/tombo#124]
Dear marcus
I have the same warning but ends with:

> Genome resolved raw signal could not be retrieved for some reads. Ensure that reads have been re-squiggled with the specified [--corrected-group].

the command that i used is:

`tombo resquiggle fast5/ Fus.contigs.polished.methilated.SRR1609157.sorted.vcf.fasta --processes 16 --dna  --num-most-common-errors 5 --overwrite`
`tombo plot max_coverage --fast5-basedirs fast5/ --plot-standard-model`

Any idea where the problem is?

Cheers

Luigi

_Originally posted by @lfaino in https://github.com/nanoporetech/tombo/issues/109#issuecomment-432638691_

**Comment by marcus1487** [comment]
This is generally an issue with file access to the fast5 read filenames. Did the resquiggle command complete successfully? And were these commands run one after another in the same environment?

**Comment by lfaino** [comment]
Hi Marcus,
yes the resquiggle finished without problem (i did not get any error) and the environment is the same. 
the commands were runnend one after another. I checked the results of the first command and start the second one.

Cheers
Luigi

**Comment by marcus1487** [comment]
I have not seen this behavior and I can't reproduce it locally, so if you could do a little bit of debugging here that would help to track down the problem. In order to track down this error if you could add a `raise` [here in the code base](https://github.com/nanoporetech/tombo/blob/master/tombo/_plot_commands.py#L901) (patch included below) and then install from source and re-run the plot command that should give some pointers to why this is happening.

In order to install from source clone the github repo (`git clone https://github.com/nanoporetech/tombo.git`), make the noted `raise` edit and then from the main repo directory run `pip install .`. Then if when you run the plot command you should get a more verbose output.

Full patch edit:
```diff --git a/tombo/_plot_commands.py b/tombo/_plot_commands.py
index 6e3d045..bdfb541 100644
--- a/tombo/_plot_commands.py
+++ b/tombo/_plot_commands.py
@@ -898,6 +898,7 @@ def get_r_raw_signal_data(
                 r_sig, _ = ts.normalize_raw_signal(
                     r_sig, 0, r_sig.shape[0], scale_values=scale_vals)
             except:
+                raise
                 if not_warned:
                     not_warned = False
                     th.warning_message(
```

**Comment by lfaino** [comment]
Thanks for the advice. I understand where thinks go wrong.
So, the software looks for the read at:

fast5/20180926_1027_Fv10027/pass/6/LabReverberi_PT_20180926_FAJ03500_MN24941_sequencing_run_Fv10027_51435_read_4858_ch_344_strand.fast5

while the read is at:

fast5/20180926_1027_Fv10027/fast5/pass/6/LabReverberi_PT_20180926_FAJ03500_MN24941_sequencing_run_Fv10027_51435_read_4858_ch_344_strand.fast5

the structure of my data is:
fast5/run_name/fast5/ ... as so on.

however, the tool discard the second fast5 folder and removes from the path.

Is it clear?

Cheers
Luigi

**Comment by lfaino** [comment]
here the error:

Traceback (most recent call last):
  File "/home/instancelf/.local/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo==1.5', 'console_scripts', 'tombo')()
  File "/home/instancelf/.local/lib/python2.7/site-packages/tombo/__main__.py", line 279, in main
    _plot_commands.plot_main(args)
  File "/home/instancelf/.local/lib/python2.7/site-packages/tombo/_plot_commands.py", line 2288, in plot_main
    plot_max_coverage(*base_args, **kwargs)
  File "/home/instancelf/.local/lib/python2.7/site-packages/tombo/_plot_commands.py", line 1663, in plot_max_coverage
    overplot_type, overplot_thresh, pdf_fn, alt_ref)
  File "/home/instancelf/.local/lib/python2.7/site-packages/tombo/_plot_commands.py", line 1575, in plot_model_single_sample
    (plot_intervals, plot_types, overplot_thresh, 'Group1'))
  File "/home/instancelf/.local/lib/python2.7/site-packages/tombo/_plot_commands.py", line 943, in get_plot_types_data
    SignalData = get_r_raw_signal_data(*plot_args)
  File "/home/instancelf/.local/lib/python2.7/site-packages/tombo/_plot_commands.py", line 897, in get_r_raw_signal_data
    r_data, reg_data.start, reg_data.end)
  File "/home/instancelf/.local/lib/python2.7/site-packages/tombo/tombo_helper.py", line 2082, in get_raw_signal
    with h5py.File(r_data.fn, 'r') as fast5_data:
  File "/home/instancelf/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/instancelf/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = 'fast5/20180926_1027_Fv10027/pass/6/LabReverberi_PT_20180926_FAJ03500_MN24941_sequencing_run_Fv10027_51435_read_4858_ch_344_strand.fast5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by marcus1487** [comment]
I'm a bit confused. When you say "software" and "tool" are you referring to tombo or another program performing work on the same reads?

**Comment by lfaino** [comment]
tombo plot gives this error:

IOError: Unable to open file (unable to open file: name = 'fast5/20180926_1027_Fv10027/pass/6/LabReverberi_PT_20180926_FAJ03500_MN24941_sequencing_run_Fv10027_51435_read_4858_ch_344_strand.fast5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

from the error i understand that tombo searches the read "LabReverberi_PT_20180926_FAJ03500_MN24941_sequencing_run_Fv10027_51435_read_4858_ch_344_strand.fast5" at the location "fast5/20180926_1027_Fv10027/pass/6/".

However, the read is not located at "fast5/20180926_1027_Fv10027/pass/6/" but at "fast5/20180926_1027_Fv10027/fast5/pass/6/". 
I know where the read is located because i searched for it 

if you compare the two paths:
"fast5/20180926_1027_Fv10027/pass/6/" (where tombo looks for) and 
"fast5/20180926_1027_Fv10027/fast5/pass/6/" (where the read is), you can find a difference.

is it clear?

Luigi

**Comment by marcus1487** [comment]
Yes I see the difference, but I'm not sure how Tombo would have found that path. This is the path tombo uses to find the read during the re-squiggle process. Did a the incorrect path exist at the time the re-squiggle command was run?

**Comment by marcus1487** [comment]
Ah! I have found it. This is indeed an error coming from [this line](https://github.com/nanoporetech/tombo/blob/master/tombo/tombo_helper.py#L1158) when the tombo index is written out.

I will put together a patch shortly and include this in the next release.

**Comment by lfaino** [comment]
ok thanks.
Sorry for the confusion in previous posts

**Comment by marcus1487** [comment]
No problem at all. I'm glad we got to the bottom of this! The current github repo should resolve this issue.
