### ISSUE TITLE
Divide by zero errors while using model sample compare with sample only estimates

### ISSUE THREAD

**Issue by dbobr** [nanoporetech/tombo#125]
Hello,

I have been receiving regular errors while trying to run model sample compare with sample only estimates. This usually generates a few errors while running and then the run fails to finish. The output is missing a few chromosomes. Error message is pasted below.

Running model_sample_compare without the --sample-only-estimates does not produce these divide by zero errors (however, it does have some file reading errors, but those do not prevent the software from finishing). I am performing these calls with per-read-statistics being calculated as well.

Typical errors that I'm getting for the --sample-only-estimates runs:
> Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/root/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4400, in _test_signif_worker
    use_standard_llhr, per_read_q, stat_type, prior_weights)
  File "/root/anaconda3/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4182, in compute_reg_stats
    r_data, ctrl_means, ctrl_sds, fm_offset, reg_data)
  File "/root/anaconda3/lib/python3.6/site-packages/tombo/tombo_stats.py", line 3736, in compute_sample_compare_read_stats
    r_z_scores = get_read_comp_z_score(r_means, read_start, read_end)
  File "/root/anaconda3/lib/python3.6/site-packages/tombo/tombo_stats.py", line 3721, in get_read_comp_z_score
    read_end - reg_start + fm_offset]
FloatingPointError: divide by zero encountered in true_divide

**Comment by marcus1487** [comment]
The `MIN_POSITION_SD` threshold was accidentally removed in this release. This value sets the estimated SD for a position to at least `0.01`. I will have a fix for this pushed soon, but I would warn that a samples only estimate with coverage low enough to produce this error would likely result in relatively poor results at low coverage positions. I would recommend setting a higher `--minimum-test-reads` value (default `1`) when using the `--sample-only-estimates` option. I would recommend a minimum of at least `50` and likely even higher than this for the method to work robustly. Setting this `--minimum-test-reads` should likely resolve this issue until I have pushed the fix.

**Comment by dbobr** [comment]
> The `MIN_POSITION_SD` threshold was accidentally removed in this release. This value sets the estimated SD for a position to at least `0.01`. I will have a fix for this pushed soon, but I would warn that a samples only estimate with coverage low enough to produce this error would likely result in relatively poor results at low coverage positions. I would recommend setting a higher `--minimum-test-reads` value (default `1`) when using the `--sample-only-estimates` option. I would recommend a minimum of at least `50` and likely even higher than this for the method to work robustly. Setting this `--minimum-test-reads` should likely resolve this issue until I have pushed the fix.

Thanks. I'll give that option a try and see if it resolves the current standing issue for me.

**Comment by dbobr** [comment]
To clarify: does --minimum-test-reads set the minimum in the control sample or in the test sample? My understanding was that it was for the test sample. If I'm getting per-read statistics, why would this value matter? Or is it being used for the aggregate statistics and that's where this issue is occurring?

**Comment by marcus1487** [comment]
`--minimum-test-reads` applies to both the control and test samples. Per-read statistics should be output for all positions on all test reads (where the control sample has the minimum coverage), but only those at higher coverage locations will be included in the aggregated reference-anchored summary stats file (i.e. input to text writing code). So if you are working with the per-read stat via the API then the `--minimum-test-reads` value should just ensure that this many reads were present to estimate the model from the control sample.

The `--minimum-test-reads` ensures that the estimate for the signal level and spread is accurate from the control sample. With fewer reads the estimate for the spread especially will be quite poor. This issue is coming from locations with only a single read in the control sample, thus producing the 0 SD estimate and resulting division by zero error.
