### ISSUE TITLE
Question about Optimization of drawing and reads filtering

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#132]
Hi:
     When I got current signal plot of tombo plot command.some observations(such in blue rect) Fluctuate within a larger signal range,making the drawing look messy and confusing.Another part of observations looks neat(green rect).
     I have reduced the number of poor-match reads by decrease `--signal-matching-score`.What else can I do?Or maybe it's just an aesthetic issue( can fix this by modifying R script).
![image](https://user-images.githubusercontent.com/37523816/48622433-b9dd4680-e9e1-11e8-84a9-a71fd81a6055.png)

**Comment by marcus1487** [comment]
I think this is more of an aesthetic issue. There are positions of signal with much higher within read variance which become hard to visualize using the raw signal plots. Also regions with small indels may contain packed signal in certain instances.

This was one of the reasons for the `--overplot-type` options (see examples [here](https://nanoporetech.github.io/tombo/plotting.html#over-plotting)). While these visualizations don't give a sense for the within read variation, they do help to see the between read variability at a location if that is mostly what you are after here.

As a last option you could look into editing the R scripts (from a source installation). Here is the location to edit for this particular plot type: https://github.com/nanoporetech/tombo/blob/1.5/tombo/R_scripts/plotGroupComp.R#L22
