### ISSUE TITLE
Issues regarding running tombo_stats_plot

### ISSUE THREAD

**Issue by joyshree12** [nanoporetech/tombo#133]
When I run the script for Tombo_stats_plot I always get the error segmentation fault. I could not figure out the reason behind it. Can give some suggestions regarding this?

**Comment by marcus1487** [comment]
Can you provide a bit more information in order to diagnose this issue. Specifically, could you provide the exact command entered as well as the full output leading up to the seg fault?

**Comment by joyshree12** [comment]
The problem is solved now, the issue was more with certain rights from the software itself.
