### ISSUE TITLE
annotate_raw_with_fastq updated file names

### ISSUE THREAD

**Issue by Lorenzda18** [nanoporetech/tombo#137]
Hello,

I have been having trouble annotating my raw fast5 files since the newest MinION update, could this be due to the new file name/structure? I currently have 1 read per fast5 and basecall offline with Guppy v 2.1.3. 

I constantly get "Added sequences to a total of 0 reads." and have not had this issue until recently.

Thanks!

**Comment by marcus1487** [comment]
Tombo is not currently mutli-FAST5 compatible. Do you know if these files are multi-FAST5 format (even though each file contains only a single read)? If they are multi-fast5 you could try to convert to single fast5 format and annotate.

**Comment by Lorenzda18** [comment]
Thanks for the quick reply!

That did the trick. I assumed that setting the software to 1 per file was creating a single read file, I was wrong.

Thanks again!
