### ISSUE TITLE
annotate not found

### ISSUE THREAD

**Issue by ceslobfer** [nanoporetech/tombo#138]
When I try to do:
tombo annotate_raw_with_fastqs --fast5-basedir PruebaTombo/Fast5_M1_Tombo/ --fastq-filenames allFQM1.fastq
This command fail with this error:
usage: tombo [-h] [-v]
             {resquiggle,preprocess,filter,detect_modifications,text_output,build_model,plot}
             ...
tombo: error: argument service_command: invalid choice: 'annotate_raw_with_fastqs' (choose from u'resquiggle', u'preprocess', u'filter', u'detect_modifications', u'text_output', u'build_model', u'plot')

I did base calling with Albacore. But the error does not seem to be for that reason.

**Comment by marcus1487** [comment]
The `annotate_raw_with_fastqs` command is found under the `preprocess` command subgroup. So run `tombo preprocess annotate_raw_with_fastqs`.

Is `tombo annotate_raw_with_fastqs` found in the docs somewhere that should be fixed?
