### ISSUE TITLE
Tombo does not support multi-fast5 format

### ISSUE THREAD

**Issue by matteocereda** [nanoporetech/tombo#141]
Hi All,

I am running tombo (cloned from git yesterday) on direct RNA sequencing (flowcell: FLO-MIN106D Kit: SQK-RNA002) data generated using the last version of MinKnow (version 18.12.4) but I have the following error:

```
[matteo@uv2000 test]$ tombo preprocess annotate_raw_with_fastqs --fast5-basedir fast5_pass/ --fastq-filenames fastq_pass/*.fastq --processes 10 --overwrite
[19:02:00] Preparing reads and extracting read identifiers.
****** WARNING ****** Basecalls exsit in specified slot for some reads. Set --overwrite option to overwrite these basecalls.
100%|##################################################################################################################################################################################################################| 1/1 [00:00<00:00,  8.93it/s]
[19:02:00] Annotating FAST5s with sequence from FASTQs.
****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.
0it [00:00, ?it/s]
[19:02:00] Added sequences to a total of 0 reads.
```

is there an issue with the basecalling folders or something related to the folder structure generated by MinKnow? I wonder whether you can help me in understanding this issue. 

Thanks in advance,
M

**Comment by drkennetz** [comment]
For clarity, after converting to single-fast5 do I then have to basecall with albacore, or can I use the guppy basecalled fastqs to annotate?

**Comment by marcus1487** [comment]
The guppy basecalled fastqs can still be used to annotate, but the guppy sequencing summary files will likely not work.

**Comment by drkennetz** [comment]
To follow up, running `multi_to_single_fast5` followed by `tombo preprocess` with using guppy fastqs to annotate works successfuly. Thank you for your help!

**Comment by marcus1487** [comment]
Thank you for confirming.

I will leave this open until a full fix with support for multi-fast5 has been added.

**Comment by matteocereda** [comment]
Hi guys, 
I followed your suggestions and it works! Thanks a lot!

**Comment by hygine** [comment]
May I ask a question , when can we use the tombo deal with the  new multi-fast5 format data ?

**Comment by callumparr** [comment]
@marcus1487 how can we use the base called file? This is concatenation of the passed read fast, or concatenation of passed and failed? Or directory to the guppy outputted directory?

**Comment by marcus1487** [comment]
@hygine , Tombo does not currently support the multi-FAST5 format and unfortunately we do not have an estimate for addition of support for this format. This requires a pretty major re-work of tombo. I have added a note to the README indicating how to convert multi-read FAST5 files before processing with tombo.

@callumparr , I am not sure exactly which base called file to which you are referring. Are you referring to the FASTA/FASTQ base calls or the FAST5 files? To the second question, tombo can be pointed to either the passed reads, the failed reads or a parent directory containing both. This choice is up to the user as to which reads to include in Tombo analyses. In either case there is no need to concatenate FASTA or FASTQ read files as the `tombo preprocess annotate_raw_with_fastqs` takes a list of files that will each be processed.

**Comment by lpryszcz** [comment]
Are you planning to add multi-fast5 support to tombo? converting multi-to-single is rather annoying ;)

**Comment by akk01** [comment]
How to check if the files are multi-fast5?

**Comment by cjw85** [comment]
@akk01 

You're question is better asked at https://github.com/nanoporetech/ont_fast5_api.
