### ISSUE TITLE
resquiggle for a subset of reads in a fastq file

### ISSUE THREAD

**Issue by marctormo** [nanoporetech/tombo#143]
Hello,

Is it possible to run the resquiggle command for a subset of reads stored in fastq file? 
First, I did the basecalling with albacore, obtaining fast5 and fastq files, and I mapped the fastq against a reference (a plasmid, 20% of reads approximately). Now, I'd like to run the resquiggle only with those reads mapping the plasmid but I don't know how to proceed.

Thank you very much!
Marc

**Comment by marcus1487** [comment]
If you are not worried about spurious alignments to the reference (i.e. reads from similar sources mapping to the plasmid of interest), then just running the whole batch of fast5s against the plasmid reference is recommended. Tombo performs alignment internally and any reads not mapping to the provided reference will not go forward in processing (reads are not forced to map to the reference). The read sequence extraction and mapping compute time is minimal compared to the re-squiggle step (in most cases), so there isn't much reason in terms of computational resources to separate out the reads first.

If spurious alignments are a concern (i.e. if you previously mapped reads to a set of references, but only wanted to re-squiggle the reads mapping to one reference record), then copying the FAST5s to a new directory would be recommended, but that is a bit more work.

**Comment by marcus1487** [comment]
You could also run the re-squiggle function once against a combined reference and [apply filters](https://nanoporetech.github.io/tombo/filtering.html) (relatively fast and reversible operations to the tombo index) to the reference sequence name of interest when you only want to process those reads. Note that there are some default filters from the resquiggle command that you would most likely want to apply after a `clear_filters` call.

**Comment by marctormo** [comment]
I've just ran re-squiggle twice (once with each reference), but I'll take into account and maybe I could try it next.
Thanks!
