### ISSUE TITLE
Analyzing multiplexed samples

### ISSUE THREAD

**Issue by AlexanderDilthey** [nanoporetech/tombo#144]
Hi,
What's the best way to analyze multiplexed samples with tombo?

To give an example, assume that we sequenced 12 relatively similar bacterial strains, which we suspect exhibit different base modification... I'm worried that the genome assemblies are not sufficiently dissimilar to reliably determine the alignment of individual reads without the barcode information.

Best wishes,

Alexander

**Comment by marcus1487** [comment]
If the samples are barcoded, then analyzing the samples after separating by barcodes would be best. If the samples are not barcoded and the genomes are quite similar, then there certainly may be issues with tombo and separating the reads derived from each sample. I would suggest barcoding samples in this setting.

**Comment by AlexanderDilthey** [comment]
Thank you!
