### ISSUE TITLE
Confusion about inconsistencies in "Text Outputs" and "Plotting Commands" results

### ISSUE THREAD

**Issue by wlhCNU** [nanoporetech/tombo#146]
Hi marcus:
    I have two questions to ask you.
    **The first question:**   As the following two pictures and commands（A and B） show,  Picture A is the partial result of command A , and picture B is the partial result of command B. What puzzles me is that the results between the two reads coverage statistics(see the red box in the figures) are different. How to explain this situation?	
    **The second question:**  As shown in commands B, C, and D, these three commands (parameter differences between commands have been shown in bold) have some subtle differences between the resulting graphs, how to explain What is the difference in this result?
                
Thanks
lihui

############################################################################

**command A**: 	tombo text_output browser_files  --fast5-basedirs /project/fast5/  --statistics-filename  /project/sample.alt_modified_base_detection.5mC.tombo.stats --file-type coverage

	
**command B**:    tombo plot  most_significant  --fast5-basedirs              /project/fast5/    --statistics-filename   //project/sample.alt_modified_base_detection.5mC.tombo.stats     --overplot-type Downsample --pdf-filename Downsample.pdf  **--plot-alternate-model 5mC** 

**command C**:     tombo plot  most_significant  --fast5-basedirs              /project/fast5/    --statistics-filename   //project/sample.alt_modified_base_detection.5mC.tombo.stats     --overplot-type Downsample --pdf-filename Downsample.pdf  **--plot-alternate-model 5mC  --plot-standard-model**

**command D:**    tombo plot  most_significant  --fast5-basedirs              /project/fast5/    --statistics-filename   //project/sample.alt_modified_base_detection.5mC.tombo.stats     --overplot-type Downsample --pdf-filename Downsample.pdf   **--plot-standard-model**

**Picture A**
![coveragea](https://user-images.githubusercontent.com/42363546/52777019-d8ed8200-307d-11e9-86ab-4d5e554da0c3.png)

**Picture B**
![coverage](https://user-images.githubusercontent.com/42363546/52776872-81e7ad00-307d-11e9-9b4e-545317590760.png)

**Comment by marcus1487** [comment]
For the first question, the plot header is computing the reads covering any portion of the plotted window, while the `text_output` command computes the per-location coverage values. That is the reason for the difference.

For the second question, I think commands B and C should produce the same plot. When an alternative model is requested the default is automatically loaded. The third command only plots the standard model. See examples of model plotting commands [here](https://nanoporetech.github.io/tombo/plotting.html#model-plotting).

One other difference you may be seeing is that by default reads are randomly downsampled for plotting (indicated by the asterisk in the plot title). Plotting the raw signal for 910 reads in this case would likely make the PDF very hard to open due to the amount of data plotted. Thus by default (via `--overplot-threshold` option) only 50 reads are plotted. You can change this behavior with the `--overplot-threshold` and `--overplot-type` options ([docs here](https://nanoporetech.github.io/tombo/plotting.html#over-plotting)).

**Comment by wlhCNU** [comment]
Thank you very much, I have already understood that your explanation is correct. In addition, I still have questions to ask you:

 **a.** Is the result in **command E** list below based on the coverage of **command F** or based on the coverage of **command G**?

**b.** Relative to the **command F**, the result of the **command G** has specific practical significance?

**c.** If I want to get the number of reads that support 5mC methylation at each site, the number of reads that don't support methylation, and the total read coverage of the site. What command can we get this part of the result?

**d.** Which command parameter can adjust the threshold of 5mC methylation in the reads covering a specific site? Can we get the results of this part of the visualization directly(such as text format results) ?

###############################################################################
**commond E:**    tombo text_output browser_files --fast5-basedirs /project/fast5/ --statistics-filename /project/sample.alt_modified_base_detection.5mC.tombo.stats **--file-type dampened_fraction**

**commond F:**  	tombo text_output browser_files --fast5-basedirs /project/fast5/ --statistics-filename /project/sample.alt_modified_base_detection.5mC.tombo.stats **--file-type coverage**

**commond G:**     tombo text_output browser_files --fast5-basedirs /project/fast5/ --statistics-filename /project/sample.alt_modified_base_detection.5mC.tombo.stats **--file-type valid_coverage**

**Comment by marcus1487** [comment]
a. coverage is from command G.

b. More details can be found about per-read statistic aggregation in the [docs here](https://nanoporetech.github.io/tombo/modified_base_detection.html#aggregating-per-read-statistics). In short reads with less significant results are not included in the final fraction reported. Thus valid coverage is the reads contributing to the fraction values and coverage is all reads spanning a genomic location.

c. There is not one file that contains all of this information, but as discussed this information can be extracted from the coverage, valid_coverage and fraction files.

d. I'm afraid I am not understanding this question. I think the information you are looking for is found within the produced text files. For plotting these locations the `plot genome_locations` can be used once the specified locations have been identified by whatever criterion you apply.
