### ISSUE TITLE
tombo index file from previously resquiggled data

### ISSUE THREAD

**Issue by flokraft85** [nanoporetech/tombo#147]
Hi,
I run tombo resquiggle on a data set over the last week. Unfortunately the resquiggle process stuck several time (no progress on reads for more that 12h), so I have to restart it. This happens also when 99% of the reads are processed, so I have to restart the short before all reads are processes. I didn't choose the --overwrite option, to keep the resquiggle data from the aborted run before, because it would take so long. But after finishing the resquiggle command the tombo index file is missing and I got the error below:
5 most common unsuccessful read types (approx. %):[--corrected-group] and [--ove   97.8% (11551399 reads) : Tombo data exists in [--corrected-group] and [--overwrite] is not set                                                              
     -----                                                                      
     -----                                                                      
     -----                                                                      
     -----                                                                      
100%|████████████████████████████| 11817254/11817254 [5:25:49<00:00, 604.47it/s]
[20:59:37] Final unsuccessful reads summary (97.8% reads unsuccessfully processed; 11558133 total reads):
    97.8% (11558133 reads) : Tombo data exists in [--corrected-group] and [--overwrite] is not set           
[20:59:39] Saving Tombo reads index to file.
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 247, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

Is there a possibility to generate the tombo index file from previously resquiggled data or do I have to resquiggle all the data with the --overwrite command, which would be very annoying because it would take more than a week to do so.
Thanks in advance!

**Comment by marcus1487** [comment]
You can use the `tombo filter clear_filters` command as a bit of a hack to produce the index file. This will read the information from the individual index files and create the index in memory and then write it to disk. This will not analyze the reads that were not processed with the original run, but seeing as it looks like you completed 99% of your reads I am guessing this might be sufficient for your purposes. Note also that the index file is not necessary for further processing, but slows processing dramatically as every fast5 must be opened for most every other tombo command.

For the stalling, I think this is likely related to #111 and #139 . I have not found the source of this error yet, but an installation from github should at least produce better error codes for the time being.

**Comment by flokraft85** [comment]
Thanks Marcus for the fast response.
I will try this.

**Comment by flokraft85** [comment]
Hi Marcus,
all of the downstream analysis went fine with the new index file! Thanks again for this very useful hint!
