### ISSUE TITLE
Analyse methylome

### ISSUE THREAD

**Issue by SADNA1** [nanoporetech/tombo#148]
We have little experience with the nanopore system, but we want to analyse methylation (5mC, 4mC and 6mA)  from DNA from Cyanobacteria. 
Firstly, do we need to sequence a reference DNA without modifications to compare with the methylated sequence?
What kind of analysis do you advise us to obtain the sequence? 
Are there some paper to include this type of experiement?
Thank you

**Comment by marcus1487** [comment]
For 5mC and 6mA, tombo includes alternative models (for DNA). This would be the recommended method to obtain the highest quality results for those modifications.

For 4mC, we do not have a trained model at this time. So the options (as discussed on the documentation page [here](https://nanoporetech.github.io/tombo/modified_base_detection.html)) are de novo discovery (which is a bit error prone for single molecule detection) or sample comparison (control vs native). Note also that both of these methods will not identify the type of modification or exact location of the modification on a per-read or per-site basis.

As noted in the documentation [here](https://nanoporetech.github.io/tombo/tutorials.html#de-novo-bacterial-modified-base-detection), if you are searching for motif driven modifications the de novo and sample comparison methods should work very well for the discovery of motifs. Then these motifs can be used to create a more accurate motif-specific model for use on more accurate per-read calls.

I hope this information helps in designing your experiments. There is not a paper outlining all of the advantages and disadvantages of the modified base detection methods, but I would recommend the documentation page which has a lot of useful information in making these decisions.
