### ISSUE TITLE
Some issues with alternative_model -standard-LLR option

### ISSUE THREAD

**Issue by yaeba** [nanoporetech/tombo#149]
Hi Marcus,

Upon running ```tombo detect_modifications alternative_model``` with ```--standard-log-likelihood-ratio``` option, the program exits with an error saying ```TypeError: <built-in function c_calc_llh_ratio_const_var> takes 4 positional arguments but 3 were given```. 

Subsequently, the variable ```running_llhr``` from ```c_calc_llh_ratio_const_var``` function was not initialised to 0 which caused it to return NULL without raising an error. This should be an easy fix. Thanks for your work on the tool.

**Comment by marcus1487** [comment]
Thank you for all the effort to dig down and fix this bug. I will add a test case to the test script for this bug and merge shortly.

**Comment by marcus1487** [comment]
Merged pull request to fix the issue. Thanks!
