### ISSUE TITLE
Tombo trial data

### ISSUE THREAD

**Issue by SADNA1** [nanoporetech/tombo#152]
Hello everyone,

We are trying to execute the Tombo's suite, but we do not found any example to get an approach of the use of it.

In the web page (https://nanoporetech.github.io/tombo/index.html) it is said "In this example, an E. coli sample is tested for dam and dcm methylation (present in lab E. coli; CpG model also available for human analysis)" but we do not find any link to the data.

Could you send us or indicate us where we can download the example data to do a trial?

Thanks in advance, 

SADNA1

**Comment by marcus1487** [comment]
There is not currently any supported test data for Tombo at the moment.
