### ISSUE TITLE
example data for tombo

### ISSUE THREAD

**Issue by sdwien** [nanoporetech/tombo#157]
Dear colleagues,
I was wondering whether you could make some test data for tombo available? E.g. something like the fast5 data from the in vitro modified and unmodified transcripts used in this paper:
https://www.nature.com/articles/nmeth.4577 by Daniel Garalde et al.
This would be very helpful to set up analysis workflows, play around with settungs and learn about how the outputs for each of the tombo commands look like.
Many thanks, best, Sophia

**Comment by marcus1487** [comment]
There is no test data available for tombo at this time. See #152 #20 for discussions concerning test data.
