### ISSUE TITLE
Question about API of Extract the raw signal 

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#158]
Hi,marcus
Is there a API of tombo  capable of extracting raws signals that deviate from the expected signal value of  each genomic base in a region?Or export the readID to which the signal belongs
Like the blue area signal in the image below:
![away from expect](https://user-images.githubusercontent.com/37523816/54686767-ffa74880-4b54-11e9-9e47-e8bae6e32621.png)

**Comment by marcus1487** [comment]
The PerReadStats object and [`get_region_per_read_stats` function](https://nanoporetech.github.io/tombo/tombo.html#tombo.tombo_stats.PerReadStats.get_region_per_read_stats) would be the function to use here. I would recommend running `detect_modifications` with the `--fishers-method-context 0`. This will give the results for testing each segment of signal against the grey distributions (without any moving window combination of p-values). Extraction of per-sample raw signal is a bit more complicated, but possible. The API is not designed for that specific task as modified base detection uses the mean signal levels for each read at each position for modified base detection.

**Comment by marcus1487** [comment]
Has this addressed the issue here?
