### ISSUE TITLE
per-read-statistics extraction of read name 

### ISSUE THREAD

**Issue by drkennetz** [nanoporetech/tombo#159]
I am writing a little program to use your API to generate the per-read-stat to a csv file and I noticed that the output array basically converted the readname from a bytes object to a string without decoding it first. So for example I generated the interval data:

    interval_data = th.intervalData(chrmint, startint , stopint, strandint)

Then got the region of interest:

    region_data = ts.PerReadStats(stats_file).get_region_per_read_stats(intrval_data)

And when I print:

    [(106009846,  0.75305769, "b'e114158c-1028-4570-87c1-c7d946566fdb'")
      (106009342, -1.82408804, "b'e114158c-1028-4570-87c1-c7d946566fdb'")
      (106009206, -0.53283592, "b'e114158c-1028-4570-87c1-c7d946566fdb'")
      (106009158, -3.62699475, "b'e114158c-1028-4570-87c1-c7d946566fdb'")
      (106009152,  0.09699272, "b'e114158c-1028-4570-87c1-c7d946566fdb'")
      (106008933, -0.26551352, "b'e114158c-1028-4570-87c1-c7d946566fdb'")]

So essentially the 3rd item in each array was a bytes object, that just got converted to a string implicitly somewhere instead of being decoded first. Numpy might have done this when putting it in the array, and it's not a big deal. It just seems like an easy fix on the front end rather than the back end. However, this may not be true!

**Comment by marcus1487** [comment]
I think I saw this in some python 2 tests previously. I have tried to keep tombo python2/3 compatible, but with the python2 end of life in site I have focused on python3 compatibility. Are you using python3 for this test?

**Comment by drkennetz** [comment]
I am using python3. Just to confirm, if I do: `for x in region_data: print(type(x[2]))` it returns string for all arrays. It may be something to do with np.void typing, as it tries to dynamically assign types. For example, loading all these into a pandas dataframe returns them all as objects. But the read name is just a string in the array.

**Comment by marcus1487** [comment]
I was able to reproduce this error and have just pushed a fix. It had to do with the storage of the statistics, so tombo stats files would need to be re-generated, but should be fixed.
