### ISSUE TITLE
clustering per read statistics

### ISSUE THREAD

**Issue by OlivierZablo** [nanoporetech/tombo#165]
Dear Marcus,

Thank you for your extensive tombo documentation and for your software, it's helping my research tremendously!

On to my Q: I've generated per-read tombo statistics file, and after visualization it looks like many of the reads have different methylation profiles (i.e., for the same genome, each represented by a single read (my genome is 9kb), many variants exist such that almost no base is consistently found to be modified at always the same location (except for a few)). So to untangle this I was thinking to cluster the reads according to base modification sites and only consider those sites (only those with high P-values) maybe with UPGMA or hierarchical clustering. My Q is which route/method and what metric from the stats file would you select for this kind of clustering? In another thread, I saw you linked extracting the stats with the tombo's API so that should still be the way to extract the data I assume?

Thanks a lot in advance and thanks again for making Tombo!

**Comment by marcus1487** [comment]
Tombo provides a command to cluster and plot per-read statistics ([here](https://nanoporetech.github.io/tombo/plotting.html#per-read-statistic-plotting)), but I have found that this command is most useful for clustering motif-specific model results as these are much less error prone. If you would like to dig down a bit further, [here is a pointer](pdist) to the clustering code used for this plotting command and [here](https://github.com/nanoporetech/tombo/blob/1.5/tombo/_plot_commands.py#L1038) is per-read statistic extraction code.

**Comment by OlivierZablo** [comment]
Thanks for the pointers! I'll dig into it and see what I can do.
