### ISSUE TITLE
Tombo Resquiggle Hangs when close to completion

### ISSUE THREAD

**Issue by nhartwic** [nanoporetech/tombo#167]
I don't really have much useful to add other than the title. I'm currently running tombo on a dataset about 1TB in size. The progress has been stuck at just shy of 100% for over two days now.

Output:
[18:51:04] Loading minimap2 reference.
[18:51:41] Getting file list.
[18:51:55] Loading default canonical ***** DNA ***** model.
[18:51:57] Re-squiggling reads (raw signal to genomic sequence alignment).
100%|█████████▉| 2662936/2663004 [143:00:20<00:13,  5.17it/s]

Version
Tombo version: 1.5

Command
tombo resquiggle --processes 16 --ignore-read-locks --overwrite  \
    /home/nhartwic/scratch/core/MJ/spec2/fast5/ \
    /home/nhartwic/scratch/core/MJ/spec2/spec2.all.minimap.racon3.fasta

Some final notes. This isn't the first time I've tried running tombo on this dataset. First run seemed to go fine but only about 60% of reads were successfully resquiggled. Tombo reported an average coverage across the assembly of ~1.5 and should have been about 12 or 24 depending on whether coverage reports are strand specific. Turns out, the fastq file I had was truncated and missing a lot of data. I re-preprocessed the fast5 files using the complete fastq dataset and attempted to resquiggle the reads using the command above. Everything seemed to be going fine (albeit slowly) until a few days ago when the process just hung inexplicable. The process itself is still live for what its worth but I haven't had output in multiple days.

Ideas comments concerns would be appreciated.

**Comment by marcus1487** [comment]
This is likely due to very long reads (which take a very long time to process; usually unsuccessfully). I would suggest adding these options to your resquiggle command: `--signal-length-range 0 500000` and `--sequence-length-range 0 50000`. These values may become the default in a coming release to avoid these issues in the future (along with a note about long reads on the README).

As a hack for the moment, you can use the `tombo filter clear_filters` command (described [here](https://github.com/nanoporetech/tombo/issues/147#issuecomment-464156516)) to create a tombo index file from a run that was quit before completion.

**Comment by nhartwic** [comment]
Ok, I'll go ahead and kill the run then and make the index with tombo filter clear_filters.

Is there any way to create the resquiggle report which states what percent of reads were successfully processed, what percent wasn't, and what the failures were?

**Comment by marcus1487** [comment]
There is not a tombo command for this, but the error modes are stored in a `status` attribute within the corrected sub-group. The read fast5s could be iterated over and the values of this attribute could be stored in a counter to generate such a report. Note that this will not account for errors in file IO as they could disallow the writing of this slot, but all the "normal" error modes are stored in this attribute.

**Comment by nhartwic** [comment]
Making the new index went well. Coverage is still below what I was expecting but is now in the ball park (~60%) of what it should be. I never did check the fast5 files to see what percentage of reads were successfully resquiggled though. And if longer reads are more likely to fail to resquiggle, a relatively small percent of resquiggle-failed reads could be responsible for relatively large deviations from expected coverage.

Thanks for all the help. I think we can consider this "resquiggle hangs" issue closed. Unless you just want to leave it open to remind you to update the default signal-length-range and sequence-length-range values.
