### ISSUE TITLE
interpreting browser file outputs

### ISSUE THREAD

**Issue by OlivierZablo** [nanoporetech/tombo#169]
Hi !
Using tombo text_output browser_files using the "difference" flag, I got a wig file and opened it with IGV. In the PNG attached is a section of the genome, and barcharts represent the difference range. May be a stupid Q, but so which would be indicative of a modified site? when both high + and low - values are found per base? And at what difference threshold should I consider valid? Thanks in advance!
![cropped_difference](https://user-images.githubusercontent.com/49452328/56301521-fd112200-6105-11e9-98bf-5e3c4c9a13f6.png)

**Comment by marcus1487** [comment]
Modified bases may present as positive or negative deviations from the expected signal and often a combination of positive and negative in a small region around the modification (as output from the `difference` option). At a single base there is only one value (which is either positive or negative). IGV might be making it look as though there are positive and negative values when zoomed out based on the aggregation method. Using difference alone is likely not a great2 measure to define modifications efficiently. The difference statistic becomes much more variable at low coverage (taking the average signal over fewer reads). Thus I would guess that the regions with larger signal deviation might come from lower coverage regions.

The difference output may be useful for some more speculative or in depth analyses, but are likely not useful as a direct measure to detect modifications.

**Comment by OlivierZablo** [comment]
Ok thank you that makes sense. I've made other charts using the 'statistic' output option to show the overall modification landscape of a genomic region. What value for each base would you consider valid? (the way I understand it depends on the coverage for a particular genomic coordinate right? So the more coverage the better confidence?) I have values from 0 to 0.96 for each base and have plotted that. I have 5 values that really stand out from the rest. What is this metric exactly? A % of occurrence for this base to be predicted modified across the reads? Thanks!

Also, in a previous thread of mine, you kindly provided a link to the per-read clustering part of your code...but the link was broken. Could you please provide it again? Really ap[appreciating all your help!

**Comment by marcus1487** [comment]
The meaning of the `statistic` value depends on the test performed. Using the default `sample_level_compare` settings this is the KS-test statistic. You can read more about the different tests available [here in the docs](https://nanoporetech.github.io/tombo/modified_base_detection.html#canonical-sample-comparison-methods). This test statistic is unfortunately quite sensitive to lower coverage as well (though using the default `--minimum-test-reads` value of 50 should mitigate this issue). The threshold for a valid result might change depending on a number of factors, including the modification of interest, sequence context, run conditions and more, so a global valid threshold recommendation is difficult for this method.

I have updated that previous comment with the correct link, and [here](https://github.com/nanoporetech/tombo/blob/1.5/tombo/tombo_stats.py#L141) it is again.
