### ISSUE TITLE
annotate_raw_with_fastqs crashes if .fastq file contains extra identifiers

### ISSUE THREAD

**Issue by baklazan** [nanoporetech/tombo#17]
I have a .fastq file that contains records from a superset of my .fast5 files. When I run
`tombo annotate_raw_with_fastqs --fast5-basedir <directory of .fast5 files> --fastq-filenames <.fastq file>`
it crashes with the following message:

```
Preparing reads and extracting read identifiers.
Annotating FAST5s with sequence from FASTQs.
********* WARNING ********
	Some records from BC01.fastq contain read identifiers not found in any FAST5 files.
Traceback (most recent call last):
  File "/usr/local/bin/tombo", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tombo/__main__.py", line 158, in main
    tombo_helper.annotate_reads_with_fastq_main(args)
  File "/usr/local/lib/python2.7/dist-packages/tombo/tombo_helper.py", line 1584, in annotate_reads_with_fastq_main
    annotate_with_fastqs(args.fastq_filenames, fast5s_read_ids, fastq_slot)
  File "/usr/local/lib/python2.7/dist-packages/tombo/tombo_helper.py", line 487, in annotate_with_fastqs
    with h5py.File(fast5s_read_ids[read_id]) as fast5_data:
KeyError: 'be188b23-3278-4d09-9fea-24e2d498d541'
```

I think I can fix this, pull request coming soon.

**Comment by marcus1487** [comment]
Ah, I had not considered that possibility. Indeed I think this should be a relatively easy fix. Thanks!

**Comment by marcus1487** [comment]
It actually looks like I did think of that, but made a mistake in the logic where I try to only warn you once. Here is a patch that should fix the issue. I will include this in the next release.

`diff --git a/tombo/tombo_helper.py b/tombo/tombo_helper.py
index b7ae9cd..b3808a6 100644
--- a/tombo/tombo_helper.py
+++ b/tombo/tombo_helper.py
@@ -511,11 +511,12 @@ def annotate_with_fastqs(fastq_fns, fast5s_read_ids, fastq_slot):
                 # after the "@" record delimiter up to the first white space or
                 # underscore
                 read_id = fastq_rec[0].split()[0].split('_')[0][1:]
-                if not been_warned_ids and read_id not in fast5s_read_ids:
-                    been_warned_ids = True
-                    _warning_message(
-                        'Some records from ' + fastq_fn + ' contain read ' +
-                        'identifiers not found in any FAST5 files.')
+                if read_id not in fast5s_read_ids:
+                    if not been_warned_ids:
+                        been_warned_ids = True
+                        _warning_message(
+                            'Some records from ' + fastq_fn + ' contain read ' +
+                            'identifiers not found in any FAST5 files.')
                     continue
 
                 with h5py.File(fast5s_read_ids[read_id]) as fast5_data:
`

**Comment by baklazan** [comment]
Exactly. I didn't expect you to be so fast.
