### ISSUE TITLE
E.coli raw data(fast5)

### ISSUE THREAD

**Issue by Macy-Zhao** [nanoporetech/tombo#170]
Hi,guys
Where is raw data of E.coli?
    Now,I need raw data(fast5) of E.coli that you menationed in the paper to test, so how I can get raw data?
 thank you for replying!

**Comment by Macy-Zhao** [comment]
I need raw signal data, please reply me as soon as possible!

**Comment by marcus1487** [comment]
There is no data officially supported with the tombo software. The nanoraw manuscript was never published and unfortunately the raw data was not submitted to a public repository. Thus I don't have a link to the data used in the nanoraw pre-print at this time. There are several other closed issues in this repo with pointers to useful test data for tombo. Hopefully one of these data sets could help with you needs.

**Comment by Macy-Zhao** [comment]
Thank you!
