### ISSUE TITLE
where does the Method get_r_reg_stats return to

### ISSUE THREAD

**Issue by OlivierZablo** [nanoporetech/tombo#172]
I was wondering where the get_r_reg_stats method returns to?

**Comment by marcus1487** [comment]
I don’t see any reference to this method in the current code base. Could you provide a link to this method?

**Comment by OlivierZablo** [comment]
The Q referred to that part of the [per read extraction] code that you linked in a previous post (https://github.com/nanoporetech/tombo/issues/165#issuecomment-481366369), specifically the per-read statistic extraction code. Thanks!

**Comment by marcus1487** [comment]
Got it. The method is `get_reg_r_stats` not `get_r_reg_stats` so my search didn't find anything. That method is called from [here](https://github.com/nanoporetech/tombo/blob/1.5/tombo/_plot_commands.py#L1604).

For future reference, you can search for all instances of any function on github by typing the method name into the search bar on github from that repository.

**Comment by OlivierZablo** [comment]
Thank you so much, really appreciate it. Sorry for the typo that caused additional searches. Also thanks for the tip to search more efficiently!
