### ISSUE TITLE
Resquiggle different fast5 format

### ISSUE THREAD

**Issue by pterzian** [nanoporetech/tombo#173]
Hi Marcus,

I have some questions about the fast5 format red by Tombo. It seems that my dataset is not following the standart format :
- Preprocessing told me : 

> Basecalls exist in specified slot for some reads. Set --overwrite option to overwrite these basecalls.

So I tried to directly resquiggle as I have done before.
- Resquiggle tells me : 

> Reads do not to contain basecalls. Check --basecall-group option if basecalls are stored in non-standard location or use `tombo annotate_raw_with_fastqs` to add basecalls from FASTQ files to raw FAST5 files.

Then I check what's inside the fast5 and this is what I found :

![tombo_issue](https://user-images.githubusercontent.com/18738470/57085350-4b284700-6cfc-11e9-916a-c9aa2d0983de.png)

So it seems to me that the fastq headers are already written in each read blocks. I tried to give the --basecall-group option the "Basecall_1D_000" but it didn't work as well (I may have not well understood the documentation on this part)

Would my issues be related to the fact my fast5 are multiplexed ? 

ps: I recently had other fast5 format issues with the Simpson & al human ont project (2017), fastq were already into the fast5, I only managed to resquiggle 2 runs on 3 (MSssI & PCR) with less that 50% resquiggled reads (fast5 contained 1D & 2D reads)

thanks a bunch for the support,

Paul

**Comment by marcus1487** [comment]
For the sent screenshot these appear to be mutli-fast5 files. Tombo unfortunately only works with the single-read format at this time. As noted in the README (added recently) you can use the `multi_to_single_fast5` command from the [ont_fast5_api package](https://github.com/nanoporetech/ont_fast5_api).

**Comment by pterzian** [comment]
Thank you for the quick answer, I saw this package recently and thought it may do the trick. I will let you know how it went.

**Comment by pterzian** [comment]
Worked like a charm!
