### ISSUE TITLE
single-read-threshold argument for aggregate_per_read_stats undocumented

### ISSUE THREAD

**Issue by Shians** [nanoporetech/tombo#178]
`tombo detect_modifications aggregate_per_read_stats` requires a `single-read-threshold` argument but I can't seem to find anything about this in the [documentation](https://nanoporetech.github.io/tombo/modified_base_detection.html#aggregating-per-read-statistics). I assume it's the same as in help string for `tombo detect_modifications alternative_model` so it would be `--single-read-threshold -1.5 2.5` but it would nice to have it be documented explicitly under the relevant function, or have a default value.

**Comment by marcus1487** [comment]
The `--single-read-threshold` argument is the same one as found in the `tombo detect_modifications alternative_model` command, but this value has a different default for each of the different testing methods (`de_novo` and `model_sample_compare`) and sample type (`DNA` and `RNA`). Given that the purpose of the `aggregate_per_read_stats` command is to apply a new threshold value a default value is not provided. The wording in the linked documentation section is attempting to document this behavior.

If you run `tombo detect_modifications aggregate_per_read_stats -h` on the command line you can see the documentation for this parameter within this command as follows:
```
P-value or log likelihood ratio threshold when
computing fraction of significant reads at each
genomic position. If two values are provided,
statistics between these values are not considered.
```

Let me know if this is still confusing or where further documentation would be helpful.

**Comment by Shians** [comment]
Thanks Marcus, I'll submit a pull request with some documentation requests in the near future.
