### ISSUE TITLE
parameter "--file-types" using questions

### ISSUE THREAD

**Issue by forrwill** [nanoporetech/tombo#181]
Hello,
I am using the nanopolish and tombo for methylation calling, and I tested the two software with the data NA12878. but I find that I can not read the results of tombo. It is a binary format, can I transform it to a readable txt file?
and at the same time,  I want to output the methylation coverage,  valid coverage, fraction, signal_sd ....  can I output these information in a file? and  runing the command line as below:
tombo text_output browser_files --fast5-basedirs ../../fast5_files/ --statistics-filename native.NA12878.5mC.tombo.stats --genome-fasta ../../reference.fasta --browser-file-basename 5mC --file-types {coverage,valid_coverage,fraction,dampened_fraction,signal,signal_sd,dwell,difference,statistic}

**Comment by marcus1487** [comment]
The `--file-types` desired options should be separated by spaces (and remove the curly brackets). The display in the help text as provided in a standard format for displaying options in python code argument parsing.

With this fixed all desired outputs should be produced.

**Comment by liujiazhe** [comment]
> The `--file-types` desired options should be separated by spaces (and remove the curly brackets). The display in the help text as provided in a standard format for displaying options in python code argument parsing.
> 
> With this fixed all desired outputs should be produced.

thank you
I have fixed it, and I want output all these statistics in one file by running one time,  but there is still an error exists, I don't know why.
command line:  tombo text_output  browser_files --fast5-basedirs /public2/Bio/Project/jzliu/Nanopore/NA12878/fast5_files/  --genome-fasta /public2/Bio/Project/jzliu/Nanopore/NA12878/reference.fasta --statistics-filename native.NA12878.6mA.tombo.stats --browser-file-basename native.NA12878.6mA.tombo --file-types coverage valid_coverage fraction dampened_fraction signal signal_sd dwell statistic

error:  
![image](https://user-images.githubusercontent.com/41096851/58771703-27e90400-85e8-11e9-9df1-f304d90f386b.png)

**Comment by marcus1487** [comment]
I believe this issue may have been fixed since the last release. Could you try an installation from github to see if the issue is resolved. First uninstall tombo then use `pip install git+https://github.com/nanoporetech/tombo.git`

**Comment by marcus1487** [comment]
Has this resolved your issue?
