### ISSUE TITLE
Tombo broken pipe while using detect_modifications

### ISSUE THREAD

**Issue by forrest1988** [nanoporetech/tombo#183]
Hi,

I am running modified bases detection using the following command:
tombo detect_modifications alternative_model --fast5-basedirs AML.tombo/workspace/pass/0 --statistics-file-basename AML_Tombo --per-read-statistics-basename AML_Tombo --alternate-bases 5mC --processes 16 --corrected-group RawGenomeCorrected_000  

And I end up with the following Errors:
~~~
[10:56:48] Parsing Tombo index file(s).
[10:56:48] Performing alternative model testing.
[10:56:48] Performing specific alternate base(s) testing.
[10:56:48] Calculating read coverage regions.
[10:56:48] Calculating read coverage.
[11:08:08] Performing modified base detection across genomic regions.
 40%|██████████████████████████████████████████████████████████████████████████▎                                                                                                              | 220919/550134 [04:12<06:16, 875.00it/s]
Traceback (most recent call last):
  File "/projects/rosikw/anaconda3/envs/tombo_37/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/projects/rosikw/anaconda3/envs/tombo_37/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/projects/rosikw/anaconda3/envs/tombo_37/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/projects/rosikw/anaconda3/envs/tombo_37/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
~~~

For exactly the same input data, this error pops up after 0-1% of the analysis, sometimes at 40% or more (like in the above example). The most surprising is that sometimes it was actually going through the entire analysis, but I have multiple datasets so I couldn't just take these "successful" proceed with other analyses.

I was trying running Tombo installed in conda environments with python 3.6 and 3.7, both raise the same errors. Have you encountered this kind of issue for methylation detection step before?

Thanks,
Wojciech

PS. At some point I was thinking that in fact this issue might be related with some side packages, as in the past I was using Tombo v1.2.1.2  I have never had this problem. Could you send dump your conda environment (e.g. with "conda list --explicit > fileName.txt"), where you know you have working version of Tombo v1.5 and post a link to it, so that it would be possible to reproduce exactly the same environment on my end?

**Comment by marcus1487** [comment]
This is likely related to #139. In the past these errors have been due to ultra long reads (either in sequence or signal space). In the latest release (1.5) this results in a sub-processing dying silently and then a multiprocessing queue or pipe trying to send information to the dead process.

For the `detect_modifications` step I have not seen this that I can recall. I suspect that this may be due to a similar core issue though, this time probably resulting from very high coverage regions. I would suggest to lower the `--multiprocess-region-size` (try `1000`) argument in order to process smaller chunks of data in memory at one time.

**Comment by forrest1988** [comment]
Hi Marcus,

I have applied --multiprocess-region-size flag with 1k value. So far so good. I will get back to you next week (or earlier) to confirm that it worked and hopefully close the issue.

Thanks,
Wojciech

**Comment by forrest1988** [comment]
Hi Marcus,

Everything worked now, Thanks!

Cheers,
Wojciech
