### ISSUE TITLE
Question about the 'statistic' of 'tombo text_output browser_files' command

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#184]
Hi:
  When I execute the` tomb text_output browser_files` command on the output file of `level_sample_compare`. I got two files.
The first question is that I compare two sets of direct RNA sequencing samples, and why they produce positive and negative strand statistics.
The second question is whether the second column of the xxxxx.wig file is the statistics for the corresponding location (KS test)? So I still need to convert it to pvalues

**Comment by weir12** [comment]
Hi:
I seem to understand a little about the second question：the second column of the xxxxx.wig file is the `effect size` produced by a hypothesis test(e.g ks-test) for each reference position .
But I did choose `--store-p-value`  opt.So,how should I extract pvalues from binary statistics files?

**Comment by marcus1487** [comment]
To answer your first question, the negative strand file is created by default. If there are entries in this file, this indicates that reads mapped to the negative strand. There are a vast number of reasons that this may occur, but these are primarily considered upstream from tombo. To test this you could map these RNA reads using minimap2 and your reference file and you should see mappings to the reverse strand as found in tombo. Tombo uses these mappings as the starting point.

Is the `--store-p-value` option is specified then the negative log p-values are output (not the p-values). I have added a note to the docs to clarify this (22a3105).
