### ISSUE TITLE
Format of fastq for preprocessing

### ISSUE THREAD

**Issue by ardakdemir** [nanoporetech/tombo#186]
Hi,

What should be the fastq file format in order to preprocess raw reads with a single fastq file containing names and basecall for all reads. 
In my case I have 2000 fast5 files each containing raw signals under Raw/signal_id
I also have a single .fastq file in the following format:
signal_id1
ATTAGAGAG......
+
+-=-=321434.....
signal_id2
ATTAGAGAG......
+
+-=-=321434..... 

I get the following error:

[02:16:55] Preparing reads and extracting read identifiers.
  0%|          | 0/2000 [00:00<?, ?it/s]****** WARNING ****** Basecalls exsit in specified slot for some reads. Set --overwrite option to overwrite these basecalls.
100%|##########| 2000/2000 [00:00<00:00, 2799.85it/s]
[02:16:56] Annotating FAST5s with sequence from FASTQs.
******************** WARNING ********************
        Successfully parsed 0 FASTQ records from ecoli_fixed.fastq before encountering an invalid record. The rest of this file will not be processed.
0it [00:00, ?it/s]
[02:16:56] Added sequences to a total of 0 reads.

**Comment by marcus1487** [comment]
FASTQ format requires the `signal_id` lines to begin with an `@` symbol. This is most likely the reason for this error.
