### ISSUE TITLE
RNA and resquiggle command does not map data

### ISSUE THREAD

**Issue by joachimwolff** [nanoporetech/tombo#189]
Hi,

I am new to Nanopore RNA data and try to get tombo running. However, I have some difficulties.

I am using data from FLO-MIn106 and SQK-RNA002, and was able to convert the fast5 files via multi_to_single_fast5, basecall it with guppy and run `tombo preprocess annotate_raw_with_fastqs`. Now I want to run resquiggle command, but I always get: 

```
tombo resquiggle fast5_new mm10_mRNA.fa --processes 4 --num-most-common-errors 5
[17:14:50] Loading minimap2 reference.
[17:17:42] Getting file list.
[17:17:43] Loading default canonical ***** RNA ***** model.
[17:17:46] Re-squiggling reads (raw signal to genomic sequence alignment).
5 most common unsuccessful read types (approx. %):
   100.0% (  12000 reads) : Tombo data exists in [--corrected-group] and [--overwrite] is not set           
     -----
     -----
     -----
     -----
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12000/12000 [00:00<00:00, 30120675.04it/s]
[17:19:09] Final unsuccessful reads summary (100.0% reads unsuccessfully processed; 12000 total reads):
   100.0% (  12000 reads) : Tombo data exists in [--corrected-group] and [--overwrite] is not set           
[17:19:10] Saving Tombo reads index to file.

```

I think `100.0% reads unsuccessfully processed` is not a desired result. I found [this](https://github.com/nanoporetech/tombo/issues/163) issue with similar problems. 

So I tried what you suggested there, run minimap directly with `minimap2 -ax map-ont mm10_mRNA.fa fastq/FAK60274_34ffe8c64dd158d34c69da2bad8e34ff03b368f7_0.fastq > reads.sam` 

and resulted in (first few lines):
```
@SQ     SN:mm10_all_mrna_BC079624       LN:4582
@SQ     SN:mm10_all_mrna_AK043954       LN:3625
@SQ     SN:mm10_all_mrna_AK134532       LN:2839
@SQ     SN:mm10_all_mrna_BC026602       LN:2496
@SQ     SN:mm10_all_mrna_AK134709       LN:2842
@SQ     SN:mm10_all_mrna_AK045729       LN:2969
@SQ     SN:mm10_all_mrna_AK038774       LN:1991
@SQ     SN:mm10_all_mrna_AK134553       LN:2202
@SQ     SN:mm10_all_mrna_KC881107       LN:1062
@SQ     SN:mm10_all_mrna_AJ555877       LN:981
@SQ     SN:mm10_all_mrna_U05671 LN:1288
@SQ     SN:mm10_all_mrna_AK145751       LN:1943
@SQ     SN:mm10_all_mrna_AK083241       LN:4510
@SQ     SN:mm10_all_mrna_AK080034       LN:3701
@SQ     SN:mm10_all_mrna_AK038698       LN:4055
@SQ     SN:mm10_all_mrna_AF367759       LN:2767
@SQ     SN:mm10_all_mrna_AK016927       LN:1106
@SQ     SN:mm10_all_mrna_BC160286       LN:1553
@SQ     SN:mm10_all_mrna_AK044248       LN:2952
@SQ     SN:mm10_all_mrna_BC062105       LN:2624
@SQ     SN:mm10_all_mrna_BC032251       LN:3654
@SQ     SN:mm10_all_mrna_BC099951       LN:5446
@SQ     SN:mm10_all_mrna_BC079670       LN:4344
@SQ     SN:mm10_all_mrna_AK081421       LN:2646
@SQ     SN:mm10_all_mrna_AY168406       LN:4569
@SQ     SN:mm10_all_mrna_LF303037       LN:45
@SQ     SN:mm10_all_mrna_AK044160       LN:4568
@SQ     SN:mm10_all_mrna_AK153970       LN:1933
@SQ     SN:mm10_all_mrna_D13545 LN:1937
@SQ     SN:mm10_all_mrna_AK168246       LN:1965
@SQ     SN:mm10_all_mrna_D17385 LN:1916
@SQ     SN:mm10_all_mrna_BC019500       LN:1932
```

Does this look correct? I am not that sure about my transcriptome file, I also used a gtf, but it gave me the same result. 

Do you have any suggestions on how to get it run? Thanks a lot in advance.

Best,

Joachim

**Comment by marcus1487** [comment]
The result indicates that there is information present in the FAST5 files in the default location (specified via the `--corrected-group` slot). In order to overwrite this information you must specify the `--overwrite` flag, which will overwrite this slot with the new results.

**Comment by joachimwolff** [comment]
Hi,

with `--overwrite` it seems to work. Thanks for the help. Anyhow, I am a bit confused, I followed your instructions on readthedocs. Can you explain me if this slot is always there and needs to be overwritten or what could be the cause of this? I had with `tombo preprocess annotate_raw_with_fastqs` also the issue that I had to set `--overwrite`, but this is not written in the documentation. Did something in the fast5 files changed that was not present at the time the documentation was written?

Thanks a lot,

Joachim

**Comment by marcus1487** [comment]
The documentation is assuming a starting point of raw (un-basecalled) FAST5s. If basecalls are already present in the FAST5 files then the preprocessing step is not necessary, but may be used to annotate with a new set of basecalls if required.

The resquiggle slot is generally reserved for tombo processing (though it could be accessed/written to by other third party tools). It is likely that your starting FAST5 files had already been processed with the resquiggle command before you began processing. Thus those analyses needed to be overwritten at the time of this command. 

I hope this helps and best of luck in your research!

**Comment by joachimwolff** [comment]
Thanks for your explanation.
