### ISSUE TITLE
How to get a reference sequence mapped by a read.

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#191]
Hi:
  When I already have a UUID of read(well re-squiggled), how do I get the Specified reference sequence mapped by this read?
  To be frank,I have found `mapped_chrom` `mapped_end` `mapped_start` attributes in the fast5 file corresponding to UUID.Maybe using `h5py` and `samtools faidx` can solve this problem.
  I just want to know if there is a ready-made API of tombo that can solve the problem more quickly and conveniently.
Thanks

**Comment by marcus1487** [comment]
The read-centric reference sequence is stored in the tombo events table. You can see an example of this [here in the code](https://github.com/nanoporetech/tombo/blob/master/tombo/tombo_helper.py#L2202). But it’s probably easier to just use that function call (‘get_all_read_data’). In terms of extracting the correct r_data object it’s probably best to load all reads and search for the read id of interest. If you’re searching for many reads from an index it probably makes sense to store the r_data objects in a dictionary by read id. Hopefully this helps point you in the right direction.

**Comment by weir12** [comment]
Sorry, I still don't quite understand. Could you give an example of it?
