### ISSUE TITLE
How to get the UUID corresponding to the signal value？

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#192]
Hi:
  By running the following code, I can extract normalized raw signal assigned to each genomic base from each read in a region
```
reg_data = tombo_helper.intervalData(chrm='chr20', start=10000, end=10100, strand='+')
reads_index = tombo_helper.TomboReads(['test_data/native_reads',])
reg_base_levels = reg_data.add_reads(reads_index).get_base_levels(num_reads=10)
```
But the return value seems to lack the signal source information.
```
>>> reg_base_levels
array([[1.99489315, 2.0799633 , 2.01628663, ..., 2.11234041, 2.16805864,
        2.24205731]])
```
I want to know the read ID corresponding to these signal values.
Just like `sample_per_read_stats.get_region_per_read_stats( reg_data)`  can get the mapping of fraction and read ID in a position.
thanks

**Comment by marcus1487** [comment]
There is not a built in way to extract these read ids, but a relatively simple modification could be made to the `get_base_levels` function in order to have these uuids returned. When iterating over the reads [here](https://github.com/nanoporetech/tombo/blob/master/tombo/tombo_helper.py#L2024), the `r_data` objects have are `ReadData` objects ([docs here](https://nanoporetech.github.io/tombo/tombo.html#tombo.tombo_helper.readData)). Thus the `r_data.read_id` holds the uuids for these reads.

**Comment by weir12** [comment]
Thanks.this method is simple but effective.

**Comment by weir12** [comment]
Sorry to open again，Getting` read_id` is very fast, but getting the `fn` attribute is very slow in this way.I found that CPU usage is very low, indicating that this is not a computationally intensive task, so is this process slow because of IO bottlenecks?Is there a faster way to get the path to the reads file?

**Comment by marcus1487** [comment]
The filename (`fn` attribute) is stored in the exact same way as the `read_id` as a string stored in memory, so this should not cause any IO bottlenecks. Are there any other changes to the way in which you ran the commands for `fn` vs `read_id` extraction?

**Comment by weir12** [comment]
These are the code I changed, the bold is the new code, there is no cut code
```        
        reg_events = []
        **reg_fn=[]**
        for r_data in self.reads:
            if self.strand is not None and r_data.strand != self.strand:
                continue
            r_means = get_read_reg_events(r_data)
            if r_means is None: continue
            reg_events.append(r_means)
            **reg_fn.append(r_data.fn)**
            if num_reads is not None and len(reg_events) >= num_reads:
                break

        if read_rows:
            return np.row_stack(reg_events),**np.row_stack(reg_fn)**
        return np.column_stack(reg_events),**np.column_stack(reg_fn)**
```

**Comment by marcus1487** [comment]
My guess is that this has to do with converting the variable length strings into numpy arrays. Could you just return the list of file names (or read ids) instead of calling np.stack.

**Comment by weir12** [comment]
Thanks,your guess is correct.
