### ISSUE TITLE
Failed to load reference genome FASTA for mapping.

### ISSUE THREAD

**Issue by pabloacera** [nanoporetech/tombo#193]
Hi!
I am trying to use tombo for resquiggle reads from e.coli pUC19 plasmid to the plasmid itself.

the fast5 files have already the basecalls, so I am typing:

`tombo resquiggle /mnt/14c9d9e1-29e1-484c-87bf-7b65e4edadb6/nanopore/pUC19/processed/test_segmenter/   /mnt/14c9d9e1-29e1-484c-87bf-7b65e4edadb6/nanopore/pUC19/processed/test_segmenter/pUC19.fasta --processes 4 --num-most-common-errors 5
[12:11:35] Loading minimap2 reference.
******************** ERROR ********************
	Failed to load reference genome FASTA for mapping.` 

This is the error I am getting. 
Below are the first lines from the fasta file from pUC19, do you see anything unusual? Does the fasta has to has certain format (lowercase, uppercase...) 

>pUC19 [length=2686] [version=09-MAY-2008] [topology=circular] Cloning vector pUC19, complete sequence.
TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGACGGTCACAGCTTGTCTGTAAGCGGAT
GCCGGGAGCAGACAAGCCCGTCAGGGCGCGTCAGCGGGTGTTGGCGGGTGTCGGGGCTGGCTTAACTATGCGGCATCAGA

Thank you very much in advance for your time and help!
Pablo.

**Comment by pabloacera** [comment]
Sorry, some spaces in the reference genome file caused the problem!
Thanks anyways

**Comment by AnunayS** [comment]
I am also facing the same issue.
Did it work by removing the spaces from the fasta file.
