### ISSUE TITLE
confusing error message tombo annotate_raw_with_fastqs

### ISSUE THREAD

**Issue by wdecoster** [nanoporetech/tombo#194]
Hi,

I noticed a confusing error message:

Upon running `tombo resquiggle f5dir ref.fa` I get:

```
        Reads do not to contain basecalls. Check --basecall-group option if basecalls are stored in non-standard location or use `tombo annotate_raw_with_fastqs` to add basecalls from FASTQ files to raw FAST5 files.
```

Okay, sounds reasonable, but it turns out `tombo annotate_raw_with_fastqs` doesn't exist and it should be `tombo preprocess annotate_raw_with_fastqs`... :)

**Comment by wdecoster** [comment]
Slightly related, but it seems `tombo preprocess annotate_raw_with_fastqs` is incompatible with a gzipped fastq file and a multiread fast5.

```****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.                                                      
0it [00:11, ?it/s]                                                                                                                                                               
[14:39:19] Added sequences to a total of 0 reads.
```

While it seems to work for the single read fast5s I still have lying around by chance. I am using the latest tombo version from bioconda (1.5).

**Comment by marcus1487** [comment]
I will push a fix for the error message shortly.

Tombo does not have multi-FAST5 support at the moment. We do not currently have a timeline for adding this feature.

**Comment by marcus1487** [comment]
Ah. This error message is fixed in github, there has not been a release since this fix. Use `pip install git+https://github.com/nanoporetech/tombo/` to install directly from github.

**Comment by wdecoster** [comment]
Thanks for letting me now. But perhaps it would make sense to explicitly test if a fast5 is in multi-read format, and give a more accurate error message there? That would at least save me some confusion the next time I come across this ;-)

**Comment by marcus1487** [comment]
I have pushed a commit with a note about the lack of multi-fast5 support to the function that accesses the raw signal slot. I think this should catch most all workflows where multi-fast5s might be tried, but do let me know if you run into any workflows where you don't get a note in the warning.

**Comment by dariober** [comment]
My 2p on this issue since I'm facing it as well... Once can convert multi-fast5 to single-fast5 using the program [multi_to_single_fast5](https://github.com/nanoporetech/ont_fast5_api#multi_to_single_fast5) from the [ont-fast5-api](https://github.com/nanoporetech/ont_fast5_api) package (also available from bioconda).
