### ISSUE TITLE
Resquiggle quality

### ISSUE THREAD

**Issue by pabloacera** [nanoporetech/tombo#196]
Hi!
I was wondering if there is any parameters after the resquiggle that indicate the quality of the resquiggle.. By region or by basepair. Basically indicating how good or bad is the alignment between signal and reference genome.
Thanks a lot in advance for your time and help!
Pablo.

**Comment by marcus1487** [comment]
Using the tombo python api, the readData object has a sig_match_score which is the value for which you are looking. This value is the average z-score for the signal matched to the expected levels. Here is a link to the docs with an example and some more information. https://nanoporetech.github.io/tombo/tombo.html#module-tombo.tombo_helper

**Comment by pabloacera** [comment]
Alright, very useful, thanks a lot!
