### ISSUE TITLE
Question about class attribute of tombo_helper.readData

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#197]
Hi:
  I have always had a small question：What are the meanings of `start` and `end` in the class `tombo_helper.readData` ?I try to get the alignment information by the path of the known fast5 files.When the class is instantiated into an object,How do I need to determine these two attributes？

**Comment by marcus1487** [comment]
These are the start and end reference mapping coordinates. Find more details about the `ReadData` class [here in the docs](https://nanoporetech.github.io/tombo/tombo.html#module-tombo.tombo_helper).

**Comment by weir12** [comment]
Sorry,maybe I wasn't clear enough.If I only know the directory of a fast5 file, how can I determine these two parameters（start & end）?In other word,I want to get the  start and end reference mapping coordinates of this read by loading that fast5 file.

**Comment by marcus1487** [comment]
The `readData` objects are loaded from the tombo index file (hidden file alongside the fast5s directory). This file is what is actually loaded when you run the `tombo_helper.TomboReads` command from the API (not the individual fast5s). The data within the fast5s is only read in when the hidden index file is not found or when more detailed information is needed from the fast5s (e.g. raw signal or event levels data). With this loaded index data, a read of interest could be selected using the `read_id` attribute of the `readData` objects.

You can access the mapping information directly from the `resquiggle` processed fast5s via the `Alignment` group (found within the tombo specific slot; default `/Analysis/RawGenomeCorrected_000`). Within the group the `start` and `end` attributes are the mapping coordinates. see more details [here in the docs](https://nanoporetech.github.io/tombo/resquiggle.html#tombo-fast5-format).

Let me know if further clarification would help with your issue.

**Comment by weir12** [comment]
Thanks,I got them.
