### ISSUE TITLE
Detecting differential dam methylation in E. coli

### ISSUE THREAD

**Issue by behrimg** [nanoporetech/tombo#198]
We are attempting to detect gains and losses of dam methylation in some experimentally evolved lines of E. coli. To detect these sites we made sure to also sequence and analyze three copies of our progenitor strain to see how repeatable the dam calls in tombo are. 

We found many sites in our progenator samples where Tombo called a mA on the plus strand but not on the minus strand (These sites do not alway agree across the three replicates and often one of the strands reports a high dampened fraction of methylation despite the absence of methylation on the other).

I find this confusing because shortly after replication Dam is supposed to ensure both strands of GATC are methylated..as such if a mA is found on the + strand at position 600208 (for example) a mA should also be found on the - strand at position 600209. Is there a way to determine which of these calls are likely to be false positives/negatives and filter them accordingly?

**Comment by marcus1487** [comment]
In order to investigate this further I would suggest having a look at the `tombo plot per_read` command. This should help to determine if there is at least some evidence for a modification (and it just didn't cross the significance threshold) or if there really does appear to be hemi-methylation at these sites.

Having replicates is certainly a very helpful in order to filter out some of the false positive/negative sites here. Hopefully this replication scheme can help to solve some of these issues.

**Comment by behrimg** [comment]
So here are the tombo plot per_read files for two genomic locations where we have disagreement. 
Each PDF has the three replicates of the progenitor strain, so WT1-3_49054_F.pdf is the forward strand at position 49054 with page 1 being replicate 1 and page 2 being replicate 2. WT1-3_49055_R is the reverse strand for that site. 
Our Fraction information from the fasta files says that the methylated fraction for 49054_F is: WT1, 0.95; WT2, 0.96; WT3, 0.96. 
While the methylated fraction for 49055_R is WT1,0.73; WT2, no call; WT3, no call.

[WT1-3_49054_F.pdf](https://github.com/nanoporetech/tombo/files/3454026/WT1-3_49054_F.pdf)
[WT1-3_49055_R.pdf](https://github.com/nanoporetech/tombo/files/3454027/WT1-3_49055_R.pdf)

. 

Im also getting plots to share of another site

**Comment by marcus1487** [comment]
Something is certainly off with those plots. I haven't seen this behavior before from this plotting function. Do you have up-to-date R, ggplot2 and rpy2 installations? 

Assuming that these plots do depict the correct genomic locations it does appear that the forward strand shows much stronger per-read calls than the reverse for methylation here across all 3 replicates (more and darker red indicates methylation and more and darker grey indicates canonical bases). Note that the no call sites from the 2 negative strand samples indicate that no reads can confidently make a call at this site. In other words, this does not mean that there is no methylation, but that tombo cannot determine confidently one way or another if there is methylation. Thus it is likely that there is methylation on the negative strand here and it just cannot be detected in those reads. Sites with called methylation on one strand and called canonical bases on the other would be more compelling evidence for hemi-methylation. 

As another approach, the detection of dam and dcm is also possible with the newly released [megalodon tool](https://github.com/nanoporetech/megalodon). Given the completely different approach to methylation detection, it would be interesting to see if this method identifies hemi-methylation at this and other sites from your samples.
