### ISSUE TITLE
A question about the variable USE_START_CLIP_BASES

### ISSUE THREAD

**Issue by omegahh** [nanoporetech/tombo#199]
USE_START_CLIP_BASES = False in resquiggle.py. But I find that sequences should be reversed if it's true.

Like this:
<img width="515" alt="屏幕快照 2019-07-30 10 41 07" src="https://user-images.githubusercontent.com/5026687/62096593-bc08dc00-b2b6-11e9-9308-12a6b4c71a2d.png">

<img width="648" alt="屏幕快照 2019-07-30 10 41 52" src="https://user-images.githubusercontent.com/5026687/62096594-bca17280-b2b6-11e9-8574-594be362abd1.png">

I am kind of confused with this variable. What does it mean? Why we should flip the sequence when it is True? Please help me. Thank you very much!

**Comment by marcus1487** [comment]
This parameter is defined at the top of that module [here](https://github.com/nanoporetech/tombo/blob/1.5/tombo/resquiggle.py#L75). The comment there notes its function (`use (mapping) clipped bases at the start of read to identify start position`). This was an experimental feature that did not seem to help the resquiggle process, and so it has been set to `False` by default to disable this feature.
