### ISSUE TITLE
Tombo standard models

### ISSUE THREAD

**Issue by rasto2211** [nanoporetech/tombo#2]
Is it safe to use [these models](https://github.com/nanoporetech/kmer_models) as tombo standard models or should I rather run `tombo estimate_kmer_reference`?

What do the flags `upstream-bases` and `downstream-bases` mean in `estimate_kmer_reference`?

**Comment by marcus1487** [comment]
Those models are separate from tombo models and so would not work in the tombo framework. By default tombo runs with these models https://github.com/nanoporetech/tombo/tree/master/tombo/tombo_models. These models are used for re-squiggling and testing within tombo. 

As for estimate_tombo_reference, this is certainly possible, but as mentioned above is not necessary in most cases. The upstream and downstream bases arguments define the k-mer used in the tombo reference. There is one dominant base which predominantly effects the k-mer level. This can be visualized with the plot_kmer command. Thus these arguments define the number of positions up and downstream of the dominant position to be included in the modeled kmer.

**Comment by rasto2211** [comment]
For what flow cells are the models that you mentioned above suitable?

**Comment by marcus1487** [comment]
The DNA and RNA models should be suitable for R9.4 and R9.5 flow cells. An R9 flow cell is not currently available.

**Comment by rasto2211** [comment]
Are you sure that the same model works for R9.4 450 bps and also for R9.4 250 bps? I think that the speed matters.

**Comment by marcus1487** [comment]
Yes certainly the speed does matter. The 250 bp/sec should be just for the (no longer available) 2D chemistry on the R9.4 flowcell though. 1D libraries on R9.4 should be running at 450 bp/sec. I will add a note to the readme giving some detail for the applicable flowcell and chemistries.

**Comment by rasto2211** [comment]
Thanks.

**Comment by marcus1487** [comment]
Added a note on the tombo models to the README in 03d39b69d761e5a6b73ff1783236a91da0d7ed51

**Comment by rasto2211** [comment]
Could you please give me some time estimate when the models for R9.4 250 bps and R9 could be available?

**Comment by marcus1487** [comment]
There is no plans at the moment to add these models. I would suggest creating one yourself with a PCR'ed sample from a known genome (with enough 6-mer diversity) using the `estimate_kmer_reference` command if this is urgent for your research.
