### ISSUE TITLE
is there any test data ?

### ISSUE THREAD

**Issue by Huanle** [nanoporetech/tombo#20]
Is there any test data available.
I'd love to try tombo.
Thanks.
Huanle

**Comment by marcus1487** [comment]
There is not a supported, distributed test data set at this time. Any real example test data set would not be included in the code base as the size of even a modest number of reads is much larger than the size of the code base. At this time there is not a plan to provide any test data. 

There are a set of test commands included with the code base at [`tombo/tests/shell_tests.sh`](https://github.com/nanoporetech/tombo/blob/master/tombo/tests/shell_tests.sh) that should help with some example commands and workflows. I hope this helps!

**Comment by Huanle** [comment]
thanks Marcus.
