### ISSUE TITLE
Issues with estimating m6A

### ISSUE THREAD

**Issue by Sebidoo964** [nanoporetech/tombo#202]
Hi! I am having some issues with analysing the epigenetics of my sample. So what I want to achieve is being able to estimate the amount of methylated A (m6A) in my sample and then finding out a percentage compared to the control fast5 /genome fasta file, in order to know how well the enzyme used works. I use tombo and the detect_modifications command, which runs without issues. The issue I am facing is that the plots are not very clear, in the sense that I can't make the estimation I am looking for, as well as I can't seem to find a good explanation to what I'm actually looking at. Should I use the text_output command, if so which? is there a webpage that explains what I want to achieve, which I haven't found yet?

**Comment by marcus1487** [comment]
The tombo plots are described in more detail on the [tombo documentation page here](https://nanoporetech.github.io/tombo/plotting.html#). It does sound as though the `text_output` commands would be more useful for this task. Those are also explained on the tombo documentation page. If there are specific issues not addressed there, please post them here.

**Comment by Sebidoo964** [comment]
I have already looked at this site, but can't find any good explanation of where i should be detecting the modifications. I see a bunch of pretty plots but nothing that describes in detail which of the bases are modified. Is it just the one that the motif is centered around or are there more in the same motif...? In most of the outputs I have to define how many unique locations and bases I want to see, but i don't know this since i don't know how many there are. if I define more locations than there are, will I get some outputs that are not methylated or will it just output the methylated ones (even though they are fewer than my imputed request). I would really appreciate it if you could suggest a way of achieving the goal, explained in the first post, such as specific commands of the different tombo tasks.

**Comment by marcus1487** [comment]
It seems that the best option to solve the main goal ("estimate the amount of methylated A") would be to produce the `tombo text_output browser_files` with the `--file-types dampened_fraction` option. As described [here in the docs](https://nanoporetech.github.io/tombo/text_output.html#tombo-text-output-browser-files), this will produce the estimated fraction of modified bases at each position computed from the `detect_modifications` step. These results could then be compared between the control and treated samples.

As for the plots, there are a lot of different plot types that tombo can produce. The documentation has attempted to describe these plots in some detail, but if you have a question concerning a specific aspect of a specific plot, I would be happy to explain this in more detail. To be honest, the plotting functions are mostly about producing pretty plots and should likely not be used for further analysis. The plotting functions allow users to inspect how the raw signal (or other analysis aspects) resulting in the produced results "by eye".

I hope this helps clear up the intended use of the tombo commands.
