### ISSUE TITLE
Q on per-read p-values between IVT and sample + ROC testing

### ISSUE THREAD

**Issue by OlivierZablo** [nanoporetech/tombo#206]
Hi,

Working with direct RNA data. I ran modification detection on IVT (PCR data) and sample of interest.
The per-read stats file was extracted into dataframes such that I have p-values for each genomic position, per read, in CSV format. At the genome-wide level (dampened fraction plot), there is a clear difference between IVT and sample (good!).
Q1: is there a way to plot the roc curves between IVT and sample WITHOUT motif description argument in tombo? I don't have motifs, I just want to see how they compare at every genomic position.
Q2: I'd like to cluster the 'sample' reads according to their modified base profiles; but the p-value range per read across genomic positions is so wide that I'm unsure what to trust. Anything below p=0.05? If so, I fear this is not accurate since I do see 'significant' p-values in the per-read IVT data too (albeit at much lower frequencies, and the overall pileup end up less than 0.2 using dampened fraction outputs).
Q3: related to Q2. How are individual p-value positions per read computed? Sorry if I missed this in the docs.

Any help would be greatly appreciated! Thanks in advance.

**Comment by marcus1487** [comment]
Q1) The `tombo plot roc` command has `--modified-locations` and `--unmodified-locations` arguments. These can be used to specify the ground truth modified locations manually. You can see all options for this (or any) command by adding the `-h` flag (e.g. `tombo plot roc -h`).

Q2) For clustering the modification profiles the `tombo plot per_read` performs this clustering step. In practice the clustering seems most useful for the `tombo detect_modifications alternative_model` method. The other `detect_modification` methods generally produce per-read results with a bit too much noise for clustering.

Q3) Each detect_modifications subcommand computes p-values in a different manner. See high-level description of the methods [here in the docs](https://nanoporetech.github.io/tombo/modified_base_detection.html). Please post if there is a question for a specific method.

**Comment by OlivierZablo** [comment]
Hi, thank you for the clarifications!
