### ISSUE TITLE
NameError: name '_R_DF' is not defined

### ISSUE THREAD

**Issue by adbailey4** [nanoporetech/tombo#208]
Looks like there may be a small error that crops up when you make a call to a plotting function which uses the `_R_DF` object defined on line [47](https://github.com/nanoporetech/tombo/blob/master/tombo/_plot_commands.py#L47) of `_plot_commands.py`. I was trying to plot a genome location sample comparison using this command `tombo plot genome_locations  --overplot-type Density --genome-locations ecoli_MRE600:527:+ --control-fast5-basedirs /path/to/fast5/0 --fast5-basedirs /path/to/fast5/2` and got the following error. 

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo', 'console_scripts', 'tombo')()
  File "/home/ubuntu/tombo/tombo/__main__.py", line 279, in main
    _plot_commands.plot_main(args)
  File "/home/ubuntu/tombo/tombo/_plot_commands.py", line 2329, in plot_main
    plot_genome_locations(*base_args, **kwargs)
  File "/home/ubuntu/tombo/tombo/_plot_commands.py", line 1766, in plot_genome_locations
    overplot_thresh, overplot_type, pdf_fn)
  File "/home/ubuntu/tombo/tombo/_plot_commands.py", line 1411, in plot_two_samples
    print(_R_DF, "This exists")
NameError: name '_R_DF' is not defined
```

I went ahead and looked into the source and it looks like there is a silent try except block on lines 44-51 of `_plot_commands.py`.

```
# try global rpy2 imports
try:
    from rpy2 import robjects as r
    from rpy2.robjects.packages import importr
    _R_DF = r.DataFrame(())
except:
    # pass here and print detailed error when main functions are actually called
    # in  to give specific error message
    pass
```

So, I tested it out using rpy2 version 3.1.0 and it looks like all you need to do is change line 47 from `    _R_DF = r.DataFrame(())` to `    _R_DF = r.DataFrame({})` and the plotting works. 

It may just be a rpy2 version issue but I didn't dive too deep into it. Based on [this](http://rpy.sourceforge.net/rpy2/doc-2.1/html/robjects.html) documentation it looks like there would be an issue with the initialization of the `robjects.DataFrame` object since version 2.1.

**Comment by marcus1487** [comment]
I am able to successfully load an R data.frame with the above command for rpy2 version 2.9, so this appears to be a change to the rpy2 API (likely at the version 3 upgrade). I may just add a requirements restriction to be `rpy2<3` (in order to avoid more future API changes), though it does appear that the dictionary initialization may make sense to add as well.

For now, a downgrade to rpy2<=2.9 should suffice.

**Comment by adbailey4** [comment]
Yep, it looks like downgrading to 2.9 works. Initialization with a dictionary works for both versions so I agree it probably make sense to make it a dictionary initialization at some point.
