### ISSUE TITLE
Error estimating alternative reference

### ISSUE THREAD

**Issue by clarepacini** [nanoporetech/tombo#21]
Hi,

I have been trying to estimate an alternative model for some methylation data sets that we have. However, I get an error when it tries to output the density:

Executing command:
==================
/mnt/home1/gurdon/cep46/.local/bin/tombo estimate_alt_reference --fast5-basedirs /mnt/home1/gurdon/cep46/MinionSeq/basecalls/FAH55505_MethAmp/workspace/pass/barcode04 --control-fast5-basedirs /mnt/home1/gurdon/cep46/MinionSeq/basecalls/Allamp/ --alternate-model-base A --alternate-model-filename m6A_altreference_high --alternate-model-name m6A --save-density-basename altmodel_density 

/mnt/home1/gurdon/cep46/.local/bin/tombo estimate_alt_reference --fast5-basedirs /mnt/home1/gurdon/cep46/MinionSeq/basecalls/FAH55505_MethAmp/workspace/pass/barcode04 --control-fast5-basedirs /mnt/home1/gurdon/cep46/MinionSeq/basecalls/Allamp/ --alternate-model-base A --alternate-model-filename m6A_altreference_high --alternate-model-name m6A --save-density-basename altmodel_density 

Parsing tombo index file(s).
Parsing tombo index file(s).
WARNING: Index file does not exist for one or more directories. For optimal performance, either re-run re-squiggle without --skip-index flag or point to top level fast5 directory of recursive directories.
Parsing standard model file
Using default canonical ***** DNA ***** model.
Parsing base levels from alternative reads
	1000 reads processed. Current minimum k-mer observations: 62 towards goal of 1000
	2000 reads processed. Current minimum k-mer observations: 134 towards goal of 1000
	3000 reads processed. Current minimum k-mer observations: 203 towards goal of 1000
	4000 reads processed. Current minimum k-mer observations: 254 towards goal of 1000
	5000 reads processed. Current minimum k-mer observations: 318 towards goal of 1000
	6000 reads processed. Current minimum k-mer observations: 379 towards goal of 1000
	7000 reads processed. Current minimum k-mer observations: 443 towards goal of 1000
	8000 reads processed. Current minimum k-mer observations: 491 towards goal of 1000
	9000 reads processed. Current minimum k-mer observations: 544 towards goal of 1000
	10000 reads processed. Current minimum k-mer observations: 602 towards goal of 1000
	11000 reads processed. Current minimum k-mer observations: 672 towards goal of 1000
	12000 reads processed. Current minimum k-mer observations: 732 towards goal of 1000
	13000 reads processed. Current minimum k-mer observations: 800 towards goal of 1000
	14000 reads processed. Current minimum k-mer observations: 857 towards goal of 1000
	15000 reads processed. Current minimum k-mer observations: 908 towards goal of 1000
	16000 reads processed. Current minimum k-mer observations: 969 towards goal of 1000
Fitting kernel densities for k-mer levels
Traceback (most recent call last):
  File "/mnt/home1/gurdon/cep46/.local/bin/tombo", line 11, in <module>
    sys.exit(main())
  File "/mnt/home1/gurdon/cep46/.local/lib/python2.7/site-packages/tombo/__main__.py", line 152, in main
    tombo_stats.est_alt_ref_main(args)
  File "/mnt/home1/gurdon/cep46/.local/lib/python2.7/site-packages/tombo/tombo_stats.py", line 1647, in est_alt_ref_main
    args.control_density_filename)
  File "/mnt/home1/gurdon/cep46/.local/lib/python2.7/site-packages/tombo/tombo_stats.py", line 799, in estimate_alt_model
    kernel_dens_bw, save_x)
  File "/mnt/home1/gurdon/cep46/.local/lib/python2.7/site-packages/tombo/tombo_stats.py", line 661, in estimate_kmer_densities
    density_basename, save_x, kernel_dens_bw, 'alternate')
  File "/mnt/home1/gurdon/cep46/.local/lib/python2.7/site-packages/tombo/tombo_stats.py", line 638, in est_kernel_density
    kmer_dens, save_x)
TypeError: write_kmer_densities_file() takes exactly 1 argument (3 given)

Thanks,
Clare

**Comment by marcus1487** [comment]
Hi Clare,

Sorry you have hit this bug. I had identified this within the dev branch (which will hopefully be pushed here shortly). In the meantime I have added a hotfix for this to the github repo. If you re-install Tombo from github, this issue should be resolved. Thanks for the bug report!
