### ISSUE TITLE
Exploring Fast5 Formats: 'mapped_start'

### ISSUE THREAD

**Issue by cednotsed** [nanoporetech/tombo#211]
Hi Marcus,

I was comparing resquiggled fast5s from Nanoraw and Tombo and found that the `Alignment` attributes for Nanoraw do not contain 'mapped_end'.

Is the 'mapped_start' for Nanoraw and for Tombo equivalent?

**Comment by marcus1487** [comment]
Yes. This attribute should be the 0-based mapping start coordinate in both repositories. The `mapped_end` attribute was added in tombo in order to increase the loading speed for a tombo run as obtaining the `mapped_end` in nanoraw required the loading of the events table from disk.
