### ISSUE TITLE
Question about the alphabet of the transcriptome

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#215]
Hi:
In RNA processing,Is the transcriptome file composed of `ACGU` or `ACGT`?The corresponding cDNA file of the species downloaded from the database is `ACGT`.However, the `fastq` group in the fast5 file is `ACGU`.I suddenly had this confusion:)

**Comment by marcus1487** [comment]
Encoding read basecalled sequence and/or transcriptome references with `T` or `U` is acceptable for tombo. Both inputs are converted to `T` bases immediately when extracted for tombo processing. So both versions will use a `T` base within the tombo framework in the end.

**Comment by weir12** [comment]
Thanks,I fully understand that.
