### ISSUE TITLE
Merge forward and reverse strand methylation levels

### ISSUE THREAD

**Issue by pterzian** [nanoporetech/tombo#216]
Hi Marcus,

In a CpG context, it can be useful to merge forward and reverse methylation levels for each CpG sites in order to increase signal. Is there is such feature in Tombo ?

If not do you an idea from where I could start ? (I was hoping not to have to write the per-reads stats files...)

I wanted to use the bedgraphs depth levels with the methylation fraction in the wigs to recalculate the counts but it seems this way would not be clean at all... 

thx,
Paul

**Comment by marcus1487** [comment]
There is not a specific tool to merge forward and reverse methylation results within tombo. I do think that merging results from the bedgraph files is a reasonable solution. These files contain the minimal information required to compute the final strand-merged fraction of methylation (e.g. without writing the per-read results files). Please post if there are any specific issues that make working from the bedgraph files difficult.

**Comment by pterzian** [comment]
Hi Marcus, 

So this is how I recalculated the original counts : 
```
count_methylated   <- round(depth * fraction)
count_unmethylated <- round(depth - count_methylated)
depth2 <- count_methylated + count_unmethylated
```
I was a bit scared at first not to find the original depth, but rounding gave me back the original depth so I guess it works fine that way.

**Comment by marcus1487** [comment]
It would be a bit safer to use something like `np.around` instead of `round` since the fraction rounding may force the count values to be slightly above or below the correct count value. Otherwise, glad to hear that this method works for your purposes.
