### ISSUE TITLE
TOMBO level-sample-compare normalization

### ISSUE THREAD

**Issue by ceslobfer** [nanoporetech/tombo#218]
We are using the TOMBO software with level-sample-compare method with RNA-direct-seq samples with two different conditions. We obtain as a result an assigned pvalue for each position of the transcripts. This value, as I understand in the documentation, represents the reliability of presenting a variation in the level of modification in that position with respect to the same position in the alternative sample.

 My question is, does that value take into account the coverage of the position? 

For example:

POSITION                       COVERAGE

sample1_control_transcriptA_position20          80

sample2_treatment_transcriptB_position20      150

Where 80 and 150 are the positions of align reads for position 20 of that transcript.

 Does the TOMBO level-sample-compare method take into account this difference in aligned readings for different samples?

**Comment by marcus1487** [comment]
The level_sample_compare method applies one of three statistical tests: ks-test (default), u-test and t-test. Each of these tests are designed to compare groups of different sizes. Though the level of coverage certainly effects the power of each test. This is why the default minimum coverage for this method is set to 50 in order to minimize the effect of different coverages across a genome/transcriptome.

**Comment by ceslobfer** [comment]
My question is: If I have a differential expression between two samples because of their experimental conditions for a transcript, would that give a differential value of modification in the positions? For example. I have the following positions with a value ks> = 0.98:

transcript_id ks_index position coverageS1 coverageS2
pp_380150 (0.98449139, 259, 7375, 1700)
pp_78626 (0.98009763, 376, 2964, 1200)
pp_365391 (0.9807845, 766, 4010, 1572)
pp_365391 (0.98088993, 767, 4011, 1574)
pp_366125 (0.98047228, 1257, 3602, 1620)
pp_366125 (0.98350161, 1303, 3664, 1659)
pp_366125 (0.98233962, 1853, 4498, 2371)
pp_366125 (0.98030793, 1854, 4496, 2370)

For all these transcripts I also have an associated differential expression. My question is whether that differential expression can affect the prediction of the differential modification by level_sample_compare.

**Comment by marcus1487** [comment]
There should not be a specific reason that differential expression would cause sites to be identified as modified. These test statistics are unbiased estimates for the difference in the mean/median of the signal level between two samples. 

Lower coverage values will result in estimates with higher variance. This should not be correlated with differential expression, but should be taken into account with large scale analyses.
