### ISSUE TITLE
Some questions about the Variable meaning of the get_r_raw_signal_data plot function

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#220]
Hi
@marcus1487  I'm trying to extract normed current signals for certain intervals(`Not` the mean value  for every base for every read.Output of `.get_base_levels` is more like the `event`)
I wish I could extract signals that have only been normalization(which Contains more information).
I've noticed that the following function maybe could implements my requirement.
https://github.com/nanoporetech/tombo/blob/87e3be186476ba88853f3c861df624513112234c/tombo/_plot_commands.py#L946
But I have some doubt bout `genome_centric` parameter.Is this parameter used to control the direction of the extracted signal?If it's `True`, does the direction of the signal vector submit to 5 '> 3'?
My actual situation are direct RNA data and transcriptome reference.

I look forward to your reply

**Comment by marcus1487** [comment]
Yes this parameter is used to control the direction of the signal returned. If `genome_centric ` is set to `True` reverse (negative) strand signals are flipped from sequencing direction. If this parameter is set to `False` then signal information would be returned in sequencing direction. 

Note that sequencing direction for RNA data is considered as 5' to 3' in tombo as RNA signal is always flipped immediately upon input. See [here](https://github.com/nanoporetech/tombo/blob/87e3be186476ba88853f3c861df624513112234c/tombo/tombo_helper.py#L2108) for this point in the code.

**Comment by weir12** [comment]
Thanks,I've got it all figured out
