### ISSUE TITLE
Tombo resquiggle still cost large memory.

### ISSUE THREAD

**Issue by tangshanshaolu** [nanoporetech/tombo#227]
Hi,
     I've been testing tombo 1.5 and I encountered the large memory problem when I running tombo resquiggle command. I check my python package and I have installed pyfaidx.  The following command is the one I run：
`tombo resquiggle /TJPROJ5/MEPI/Home/shaolu/softwares_test/Tombo/01convert/ONT_3C_lane1/fast5_pass /TJNAS01/CANCER/Gencode/hg38/hg38.fa --processes 4 --num-most-common-errors 5`

The following screenshot is the progrem running detail, memory cost nearly 200G:
![image](https://user-images.githubusercontent.com/32194143/74625520-8dd1e780-5187-11ea-8352-ffd2481fe4cb.png)

 And I'm sure I have installed pyfaidx:

![image](https://user-images.githubusercontent.com/32194143/74625568-b954d200-5187-11ea-846b-666b29e575a2.png)

And log looks have no problem:
![image](https://user-images.githubusercontent.com/32194143/74625644-edc88e00-5187-11ea-8ea8-a2e58769131a.png)

Hope for your reply.

**Comment by marcus1487** [comment]
Tombo is generally able to perform the resquiggle step on large genomes with a relatively small memory footprint (dominated by the reference; ~8GB for hg38). This reference is loaded into a shared memory location. I have seen in the past that some job scheduling software (SGE, UGE, etc) can miscalculate the actual amount of memory used when shared memory is shared across the tombo threads. Could you run this command in a standard shell to observe the memory usage through htop, top or some other mechanism?

**Comment by tangshanshaolu** [comment]
Hi,
      Thank you for you reply! I tested the  resquiggle command on the  standard shell and use top to observe the memory usage.  Following screenshot  is the detail：
![image](https://user-images.githubusercontent.com/32194143/74917733-f678c880-5402-11ea-8dee-a93ce67a8f29.png)
I just run a little time, I tested on landing node so I can't cost large memory.

**Comment by marcus1487** [comment]
The shared memory looks about right for the hg38 genome. Note that most all of the memory usage is shared. Can you log onto a compute node (usually via qlogin) to see how much total memory each process is using outside of the shared memory. Could you try several different numbers of `--processes` and record the total machine memory (not sum or processes) to get an estimate for the amount added by each worker. You shouldn't need to run for long to get an estimate for each workers usage.

**Comment by marcus1487** [comment]
Were you able to assess the actual memory used by each process here (not including the shared memory reference)?
