### ISSUE TITLE
Question: trimming signal values from start/end fast5 reads to remove adapter/barcode signals?

### ISSUE THREAD

**Issue by Koen-vdl** [nanoporetech/tombo#229]
I'm working with reads from a native barcoded run. I have already de-multiplexed the fast5 files. However I would like to know whether it is required to trim the adaptor/barcode sequence of 
each read’s signal at the fast5 level before re-squiggling. I use porechop for this for fastq files but I'm not sure how to approach this with fast5 files.  

Should I "blindly" delete 1000-2000 signal values from the start and end of the reads to remove adapter and barcode signals? I couldn't find a tool to do this.

**Comment by marcus1487** [comment]
Removing the adapter and barcode signal is not necessary. Tombo performs an initial processing step to identify the start of the mapped reference sequence within the signal, thus effectively perform the proposed signal trimming. In fact trimming too much signal might interfere with this reference sequence search and thus is not recommended.

**Comment by Koen-vdl** [comment]
Thx for the lighting fast response Marcus.
