### ISSUE TITLE
determine location of modified bases according to ouput of 'write_most_significant_fasta' 

### ISSUE THREAD

**Issue by Huanle** [nanoporetech/tombo#23]
Hi Markus,
the outputs (both the motif and the number of motifs) of tombo write_most_significant_fasta vary according to the '--num-bases'  and '--num-regions'.
How can i get the exact location of modified bases in the reference genome?
Thanks a lot.

**Comment by marcus1487** [comment]
Hi Huanle,

I'm not sure I completely understand the issue in the first part of your issue here, but the output of the write_most_significant_fasta is a fasta formatted file containing the genome sequence centered on the genomic locations with the largest estimated fraction of modified bases. For each record within these fasta files the genomic location is listed in the format "[chromosome]:[1-based genome position]:[strand]".

The preferred command to simply visualize the modified genomic locations would be the write_wiggles command that will output a wiggle format file listing the fraction of modified reads at each genomic location. I hope this helps!

**Comment by Huanle** [comment]
Hi Markus,

Thanks a lot for your response.

But it seems i did not make my question clear.

I know how to get the exact positions of potential modified bases. However, when I gave different values to '--num-bases', it generated different number of sequences in 'tombo_results.significant_regions.fasta'.

The smaller values brought about more sequences and thus more idnetified locations. Sometimes it even leads to minor change of the location.

E.g. 
>2595_T7:**116**:+ Frac Standard:1 Frac. Alternate:0 (when --num-bases 5)
>2595_T7:**117**:+ Frac Standard:1 Frac. Alternate:0 (when --num-bases 3)

So I wonder how to determine which value that should be used for the --num-bases' option ?
Does using large --num-bases values give rise to more reliable prediction?

Best,
Huanle

**Comment by marcus1487** [comment]
Hi Huanle,

This command certainly should not produce a different number of sequence records based on the `--num-bases` argument. If this is happening that is certainly a bug. Please confirm that you are indeed seeing a change in the number of sequence records when you change only the `--num-bases` argument.

As for the change in the listed location when the `--num-bases` argument is changed, this is completely expected. The printed location indicates the start of the region for which the sequence is provided. This region is centered on the genome location with the most significant result, as the purpose of the command is to extract the sequence around modified bases. Thus the difference between a 3-base and 5-base window would be 1 base on the upstream side and 1 base on the downstream side, resulting in a change of 1 in the fasta record. The exact computation of this region start location is found [here in the code](https://github.com/nanoporetech/tombo/blob/master/tombo/tombo_stats.py#L133).

As for the value of the `--num-bases` option, this is more of a context and research question. For the motifs reported in the original nanoraw pre-print manuscript I used a window of 15 (7 bases of context to either side of a modified location). A smaller or larger window may be applicable based on the particular biological context. The window should certainly be larger than any motif width one would hope to discover at a minimum.

**Comment by marcus1487** [comment]
Would you mind checking your tombo version (with ‘tombo —version’ command). I seem to remember this in a previous version but I think it is fixed in the most recent version (1.1.1).

**Comment by Huanle** [comment]
$ tombo --version
tombo version: 1.1.1

**Comment by marcus1487** [comment]
Is this a very small genome? The identified regions are forced to be further than half the —nun-bases apart. So a modified position cannot be contained within another region. Thus if the search space is very small the number of unique locations further than half the —nun-bases apart gets smaller and smaller for larger values of —num-bases. I will add a warning for this case in the future, but it would be great to confirm that this is indeed the issue in this case.

**Comment by Huanle** [comment]
Thanks Marcus,
The reference seqeunces are 5 artificial constructs of length 2200 - 2700 bp.
So, yes it represents very small genome.

Kind Regards,
Huanle

**Comment by marcus1487** [comment]
Glad we got to the bottom of this! I’ll add the warning message in the next release, but I’ll close this issue for now. Thanks for the effort tracking this down!

**Comment by Huanle** [comment]
thanks Markus for your help.
