### ISSUE TITLE
Merge/Concatenate differente tombo resquiggle output

### ISSUE THREAD

**Issue by stefanucci-luca** [nanoporetech/tombo#233]
Hi there,

I'd like to use ```tombo resquiggle``` to align Nanopore reads. I am working on the human genome. I am running the analysis on a HPC cluster, but it is taking too long (more than 100 hours). Do you have any suggestion on the memory to allocate?

Alternatively, could I split the fast5 files, process them in smaller batches and merge the resulting file together? Ho would you merge them then? a simple cat would work or is there some data structure I'll mess up?

Thanks,
Luca

**Comment by marcus1487** [comment]
What is your end goal? Generally tombo would not be recommended directly for mapping reads alone. 

Tombo should not use much more memory over the loaded reference genome unless read lengths are extremely long. Additional `--processes` should also not increase memory consumption too much.

In terms of splitting a run over smaller batches, this can lead to improved speed in certain environments. There should be no need to merge the outputs files. Most tombo commands accept multiple fast5 directories that will be processed together. If this is not true for a particular pipeline, please post this here.
