### ISSUE TITLE
per_read_stats output is empty

### ISSUE THREAD

**Issue by OlivierZablo** [nanoporetech/tombo#235]
Hi Marcus,

I've run a bunch of model_sample_compare runs without problems; however suddenly for one particular sample (that caused no problems in the past on the same tombo version), tombo keeps outputting empty per read stats files..I've run it several times to no avail. It does produces a full stats files though (but it's kind of off in the number of methylated sites).
The job log is as follows:
[15:03:18] Parsing Tombo index file(s).
[15:03:20] Performing two-sample comparison significance testing.
[15:03:20] Parsing Tombo index file(s).
[15:03:21] Calculating read coverage regions.
[15:03:21] Calculating read coverage.
[15:03:22] Calculating read coverage.
[15:03:22] Performing modified base detection across genomic regions.

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [3:39:34<00:00, 13174.51s/it]Traceback (most recent call last):
  File "/users/miniconda3/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/users/miniconda3/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/users/miniconda3/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

Any ideas what's going on??

Thanks in advance,
Olivier

**Comment by marcus1487** [comment]
I believe I have seen this error with very large chunks being processed at once and thus a large chunk of raw data being passed between processes and hitting a system limit. Was the `--multiprocess-region-size` set to a larger value for this run? Or is this a very deep sample?

**Comment by OlivierZablo** [comment]
Thanks for your fast reply!
The command I used successfully many times is this:

tombo detect_modifications model_sample_compare --fast5-basedirs $FAST5_SAMPLE \
                                                --statistics-file-basename <>  \
                                                --control-fast5-basedirs $FAST5_CONTROL \
                                                --sample-only-estimates \
                                                --fishers-method-context 3 \
                                                --per-read-statistics-basename <>
The sample is about 30,000 x coverage and the control is about 59K coverage ,so deep indeed I'd think.
I've never fiddled with --multiprocess-region-size or --processes for that matter. I have access to a cluster so resources are not an issue if you have a recommendation? I typically run this job with 16 cores/64gb ram.

Best,

**Comment by marcus1487** [comment]
Plus side of stay-at-home orders.

That level of coverage could indeed cause this issue. I would recommend setting `--multiprocess-region-size` to a lower value, so that the produced results are spread over more processes. This should resolve this issue. 

In terms of a long term fix unfortunately, this is not an easy error to catch at the interface of two processes. I think I looked at raising a more informative error here without luck previously, but can try again.

**Comment by OlivierZablo** [comment]
ok I'll try reducing that value. I see the default is 10000 (nucleotides?). I struggle to deduce scale here - should I reduce by thousands or hundreds or less? Will this change in region size impact results at all or is just to mitigate computation hurdles? (sorry not a programmer, biologist here!)

Stay safe!

**Comment by marcus1487** [comment]
Yes the default in 10000 nucleotides. From the log you posted it looks like only a single window was processed. Thus it is hard to estimate the appropriate size for this sample. 1000 would be a good starting guess. 

The results will not change at all. This is purely a computational parameter. Larger values generally help I/O speed at the cost of potential issues like this. Here are some details on the parameter. https://nanoporetech.github.io/tombo/modified_base_detection.html#multi-processing

One other option is to downsample reads from the very deep sample. See this command https://nanoporetech.github.io/tombo/filtering.html#tombo-filter-level-coverage

**Comment by OlivierZablo** [comment]
Ok great thank you so much for all your guidance!
