### ISSUE TITLE
no reads found by detect_modifications - human CpG 

### ISSUE THREAD

**Issue by clariB** [nanoporetech/tombo#237]
I am trying to detect human CpG methylation. I first ran the resquiggle command. This is my output from that:

```
[10:09:13] Loading minimap2 reference.
[10:21:29] Getting file list.
[10:21:29] Loading default canonical ***** DNA ***** model.
[10:21:31] Re-squiggling reads (raw signal to genomic sequence alignment).
5 most common unsuccessful read types (approx. %):
     6.2% (    249 reads) : Alignment not produced                                                          
     2.7% (    106 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`)
     1.6% (     62 reads) : Read event to sequence alignment extends beyond bandwidth                       
     0.1% (      5 reads) : Reference mapping contains non-canonical bases (transcriptome reference cannot contain U bases)
     -----
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4000/4000 [21:20<00:00,  3.12it/s]
[10:42:51] Final unsuccessful reads summary (10.5% reads unsuccessfully processed; 422 total reads):
     6.2% (    249 reads) : Alignment not produced                                                          
     2.6% (    106 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`)
     1.6% (     62 reads) : Read event to sequence alignment extends beyond bandwidth                       
     0.1% (      5 reads) : Reference mapping contains non-canonical bases (transcriptome reference cannot contain U bases)

```

I then ran "tombo filter stuck" on the fast5 directory then ran detect_modifications:

`tombo detect_modifications alternative_model --fast5-basedirs Desktop/methylation_data/130and131/single130_131_fast5/1/ --statistics-file-basename human_cpg_testing_130_131 --alternate-bases CpG --processes 4 --dna`

This is my output:
```
[16:17:14] Parsing Tombo index file(s).
[16:17:14] Performing alternative model testing.
[16:17:15] Performing specific alternate base(s) testing.
[16:17:15] Calculating read coverage regions.
[16:17:15] Calculating read coverage.
[16:17:15] Performing modified base detection across genomic regions.
0it [00:00, ?it/s]
```
Why would there be no reads were found by the detect modification command? It appears to me that resquiggle ran successfully.

**Comment by marcus1487** [comment]
What was the result of the `filter_stuck` command? Could you confirm via the `text_output` commands that you have valid covered regions after this filtering?

**Comment by clariB** [comment]
result of filter_stuck:
```
[15:59:47] Parsing Tombo index file(s).
[15:59:47] Filtering stuck reads.
[15:59:58] Filtered 3684 reads (100.0% of previously filtered and 100.0% of all valid reads) reads due to observations per base filter from 1.
[15:59:58] Saving Tombo reads index to file.
```
result of text_output:
```
[16:59:05] Parsing Tombo index file(s)
******************** ERROR ********************
	No reads present in --fast5-basedirs.
```
So after filtering w/stuck, it just filtered out all of the fast5s? Does that just mean I don't have very high-quality reads?

**Comment by marcus1487** [comment]
What was the filter command options used? It may just be that the thresholds used were too stringent. See `tombo filter stuck -h` for a description of the filter options.

**Comment by clariB** [comment]
I didn't add any filter options. I just ran 
`tombo filter stuck --fast5-basedirs Desktop/methylation_data/130and131/single130_131_fast5/1`

**Comment by marcus1487** [comment]
The `--obs-per-base-filter` argument should be required for this argument. Unfortunately, the behavior when this value is not set it to filter all reads regardless of the read metrics. I have made this change on the github repo (1e2e996), but setting this argument should fix this filtering issue.
