### ISSUE TITLE
conda install, lack of r-cowplot in bioconda

### ISSUE THREAD

**Issue by Runsheng** [nanoporetech/tombo#24]
I used  ```conda install -c bioconda ont-tombo``` directly in a new mini conda env. However, the bioconda channel do not contain r-cowplot. I can only finish the install by adding r-cowplot with other channels ```conda install -c conda-forge r-cowplot``` and then the package works well.

**Comment by marcus1487** [comment]
Thank you for this issue report. I have been working on replacing cowplot internally for essentially this issue of requiring the conda-forge channel (which can cause a host of other issues). I hope to have a release replacing this with the r-gridextra dependency soon. I will reference this issue when I have pushed this change.
