### ISSUE TITLE
Event to sequence alignment extends beyond bandwidth

### ISSUE THREAD

**Issue by youyupei** [nanoporetech/tombo#240]
Hi,

I am using tombo resquiggle to map squiggle to the baseballs. But for a lot of reads, I received an error: "tombo.tombo_helper.TomboError: Read event to sequence alignment extends beyond bandwidth". I guess this is because the DTW path went outside the band? (I am not sure.) How can I get those reads successfully resquiggled ?  It would be very appreciated if anyone could help.

**Comment by youyupei** [comment]
Just to clarify, the code I am using is from https://gist.github.com/marcus1487/5cf083644143aafc770dceb213783346

**Comment by marcus1487** [comment]
This error does indeed indicate that the band likely does not contain the true path. This is determined by the path coming within a set range of the edge of the bandwidth. This parameter is obtained at line 14 from the referenced script. The parameter of interest is `band_bound_thresh`. If this is set to `0` this error will not be encountered, though this does indicate that the inferred path is likely incorrect. You can set this parameter by adding this line: `rsqgl_params = rsqgl_params ._replace(band_bound_thresh=0)`. I would recommend instead increasing the bandwidth though. This should allow the correct path to be obtained at the cost of higher compute costs. This parameter is `bandwidth`. The default values for these values can be found here: https://github.com/nanoporetech/tombo/blob/master/tombo/_default_parameters.py#L50. I would recommend trying a new bandwidth value around `2000` (set with `rsqgl_params = rsqgl_params ._replace(bandwidth=2000)`).

**Comment by LeilyR** [comment]
Hi, 
I am having similar issue. Though , I got only `36.2% reads unsuccessfully processed`. Is this a high rate for Nanopore RNA reads? Would you think I should try a new bandwidth to restore more? Or that would not help the percentage? Thanks!

**Comment by marcus1487** [comment]
@LeilyR , increasing the bandwidth will only help if the errors are downstream of the re-squiggle algorithm. For example increasing the bandwidth will not effect the "No alignment" error type. If you could post the full list of error types and percentages I could comment on these or you can find more information in [the docs here](https://nanoporetech.github.io/tombo/resquiggle.html#common-failed-read-descriptions). 

In general, I would say that 36% failed reads for a direct RNA sample is not too bad. Some of the Tombo filters can be somewhat strict for certain samples.

**Comment by LeilyR** [comment]
Hi @marcus1487 , Thanks a lot for the quick reply and feedback. I will check the doc. , however here is the full error message as you have asked: 

`:::
Traceback (most recent call last):
  File "/package/anaconda3/envs/ont-tombo-1.5.1/lib/python3.7/site-packages/tombo/tombo_helper.py", line 94, in banded_traceback
    return c_banded_traceback(*args, **kwargs)
  File "tombo/_c_dynamic_programming.pyx", line 305, in tombo._c_dynamic_programming.c_banded_traceback
NotImplementedError: Read event to sequence alignment extends beyond bandwidth

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/package/anaconda3/envs/ont-tombo-1.5.1/lib/python3.7/site-packages/tombo/resquiggle.py", line 1575, in _resquiggle_worker
    map_res, rsqgl_params, fast5_fn, all_raw_signal)
  File "/package/anaconda3/envs/ont-tombo-1.5.1/lib/python3.7/site-packages/tombo/resquiggle.py", line 1497, in run_rsqgl_iters
    seq_samp_type=seq_samp_type)
  File "/package/anaconda3/envs/ont-tombo-1.5.1/lib/python3.7/site-packages/tombo/resquiggle.py", line 1168, in resquiggle_read
    seq_samp_type=seq_samp_type, reg_id=map_res.align_info.ID)
  File "/package/anaconda3/envs/ont-tombo-1.5.1/lib/python3.7/site-packages/tombo/resquiggle.py", line 1038, in find_adaptive_base_assignment
    rsqgl_params.band_bound_thresh)
  File "/package/anaconda3/envs/ont-tombo-1.5.1/lib/python3.7/site-packages/tombo/tombo_helper.py", line 96, in banded_traceback
    raise TomboError(unicode(e))
tombo.tombo_helper.TomboError: Read event to sequence alignment extends beyond bandwidth

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/package/anaconda3/envs/ont-tombo-1.5.1/lib/python3.7/site-packages/tombo/resquiggle.py", line 1583, in _resquiggle_worker
    map_res, save_params, fast5_fn, all_raw_signal)
  File "/package/anaconda3/envs/ont-tombo-1.5.1/lib/python3.7/site-packages/tombo/resquiggle.py", line 1497, in run_rsqgl_iters
    seq_samp_type=seq_samp_type)
  File "/package/anaconda3/envs/ont-tombo-1.5.1/lib/python3.7/site-packages/tombo/resquiggle.py", line 1168, in resquiggle_read
    seq_samp_type=seq_samp_type, reg_id=map_res.align_info.ID)
  File "/package/anaconda3/envs/ont-tombo-1.5.1/lib/python3.7/site-packages/tombo/resquiggle.py", line 1028, in find_adaptive_base_assignment
    fwd_pass, fwd_pass_move, band_event_starts, shifted_z_scores = run_fwd_pass()
  File "/package/anaconda3/envs/ont-tombo-1.5.1/lib/python3.7/site-packages/tombo/resquiggle.py", line 899, in run_fwd_pass
    mapped_start_offset, rsqgl_params, events_per_base)
  File "/package/anaconda3/envs/ont-tombo-1.5.1/lib/python3.7/site-packages/tombo/resquiggle.py", line 676, in _get_masked_start_fwd_pass
    shifted_z_scores[seq_pos,:] = get_start_mask_z_score(seq_pos, event_pos)
  File "/package/anaconda3/envs/ont-tombo-1.5.1/lib/python3.7/site-packages/tombo/resquiggle.py", line 661, in get_start_mask_z_score
    event_vals, r_ref_means[seq_pos], r_ref_sds[seq_pos],
IndexError: index 553 is out of bounds for axis 0 with size 553`

And here is the statistic:

` Unexpected errors occured. See full error stack traces for first (up to) 50 errors in "unexpected_tombo_errors.6789.err"
[00:51:59] Final unsuccessful reads summary (36.2% reads unsuccessfully processed; 1532332 total reads):
    33.6% (1421346 reads) : Alignment not produced
     2.5% ( 106944 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`)
     0.1% (   4039 reads) : Read event to sequence alignment extends beyond bandwidth
     0.0% (      1 reads) : Unexpected error
     0.0% (      1 reads) : Read failed sequence-based signal re-scaling parameter estimation.
     0.0% (      1 reads) : Not enough raw signal around potential genomic deletion(s)
[00:51:59] Saving Tombo reads index to file.`

**Comment by marcus1487** [comment]
@LeilyR from the output it appears that 33.6% of the unsuccessfully processed reads did not produce a valid base space mapping (`Alignment not produced` category). Thus these reads did no proceed to the signal mapping part of processing. Adjusting the bandwidth will not effect this portion of the reads.

**Comment by LeilyR** [comment]
@marcus1487 Thanks a lot!

**Comment by NuriaDiaz** [comment]
> This error does indeed indicate that the band likely does not contain the true path. This is determined by the path coming within a set range of the edge of the bandwidth. This parameter is obtained at line 14 from the referenced script. The parameter of interest is `band_bound_thresh`. If this is set to `0` this error will not be encountered, though this does indicate that the inferred path is likely incorrect. You can set this parameter by adding this line: `rsqgl_params = rsqgl_params ._replace(band_bound_thresh=0)`. I would recommend instead increasing the bandwidth though. This should allow the correct path to be obtained at the cost of higher compute costs. This parameter is `bandwidth`. The default values for these values can be found here: https://github.com/nanoporetech/tombo/blob/master/tombo/_default_parameters.py#L50. I would recommend trying a new bandwidth value around `2000` (set with `rsqgl_params = rsqgl_params ._replace(bandwidth=2000)`).

Dear Marcus,

I'm having the same issue which is described in this post, however I'm trying to set the indicated variable `rsqgl_params = rsqgl_params ._replace(bandwidth=2000)` but somehow I'm not able. How do I exactly have to set it? Just running it in the command line gives me the following error: `bash: syntax error near unexpected token `('`

Thanks,
Núria
