### ISSUE TITLE
resquiggle mapping  （filter too much reads）

### ISSUE THREAD

**Issue by samll-rookie** [nanoporetech/tombo#242]
1、I resquiggle my ont pass fast5 to genome ,but it filter too much reads（505277 reads） and result in  a little covearage for genome .The final results are as follows:

2、How to I use more reads to ananlysis (adjusting parameter )；How to effectively avoid?

3、What accounts for this  ？ratio of 26.5% ( 245887 reads) and  25.1% ( 232719 reads)   

4、The final results are as follows:
[15:03:13] Final unsuccessful reads summary (54.4% reads unsuccessfully processed; 505277 total reads):
    26.5% ( 245887 reads) : Read event to sequence alignment extends beyond bandwidth                       
    25.1% ( 232719 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`) 
     1.7% (  15393 reads) : Reference mapping contains non-canonical bases (transcriptome reference cannot contain U bases)
     1.2% (  11233 reads) : Alignment not produced                                                          
     0.0% (     21 reads) : Not enough raw signal around potential genomic deletion(s)                      
     0.0% (     14 reads) : Read failed sequence-based signal re-scaling parameter estimation.              
     0.0% (      7 reads) : Read contains too many potential genomic deletions                              
     0.0% (      3 reads) : Too much raw signal for mapped sequence

**Comment by marcus1487** [comment]
The read sequence bandwidth error can be reverted by either increasing the bandwidth (at the cost of more compute cost) or decreasing the bandwidth edge threshold (at the cost of potentially poor signal alignments). See more information about setting these options by running the resquiggle command with the `—print-advanced-arguments` option. 

As noted in the second error message, these reads can be accessed by running the `tombo filter clear_filters` command. Note that these reads will also generally show poor signal alignment that may effect downstream analyses.

**Comment by samll-rookie** [comment]
> The read sequence bandwidth error can be reverted by either increasing the bandwidth (at the cost of more compute cost) or decreasing the bandwidth edge threshold (at the cost of potentially poor signal alignments). See more information about setting these options by running the resquiggle command with the `—print-advanced-arguments` option.
> 
> As noted in the second error message, these reads can be accessed by running the `tombo filter clear_filters` command. Note that these reads will also generally show poor signal alignment that may effect downstream analyses.

1、how to increasing the bandwidth in the script ?
2、I find the parameter  (--signal-align-parameters DNA : 4.2 4.2 300 1500 20.0 40 750 2500 250) ，I should   modify the second(300) or the three(1500) number  as  what is right?
#tombo resquiggle --signal-align-parameters 4.2 4.2 300 1500 20.0 40 750 2500 250 fast5dir genome.fa -processes 40 --num-most-common-errors 5

**Comment by samll-rookie** [comment]
1、how to increasing the bandwidth in the script ?
2、I find the parameter (--signal-align-parameters DNA : 4.2 4.2 300 1500 20.0 40 750 2500 250) ，I should modify the second(300) or the three(1500) number as what is right?
#tombo resquiggle --signal-align-parameters 4.2 4.2 300 1500 20.0 40 750 2500 250 fast5dir genome.fa -processes 40 --num-most-common-errors 5
