### ISSUE TITLE
How to filter index file  by the specific sub-folder condition temporarily.

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#243]
HI:
I have a folder which contian three biological duplications(3 sub-folder behind `root_dir`).
Firstly I used tombo to index `root_dir` along with  emergence `root_dir.RawGenomeCorrected_000.tombo.index`
I have a question:how to filter index file  by the specific sub-folder condition temporarily.
for example,I just want tombo using reads of batch1 for downstream analysis.
But I don't want to Rebuild an index for batch1. 
```
root_dir
├── batch1
├── batch2
└── batch3
```

**Comment by marcus1487** [comment]
There is not a way to do this using the command line utilities, but you could use the python API to perform this filter and re-save the index file. Here is the [documentation for the readData object](https://nanoporetech.github.io/tombo/tombo.html#tombo.tombo_helper.readData). The `fn` attrubute should allow this type of filtering. I would recommend copying the index file to revert to the original filters.

**Comment by weir12** [comment]
thanks!
