### ISSUE TITLE
Can I distribute tasks of Tombo to different node in sge? and The running time is so long. 2, Can I use alternative mode for human or other species methylations calling ?

### ISSUE THREAD

**Issue by forrwill** [nanoporetech/tombo#244]

**Comment by forrwill** [comment]
Looking forward to your reply!

**Comment by marcus1487** [comment]
Individual tombo commands are not capable of being distributed over SGE nodes, but individual tombo commands can be split up and distributed (e.g. via a job array). Each call should be made to a distinct set of files/reads so that no file is accessed simultaneously. After the re-squiggle step, tombo index files are merged internally (at very low overhead) and further processing (`detect_modifications`, `text_output`, etc.) can proceed. 

The alternative mode can indeed be applied to human or other species.

**Comment by forrwill** [comment]
thanks for your reply!  and there is another question for me. I output the fraction and valid coverage with text_output commands, the result is as below(I transformed the wig to bed format):
![image](https://user-images.githubusercontent.com/41096851/81768145-df7ed980-950c-11ea-8776-1356aba1be4d.png)
The position seems not very clear, start != end; and I don't know which is the methylated pos

**Comment by forrwill** [comment]
==> 6mA_valid_cov <==
NC_002516.2	7	8	+	12.0
NC_002516.2	9	10	+	6.0
NC_002516.2	16	17	+	9.0
NC_002516.2	17	18	-	15.0
NC_002516.2	18	19	-	15.0
NC_002516.2	20	21	-	11.0
NC_002516.2	21	22	+	8.0
NC_002516.2	23	24	-	8.0
NC_002516.2	25	26	+	10.0
NC_002516.2	26	27	+	8.0

==> 6mA.fraction <==
NC_002516.2	7	8	+	0.0833
NC_002516.2	9	10	+	0.0
NC_002516.2	16	17	+	0.5556
NC_002516.2	17	18	-	0.0667
NC_002516.2	18	19	-	0.0667
NC_002516.2	20	21	-	0.0909
NC_002516.2	21	22	+	0.875
NC_002516.2	23	24	-	0.375
NC_002516.2	25	26	+	0.5
NC_002516.2	26	27	+	0.375

**Comment by marcus1487** [comment]
For the positions, this is unrelated to Tombo. The BED format uses closed start, open end coordinate systems, so for a single base position end = start - 1. For the methylated positions, methylation is not binary in many biological systems. Thus the fraction of reads covering a site which are estimated to be methylated is reported at each position. It is left to the users goals for how to interpret these fraction methylated values.

**Comment by forrwill** [comment]
thank you. I get it

**Comment by forrwill** [comment]
could you please give me some advice about the parameter --q-score?
the log tells me that 60% reads "Alignment is not produced" using the default parameters without quality control.
the data is NA12878, and the ref is Ensembl_release98 version of human, and I don't know if it is  the poor quality produced the problem. 
I want to  set a Threshold for the reads quality.  and I need you advice. 
![image](https://user-images.githubusercontent.com/41096851/81780271-d996f180-9528-11ea-9c3e-2a113a93fb47.png)

**Comment by marcus1487** [comment]
The "Alignment not produced" is encountered before applying the q-score threshold, so changing the q-score threshold will not effect this output. Changing either the basecalling model or reference genome to match the reads are the two options to fix this read processing step.

**Comment by forrwill** [comment]
thank you very much,
