### ISSUE TITLE
Extract all-context methylation information

### ISSUE THREAD

**Issue by DAVID2022** [nanoporetech/tombo#247]
Hi,

Can you tell me how can I extract  DNA m5C methylation information on CHH or CHG motif like you present in this poster?
[p17020-tombo.pdf](https://github.com/nanoporetech/tombo/files/4644744/p17020-tombo.pdf)

**Comment by marcus1487** [comment]
The roc curves in this poster were computed using the de novo detection method. These locations can be plotted with the genome locations plotting method.

**Comment by DAVID2022** [comment]
@marcus1487 Can I  using 
“tombo detect_modifications alternative_model   --alternate-bases 5mC ” to detect 5mc modified base in all context，and than use“ tombo text_output browser_files    --motif-descriptions CHG:1:CHG_5mC ” toextract all context DNA m5C methylation information in CHG motif?

Thank you very much for your kind help !

**Comment by marcus1487** [comment]
Yes. That command could be used as well. The performance of the 5mC all-context model may not be as good as the de novo method though. The motif specification in the text output command should work for the de novo output as well.
