### ISSUE TITLE
Suggested public datasets for evaluation

### ISSUE THREAD

**Issue by shubhamchandak94** [nanoporetech/tombo#248]
Hi,
Hope you are doing well.
We are working on analyzing the impact of lossy compression of nanopore raw signal on various downstream performance metrics such as read accuracy and consensus accuracy (see first version on [biorxiv](https://www.biorxiv.org/content/10.1101/2020.04.19.049262v1)).
We are planning to analyze whether lossy compression adversely impacts detection of modified nucleotides. I had a couple of questions in this regard:
1. Is there some standard public dataset (preferably microbial) for evaluating this? We are looking for a dataset where the ground truth methylation pattern is known.
2. I realized that [medaka](https://github.com/nanoporetech/medaka) also supports methylation calling when the appropriate basecaller is used. Do you have any recommendation regarding which tool to use, assuming we probably won't use the advanced features in tombo?

Thanks a lot,
Shubham Chandak

**Comment by marcus1487** [comment]
We do not currently have a public data set for such purposes, but are working to release some data in the coming months.

For the best modified base detection, I would recommend [Megalodon](https://github.com/nanoporetech/megalodon), when an appropriate basecalling model is available. Megalodon uses the same basecalling models that Medaka works with, but Megalodon anchors the intermediate basecalling data to the reference sequence producing higher accuracy modified base calls. We are working to add more options for basecalling models (see the [Rerio respiratory](https://github.com/nanoporetech/rerio)), but there are some tasks for which Tombo is still the recommendation. For example Tombo is still recommended for RNA modified base analysis via the sample compare method. Tombo is also recommended for de novo modified base detection.

**Comment by shubhamchandak94** [comment]
Thanks!
