### ISSUE TITLE
aggregate raw data from multiple genomic loci containing the same motif

### ISSUE THREAD

**Issue by wkloosterman** [nanoporetech/tombo#25]
Hi,
I would like to perform a motif analysis using Tombo. However, I only have low coverage sequencing data (<1x). I thought about aggregating the raw resquiggled signal across multiple reads that contain the same motif. So, say I have motif CGTAGC, I would like to extract and plot all reads with this motif on top of each other. Of course, I can use tombo plot_motif_centered, but this gives separate plots for each genomic location that contains the above motif. Instead, I would like to overlap the signal corresponding to this motif (at separate genomic loci) in one plot. Is this currently possible?

As an alternative, I could parse the resquiggled fast5 files myself and extract the raw signal from the reads and then plot.

Thanks,
Wigard Kloosterman

**Comment by marcus1487** [comment]
Hi Wigard,

I think this type of plot would be quite difficult to interpret and digest for the vast majority of users and thus I don't think I would add this as a main tombo command. The other command that is useful for this context is the `plot_motif_with_stats` command (though the stat distribution will obviously not be very useful with the low coverage).

The main issue is that the signal for a particular base is effected by the surrounding 5-8 bases. Thus for your example 6 base context only one or 2 bases would be consistent across different genomic locations (with different bases outside the specified context). Thus this command would likely be suggested only for contexts greater than 9 or 10 bases at a minimum. Having these caveats for a main command seems like it might contribute to some misleading plots and interpretations from users.

I could look into adding a short script to the repo using the tombo python API for this purpose (that would look much like the code from the [`plot_motif_with_stats` code](https://github.com/nanoporetech/tombo/blob/master/tombo/plot_commands.py#L1703)). A new major release is coming shortly (hopefully by the end of the day today). In this release the API is cleaned up a good bit, so this would be a bit easier to construct. I would suggest using the tombo python api as opposed to parsing the FAST5 yourself, but obviously the data is there for your own analysis if you wish.

**Comment by wkloosterman** [comment]
Hi Marcus,

Thanks! I am aware of the influence of neighbouring bases on the signal. We are only interested in the middle base of a motif, so that should work if the motif is large enough, as you suggested.

If there is a possibility to add a short script for this purpose, that would be greatly appreciated of course. I'll check out the new API anyways.

Just running the plot_motif_with_stats command is staying at the 'Finding significant regions with motif' step for a very long time (hours).

**Comment by marcus1487** [comment]
This task is now has a much more concise implementation with the python API re-write in the 1.4 release. The same issues/warnings with comparing signal across genomic positions with the same motif holds, but programmatically the task is now possible in the Tombo API.

This task would involve linking together several Tombo classes. These classes (with links to the docs) are: [`Fasta`](https://nanoporetech.github.io/tombo/tombo.html#tombo.tombo_helper.Fasta), [`TomboMotif`](https://nanoporetech.github.io/tombo/tombo.html#tombo.tombo_helper.TomboMotif), [`TomboReads`](https://nanoporetech.github.io/tombo/tombo.html#tombo.tombo_helper.TomboReads) and maybe a couple of other `tombo_helper` functions. Hopefully this API re-write and documentation will help with this task!
