### ISSUE TITLE
tombo preprocess annotate_raw_with_fastqs

### ISSUE THREAD

**Issue by akk01** [nanoporetech/tombo#250]
The step `tombo preprocess annotate_raw_with_fastqs` is confusing. In case I have already performed base calling using Guppy, is this step is still required?

**Comment by marcus1487** [comment]
This step is required if only FASTQ basecalls were output and not basecalled FAST5. This allows users who have performed basecalling, but did not select the FAST5 output type to proceed with Tombo processing without performing the computationally expensive basecalling step again.

Find this and further documentation on this command [here in the docs](https://nanoporetech.github.io/tombo/resquiggle.html#pre-process-raw-reads).
