### ISSUE TITLE
Problem with  calc_window_fishers_method

### ISSUE THREAD

**Issue by scibigot** [nanoporetech/tombo#251]
Hello,

I got a confusing error message (screen) after running tombo detect_modifications model_sample_compare.

I use
Tombo version: 1.5.1
Ubuntu 19.10
Python 2.7

<img width="1251" alt="Снимок экрана 2020-05-25 в 15 00 29" src="https://user-images.githubusercontent.com/13982695/82813847-903a9080-9e9e-11ea-942e-ecf17ccd00b2.png">

**Comment by marcus1487** [comment]
I would recommend upgrading to python 3.5 or higher. The multiprocessing interface in python2 can cause issues such as this and python 2 is no longer supported.

**Comment by marcus1487** [comment]
Was an upgrade to python3 able to resolve this issue?

**Comment by scibigot** [comment]
Yes, it fixed the problem, thanks for the advice. 
But this is a super weird error so as it worked on a second strain with version 2

**Comment by marcus1487** [comment]
Yes I had the same experience. I think it has to do with some internal limits on the multiprocessing side that are not handled well in python2. I would guess that the sample which worked might have lower coverage.

Glad the issue is solved in any case!
