### ISSUE TITLE
my detect detect_modifications running with warning " Tombo index file does not exist for one or more directories", and why I can not create index for fast5, and this problem will surely slow down my task.

### ISSUE THREAD

**Issue by forrwill** [nanoporetech/tombo#252]

**Comment by forrwill** [comment]
my resquiggle command:
tombo resquiggle --dna --processes 4  --num-most-common-errors 5 --ignore-read-locks --fast5-basedirs basecall2/work1/workspace/  genome.fa

my detect_modification command:
tombo  detect_modifications alternative_model --fast5-basedirs  basecall2/work1/workspace   --statistics-file-basename statistic  --alternate-bases CpG 6mA 5mC --dna --processes 8
The log file is as below:
[10:05:03] Parsing Tombo index file(s).
******************** WARNING ********************
	Tombo index file does not exist for one or more directories.
		If --skip-index was not set for re-squiggle command, ensure that the specified directory is the same as for the re-squiggle command.

**Comment by forrwill** [comment]
![image](https://user-images.githubusercontent.com/41096851/82884860-ec70e380-9f76-11ea-9ac8-ee56fa154358.png)
my tombo task is always on "D" status, when I submit the job

**Comment by AicuiZhang** [comment]
Hi! @forrwill 
I met the same problem that when I submit tombo task, it turned out D status which means dormant. I saw you closed this question by yourself. Could you please tell me how you worked out?

**Comment by marcus1487** [comment]
Generally this happens when the exact directory specified in the resquiggle command is not provided to the detect_modfications command. The resquiggle command write a hidden file (starts with a `.`) immediately alongside the fast5 directory. As such the exact same directory must be specified for both the resquiggle and detect_modifications commands.
