### ISSUE TITLE
Requiggle records with both genome and cDNA reference instead of overwrite

### ISSUE THREAD

**Issue by akk01** [nanoporetech/tombo#257]
I want to perform requiggle with both genome and cDNA reference with same Fast5. Is there anyway to keep both without overwriting.

**Comment by marcus1487** [comment]
The `--corrected-group` argument to all Tombo commands is intended for this purpose. This argument should be available for all applicable Tombo commands. See more documentation about this [here](https://nanoporetech.github.io/tombo/resquiggle.html#tombo-fast5-format).
