### ISSUE TITLE
Install with pip and conda fails on Mac El Capitan & Centos6

### ISSUE THREAD

**Issue by timkahlke** [nanoporetech/tombo#26]
Tried to set up tombo using pip on Mac El Capitan 10.11.6 and Centos6 with identical result:

```
gcc: tombo/c_dynamic_programming.cpp: No such file or directory
...
Failed building wheel for ont-tombo
...
```

**Comment by timkahlke** [comment]
Install with conda on both systems fails with the same error:

```
conda install -c bioconda ont-tombo
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - ont-tombo
  - r-cowplot

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
```

**Comment by nickschurch** [comment]
I have exactly the same error on Centos 6.3...

**Comment by marcus1487** [comment]
I am having some issues getting the update pushed to bioconda, but I should have this resolved shortly and I will post here with an update.

For the pip install, the release is live on pip, so I am not sure why you are getting an error there. Would you mind sending the command used to install with pip and the full stack trace? Thanks!

**Comment by nickschurch** [comment]
I get exactly the same error with the conda install, but I tried the pip install within a closed conda python 3.6.4 environment and I'm getting a different gcc error. gcc is failing because it can't find -liconv. Looks like it might be related to rpy2?

```
bash-4.1$ pip install ont-tombo[full] > tombo_pip_install.log
  Failed building wheel for rpy2
Command "/cluster/gjb_lab/nschurch/cluster_installs/miniconda2/envs/ONTpipeline/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-oxway1ba/rpy2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-hvn1b590-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-oxway1ba/rpy2/
bash-4.1$ 
```

The full log is here:
[tombo_pip_install.log](https://github.com/nanoporetech/tombo/files/1720682/tombo_pip_install.log)

The conda env should be able to be reproduced from this yaml:
[tombo_pip_install.yaml.gz](https://github.com/nanoporetech/tombo/files/1720692/tombo_pip_install.yaml.gz)

**Comment by marcus1487** [comment]
Ya. That does certainly look like an rpy2 install error and I am able to reproduce that locally on ubuntu and mac. I think as a workaround you can install the dependencies with conda and then install tombo with pip. Here is the list of requirements:

`conda install setuptools h5py numpy scipy cython mappy future pyfaidx rpy2 r-base r-gridextra r-ggplot2`

The bioconda source has been submitted and passed build checks. It is now just waiting on maintainer approval and a new bioconda build, so it should be available shortly. https://github.com/bioconda/bioconda-recipes/pull/7670

**Comment by timkahlke** [comment]
Never mind, got it to run on both systems. Problem causes: outdated gcc on Centos6 and native-python/miniconda/pip-confusion on Mac.

**Comment by marcus1487** [comment]
Glad you were able to sort it out!

In the meantime the [bioconda release](http://bioconda.github.io/recipes/ont-tombo/README.html) has been accepted. So that should make things easier moving forward.

**Comment by ma-diroma** [comment]
Hi, 

I have a similar issue on CentOS 6.5. I have successfully installed setuptools h5py numpy scipy cython mappy future pyfaidx rpy2 using pip2.7, gridextra and ggplot2 for R version 3.4.1.
However when I try to install tombo, I have an error

pip2.7 install ont-tombo --user
Collecting ont-tombo
  Using cached ont-tombo-1.2.tar.gz
Requirement already satisfied: h5py in /home/madiroma/.local/lib/python2.7/site-packages (from ont-tombo)
Requirement already satisfied: numpy in /home/madiroma/.local/lib/python2.7/site-packages (from ont-tombo)
Requirement already satisfied: scipy in /home/madiroma/.local/lib/python2.7/site-packages (from ont-tombo)
Requirement already satisfied: cython in /home/madiroma/.local/lib/python2.7/site-packages (from ont-tombo)
Requirement already satisfied: setuptools>=18.0 in /usr/local/lib/python2.7/site-packages/setuptools-21.2.1-py2.7.egg (from ont-tombo)
Requirement already satisfied: mappy in /home/madiroma/.local/lib/python2.7/site-packages (from ont-tombo)
Requirement already satisfied: future in /home/madiroma/.local/lib/python2.7/site-packages (from ont-tombo)
Requirement already satisfied: six in /home/madiroma/.local/lib/python2.7/site-packages (from h5py->ont-tombo)
Building wheels for collected packages: ont-tombo
  Running setup.py bdist_wheel for ont-tombo ... error
  Complete output from command /usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jvUdRG/ont-tombo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpvyNgthpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-jvUdRG/ont-tombo/setup.py", line 90, in <module>
      'Topic :: Scientific/Engineering :: Bio-Informatics',
    File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/madiroma/.local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "build/bdist.linux-x86_64/egg/setuptools/command/build_py.py", line 50, in run
    File "/usr/local/lib/python2.7/distutils/command/build_py.py", line 373, in build_packages
      self.build_module(module, module_file, package)
    File "build/bdist.linux-x86_64/egg/setuptools/command/build_py.py", line 70, in build_module
    File "/usr/local/lib/python2.7/distutils/command/build_py.py", line 334, in build_module
      "'package' must be a string (dot-separated), list, or tuple")
  TypeError: 'package' must be a string (dot-separated), list, or tuple
  
  ----------------------------------------
  Failed building wheel for ont-tombo
  Running setup.py clean for ont-tombo
Failed to build ont-tombo
Installing collected packages: ont-tombo
  Running setup.py install for ont-tombo ... error
    Complete output from command /usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jvUdRG/ont-tombo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-qcPhBc-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jvUdRG/ont-tombo/setup.py", line 90, in <module>
        'Topic :: Scientific/Engineering :: Bio-Informatics',
      File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 61, in run
      File "/usr/local/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "build/bdist.linux-x86_64/egg/setuptools/command/build_py.py", line 50, in run
      File "/usr/local/lib/python2.7/distutils/command/build_py.py", line 373, in build_packages
        self.build_module(module, module_file, package)
      File "build/bdist.linux-x86_64/egg/setuptools/command/build_py.py", line 70, in build_module
      File "/usr/local/lib/python2.7/distutils/command/build_py.py", line 334, in build_module
        "'package' must be a string (dot-separated), list, or tuple")
    TypeError: 'package' must be a string (dot-separated), list, or tuple
    
    ----------------------------------------
Command "/usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jvUdRG/ont-tombo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-qcPhBc-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-jvUdRG/ont-tombo/

Could you please help me?
Maria Angela

**Comment by marcus1487** [comment]
My guess is that this is accessing an old version of distutils. This is why the setuptools >version 18 is required. My guess is that the version of pip you are using might be out of date, or and old version of setuptools/distutils has made its way in front of the installed setuptools in your path.

I would suggest trying a conda install as debugging system python package install issues can be quite a headache.

**Comment by ma-diroma** [comment]
I tried with conda

```
conda install -c bioconda ont-tombo
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - libedit
  - ont-tombo -> r-base 3.4.1* -> ncurses 5.9*
Use "conda info <package>" to see the dependencies for each package.
```

and then

```
conda info libedit
Fetching package metadata ...........

libedit 3.1 heed3624_0
----------------------
file name   : libedit-3.1-heed3624_0.tar.bz2
name        : libedit
version     : 3.1
build string: heed3624_0
build number: 0
channel     : defaults
size        : 171 KB
arch        : None
license     : 3-Clause BSD
license_family: BSD
md5         : 91ce7622c3bc0a51cb3b897749f1aeaf
noarch      : None
platform    : None
subdir      : linux-64
timestamp   : 1505666480132
url         : https://repo.continuum.io/pkgs/main/linux-64/libedit-3.1-heed3624_0.tar.bz2
dependencies:
    libgcc-ng >=7.2.0
    ncurses 6.0.*
```

What do you suggest?

**Comment by marcus1487** [comment]
When I install tombo my version of conda removes libedit. I had really not noticed this before. My first guess would be to update/re-install conda as this might either be an older conda issue or there might be some conda setting that is causing this.

**Comment by ma-diroma** [comment]
I have installed it today, v.4.3.30

**Comment by marcus1487** [comment]
Current conda version is 4.4.10. Try a `conda update` first maybe? 

Sorry I haven't seen this issue before and can't re-create it, so I'm kind of just taking shots in the dark here.

**Comment by ma-diroma** [comment]
Solved.
Thank you

**Comment by nrp1980** [comment]
@ma-diroma...can you tell me how you resolved your installation issue?  I am having very similar problems, both with pip and conda attempts.  I am on 4.4.10; my conda error is slightly different:

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator
  - ont-tombo -> r-base=3.4.1 -> icu=54
  - ont-tombo -> r-base=3.4.1 -> ncurses=5.9

Many thanks to any who can advise!
