### ISSUE TITLE
How the canonical distribution are assigned to a model

### ISSUE THREAD

**Issue by LeilyR** [nanoporetech/tombo#260]
Hi, 
This could be a naive question but if I understood correctly tombo is an unsupervised learning method, so there is no need in training but what I am not so sure about is that how alternative models are computing the values for canonical distribution. Are these models (5mc,  6mc or the standard one ) have been initially trained on some data and there is basically no need to retrain or the canonical values are getting computed based on the seq2signal assignment in the re-squiggle. I have gone through the tutorial for the modified base detection but when for example you have used mean of canonical I am not sure when that has been computed. 
Best,
Leily

**Comment by marcus1487** [comment]
I am not sure I understand your question. The canonical model/kmer distributions are determined from a sample with only canonical bases. Alternative models do not model canonical bases, but only alternative bases in the context of other canonical bases. Each k-mer containing the modified base is modeled, but k-mers without modified bases are not included in alternative models. 

Does this help? If not could you be a bit more specific?

**Comment by LeilyR** [comment]
Hi Marcus, Thanks a lot for the response. So what I exactly want to know is that for example for an alternative model in robust LLR formula there is a scaling factor which is computed as `normSignal -(CanonicalMean+AltMean/2)`. How is the `CanonicalMean` calculated?

**Comment by marcus1487** [comment]
Yes. This is computed from the reference genome by taking the local k-mer sequence and looking up the computed expected level from the k-mer levels model.
