### ISSUE TITLE
tombo preprocess error

### ISSUE THREAD

**Issue by aman21392** [nanoporetech/tombo#263]
I used command-
tombo preprocess annotate_raw_with_fastqs --fast5-basedir ./single_fast5/ --fastq-filenames ./fastq_pass/FAM97142_pass_121130d2_*.fastq --processes 20 --overwrite

tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
with h5py.File(fast5_fn) as fast5_data:

0%|          | 0/1231437 [00:00<?, ?it/s]
  0%|          | 200/1231437 [00:00<21:32, 952.53it/s]
  0%|          | 400/1231437 [00:00<21:21, 960.54it/s]
  0%|          | 600/1231437 [00:00<17:45, 1155.09it/s]
  0%|          | 900/1231437 [00:00<14:11, 1445.89it/s]
  0%|          | 1300/1231437 [00:00<11:26, 1792.09it/s]
  0%|          | 1800/1231437 [00:00<09:25, 2173.56it/s]
  0%|          | 2300/1231437 [00:01<11:01, 1857.30it/s]
  0%|          | 2800/1231437 [00:01<09:48, 2088.27it/s]
  0%|          | 3300/1231437 [00:01<09:35, 2133.50it/s]
  0%|          | 3800/1231437 [00:01<09:25, 2169.14it/s]
  0%|          | 4300/1231437 [00:01<08:49, 2318.33it/s]
  0%|          | 4800/1231437 [00:02<09:13, 2217.14it/s]
  0%|          | 5300/1231437 [00:02<09:08, 2236.41it/s]
  0%|          | 5800/1231437 [00:02<10:07, 2018.31it/s]
  1%|          | 6300/1231437 [00:02<09:38, 2116.38it/s]
  1%|          | 6800/1231437 [00:03<09:51, 2070.28it/s]
  1%|          | 7300/1231437 [00:03<09:45, 2091.61it/s]
  1%|          | 7800/1231437 [00:03<09:39, 2110.59it/s]
  1%|          | 8300/1231437 [00:03<09:34, 2127.77it/s]
  1%|          | 8800/1231437 [00:04<09:16, 2197.84it/s]
  1%|          | 9300/1231437 [00:04<09:26, 2157.09it/s]
  1%|          | 9800/1231437 [00:04<09:23, 2169.38it/s]
  1%|          | 10300/1231437 [00:04<09:44, 2090.00it/s]
  1%|          | 10900/1231437 [00:05<09:23, 2166.34it/s]
  1%|          | 11500/1231437 [00:05<09:04, 2239.88it/s]
  1%|          | 12100/1231437 [00:05<09:08, 2223.14it/s]
  1%|          | 12700/1231437 [00:05<09:21, 2169.73it/s]
  1%|          | 13300/1231437 [00:05<09:05, 2232.89it/s]
  1%|          | 13900/1231437 [00:06<08:59, 2255.57it/s]
  1%|          | 14500/1231437 [00:06<09:03, 2240.94it/s]
  1%|          | 15100/1231437 [00:06<08:57, 2261.97it/s]
  1%|▏         | 15700/1231437 [00:06<09:00, 2248.37it/s]
  1%|▏         | 16300/1231437 [00:07<08:55, 2267.54it/s]
  1%|▏         | 16900/1231437 [00:07<09:05, 2225.06it/s]
  1%|▏         | 17500/1231437 [00:08<09:15, 2185.53it/s]
  1%|▏         | 18100/1231437 [00:08<09:10, 2204.24it/s]
please tell me it seems ok or something i will do .

**Comment by marcus1487** [comment]
This appears to be processing as expected. The warning about a change in the h5py package.

**Comment by marcus1487** [comment]
I've just pushed a fix to avoid this warning to the github repo.

**Comment by aman21392** [comment]
Thank you
