### ISSUE TITLE
Different Corrected Groups for Different fast5 Directories (model_sample_compare)

### ISSUE THREAD

**Issue by Chris-Kimmel** [nanoporetech/tombo#267]
Hi all,

### Setup

Suppose I have two directories of fast5 files. One directory contains fast5 files from IVT RNA. The other contains fast5 files from RNA that was harvested from cells. I would like to run `tombo detect_modifications model_sample_compare` to find modification sites in the harvested RNA by comparing the fast5 files from both directories.

### Question

The problem is, both of my fast5 directories have been resquiggled multiple times using the `--corrected-group` option. **I'd like to use a particular "corrected group" for the IVT-RNA control, and another "corrected group" for the harvested RNA.**

Is this possible?

Looking at the output of `tombo detect_modifications model_sample_compare --help`, it seems like the user can only enter one argument for the `--corrected-group` option. But that doesn't make sense, since the user supplies *two* fast5 directories.

**Comment by marcus1487** [comment]
It is unfortunately not possible to use different `--corrected-group` options in a single call to `tombo detect_modifications`. The `--corrected-group` option is intended to use different processing options and store the results without overwritting the re-squiggle results. Any set of options that are intended to be compared should be stored in the `--corrected-group` with the same name value. The `--corrected-group` option is not intended to be set to different values for different sets of FAST5 files. The separate base directories of files is intended as the separation in this case.

Please post if any further clarifications would be helpful.

**Comment by Chris-Kimmel** [comment]
Okay, thank you @marcus1487 . That answers my question. :)
