### ISSUE TITLE
Best practice for polishing genome before resquiggle?

### ISSUE THREAD

**Issue by zacksaud** [nanoporetech/tombo#270]
Hi,

In the Tombo manual, it states:
"Importantly, the reference sequence is assumed to be correct, so polishing to create a personalized reference may improve performance, particularly for a divergent sample or poorly assembled reference."

Is this referring to just polishing with the long reads (ie mapping the long reads and using Racon), or polishing with the long reads and using Medaka correction or the best polishing possible- ie first polishing with long reads, then Medaka, and then using Illumina reads with Pilon? 

I'd assume that polishing with short reads would remove indels, which I guess would be detrimental to aligning the ionic current data, am I correct in my line of thought? If so, what is best practice for polishing an assembly before running resquiggle in Tombo?

Many thanks in advance

Zack

**Comment by marcus1487** [comment]
The idea here is that the best modified base results will be obtained from a reference sequence that exactly matches the sequenced sample. Thus the goal is the most accurate reference sequence possible for a given sample. There are many pipelines and benchmarks available for a range of methods to perform this task. Our current recommendation for de novo assembly would be to run Flye, then racon, then medaka. See more details about this pipeline here: https://colab.research.google.com/github/epi2me-labs/tutorials/blob/master/Assembly_Tutorial.ipynb

**Comment by zacksaud** [comment]
Many thanks for this info, so it shouldn't be a problem to polish with Illuminareads/Pilon  before running requiggle.
Thank you
