### ISSUE TITLE
Where are the plots stored

### ISSUE THREAD

**Issue by MustafaElshani** [nanoporetech/tombo#271]
Apologies in advance if this is a newbie question.

I am trying to identify modified bases using the canonical sample comparison method (Control vs Treated) on native RNA samples.

1. Converted pre basecalled multifast5 to singlefast5 using ont_fast5_api
2. `tombo resquiggle --ignore-read-locks` for each of the singlefast5 with genecode.v34.transcripts.fa from Control and Treated,All went well
3. Ran `tombo detect_modifications level_sample_compare --multiprocess-region-size 500 --fast5-basedirs /path/to/Control/singlefast5 --alternate-fast5-basedirs  /path/to/Treated/singlefast5 --statistics-file-basename sample.level_compare_sample` It finished with 3 or so `File "<__array_function__ internals>", line 6, in concatenate` erros but continued to 100%
4. I persisted and continued with `tombo plot max_difference --fast5-basedirs --fast5-basedirs /path/to/Control/singlefast5 --alternate-fast5-basedirs --alternate-fast5-basedirs  /path/to/Treated/singlefast5 ` 
which ended up with 

`Parsing Tombo index file(s).
[12:42:50] Parsing Tombo index file(s).
[12:42:56] Getting largest mean signal differences.
Preparing plot data.
[08:22:23] Plotting.`

I am assuming it has plotted something but I can't seem to find a file. Where have a gone wrong? 
I am expecting to see base modification at end of PolyA tails, is this even mapped?

Any help would very much be appreciated

**Comment by marcus1487** [comment]
By default, the plots are stored in the current working directory. A different path can be specified via the `--pdf-filename` argument if an alternative output location is desired.
