### ISSUE TITLE
Conda's Tombo plot script fails

### ISSUE THREAD

**Issue by mmiladi** [nanoporetech/tombo#272]
Hi,

The conda installtion of Tombo in a clean environment fails due to the rpy2 version incompatibility, as it has been reported here: https://github.com/nanoporetech/tombo/issues/208

Downgrading the rpy2 dependencies with `conda install rpy2=2.9` solved the issue. I think the bioconda recipe needs to impose rpy2 < 3.0

Best,
-M

**Comment by marcus1487** [comment]
Addressed in bioconda: https://github.com/bioconda/bioconda-recipes/pull/23172
