### ISSUE TITLE
What is the right control for sample comaprison method? 

### ISSUE THREAD

**Issue by LeilyR** [nanoporetech/tombo#273]
Hi Marcus, May I ask if it is possible to run `tombo/sample comparison method` on direct RNA data with in vitro transcribed RNA from the GST sequence as spike-in (to be used as control)?

**Comment by marcus1487** [comment]
IVT is a reasonable control for a direct RNA sequencing sample, but this must be from the same reference as the native sample of interest. The signal attributed to the reference bases are compared at those positions. Thus a control from a different source/organism is not a valid control sample in the Tombo framework.

**Comment by LeilyR** [comment]
thanks a lot!

**Comment by LeilyR** [comment]
Hi Marcus,
May I ask if you would recommend using one ctrl for all the replicates or having a ctrl per replicate for tombo sample comparison mode.

**Comment by marcus1487** [comment]
As long as all replicates derive from the same reference sequence having one control for all replicates should not be an issue. If more replicates of the control are provided they would be treated as one sample for most analyses within Tombo.

**Comment by LeilyR** [comment]
Thank a million Marcus!
