### ISSUE TITLE
Per-read stats file structure, Python API

### ISSUE THREAD

**Issue by Chris-Kimmel** [nanoporetech/tombo#274]
Hi all,

I wrote a tool for my lab that converts `.tombo.per_read_stats` files into CSV files. The intended output is a table of _p_-values with a row for every read and a column for every nucleotide position.

I want to make sure I understand the HDF5 encoding used in `.tombo.per_read_stats` files. Is this right?

> * In a `.tombo.per_read_stats` file, there are three datasets in every block: `block_stats`, `read_ids`, and `read_id_vals`. The number of processors used by Tombo during `tombo detect_modifications` is the same as the number of blocks.
> * Every record in the dataset `block_stats` corresponds uniquely to one position on one read. Every position on every read is accounted for, except when the _p_-value there is not defined.
> * Suppose a record in the dataset `block_stats` has the value "pos: _x_, pval: _y_, read_id: _z_". Suppose also that the record in row _z_ of dataset `read_ids` is _w_, and the record in row _w_ of `read_id_vals` is _r_. Then nucleotide position _z_ on the read with read id _r_ was assigned _p_-value _y_.
> * Tombo numbers nucleotide positions the same way they are numbered on the reference FASTA used for resquiggling. That is, on the string of A's, C's, T's, and G's inside my reference FASTA, the 17th letter corresponds with what Tombo calls "position 17". In particular, the first letter on the reference FASTA string corresponds to Tombo's "position 1", and _not_ "position 0".

I'd be happy to clarify what I mean; I know what I just wrote is really opaque.

For context, all our lab's Tombo reads are of the same 9kb single-stranded RNA sequence. We're running `tombo detect_modifications model_sample_compare` without the multiprocess options, so our HDF5 file has only one statistic block. And we resquiggle to a reference genome.

I'm probably going to rewrite our tool to use the Tombo API instead of directly reading the HDF5 file, but for the short-term I'm just asking this so I can patch our tool and make sure we've been interpreting our data correctly.

Thanks,
Chris

**Comment by marcus1487** [comment]
There are several issues in the above description. I would strongly recommend using the Tombo API for this purpose as you note as this is documented and I believe the exact output you are requesting is directly accessible from the API. In particular see the `get_region_per_read_stats` function described [here in the docs](https://nanoporetech.github.io/tombo/tombo.html#tombo.tombo_stats.PerReadStats).

Docs on the per-read format can be found [here](https://nanoporetech.github.io/tombo/modified_base_detection.html#per-read-statistics-file-format). To briefly touch on the issues with the description in the issue:

- The number of blocks is not related to the number of processes used in processing, but instead is the number of regions.
- Every position on a read does not need to be contained in the block stats
- The statistic stored is not always a p-value, but can also be a log likelihood ratio (when using the alternative test)
- Block stats positions are 0-based not 1-based.

**Comment by Chris-Kimmel** [comment]
Thanks for the clarification. A few more questions about some of Tombo's Python API methods:

* `tombo_stats.PerReadStats.get_region_per_read_stats(reg)`. This method returns a record array with three columns: `pos`, `stat`, and `read_id`.
    * What exactly does the integer `pos` represent?
    * Suppose I resquiggled my fast5 files against a reference genome `mygenome.fasta`. When you open the `mygenome.fasta` in Notepad, you see one sequence `ACTGGATT...` after one identifier. Does `pos=1` correspond to the first letter (`A`) in the sequence from `mygenome.fasta` or the second letter (`C`)? Does this relationship depend on the `strand` attribute of the argument `reg` of `PerReadStats`?
* `tombo_helper.intervalData(self, chrm, start, end, strand=None, reg_id=None, reg_text='', reads=None, seq=None)`:
    * It would be nice if I could set `start=-infinity`, `end=+infinity` (or something along those lines) so as to make sure my program output contains every genomic position for which there is a test statistic. Can I achieve this by setting `start=None`, `end=None`?
    * Is the `strand` attribute of an `intervalData` object only relevant when the user is sequencing double-stranded nucleotides? What happens if I let the `strand` argument to of `tombo_helper.intervalData` constructor stay on its default value `None`? Does that have the same affect as `strand='+'`?

For context, here's some of my code:

```python
    ... # some argparse stuff

    import pandas as pd
    from tombo import tombo_helper, tombo_stats

    reg = tombo_helper.intervalData(
        chrm=args.chromosome,
        # TODO: fix start and end positions
        start=0,
        end=10**6,
        strand=args.strand,
    )

    prs_recarray = (
        tombo_stats.PerReadStats(args.prs_path)
        .get_region_per_read_stats(reg)
    )

    # The three operations below that involve 'stat_level' are just to delete
    # extraneous labelling information from the table before we export to CSV
    (
        pd.DataFrame(prs_recarray)
        .set_index(['read_id', 'pos'])
        .rename_axis('stat_level', axis=1)
        .unstack('pos')
        .stack('stat_level')
        .reset_index('stat_level', drop=True)
        .to_csv(args.output_path)
    )
```

**Comment by marcus1487** [comment]
Position represents the 0-based (meaning pos=1 is the second base in the reference) coordinate on the reference chromosome specified via the interval object. This does not depend upon the strand for the interval. 

This command does not work with start, end or strand set to None. Setting any of these values to None will results in unexpected behavior (likely no data returned, but haven't tested this). There are some tombo functions that allow strand to be None, but this function requires this attribute.

I am not sure what you mean by "double stranded-nucleotides". The strand attribute indicates to which strand the called read maps. Even RNA reads for example can map to either the positive of negative strand. Statistics are intentionally separated into positive and negative strands as the canonical bases are different on the forward and reverse strand and should thus likely be treated differently. There are some cases when opposite strand can be combined when biological information is taken into acount (e.g. CpG methylation).

I hope this helps sort out your use case.

**Comment by Chris-Kimmel** [comment]
Okay. This info was all very helpful. Thanks for explaining all this, Marcus.

**Comment by Chris-Kimmel** [comment]
For future reference, Tombo has a built-in script for this: https://github.com/nanoporetech/tombo/pull/176/ . I couldn't find the script in my installed code; maybe it's in the source but not in the packaged version. Not documented but looks useful.
