### ISSUE TITLE
What is the relationship between the base in Tombo event and the basecalled sequence?

### ISSUE THREAD

**Issue by PanZiwei** [nanoporetech/tombo#279]
Hi,
I had a question on the sequence information in the event after Tombo re-squiggle step. What is the relationship between the base in the Tombo event and the sequence information?

I thought that for the same read the base in the event should be the same as the sequence base called by Guppy because re-squiggle utilizes the raw signal and associated base calls to re-assign the raw signal to the reference sequence based on an expected current level model. However, when I compared these two sequences and found that they are different. It seems that they share some similarities, but the Tombo sequence is not 100% included in the Guppy sequence.

Here is what I have done:
1. Use Guppy to do the baseball and save the output in fast5 format. The nucleotide information result by Guppy is saved in `--Basecall_1D_001` Group in .fast5.
1. Extract the sequence from fastq in `--Basecall_1D_001` as **Guppy sequence**
![Screen Shot 2020-08-15 at 5 55 42 PM](https://user-images.githubusercontent.com/44417006/90322288-9467ce80-df20-11ea-8104-fd6bcfe318fc.png)
1. Re-squiggle the data with Tombo with the command below:
`tombo resquiggle path/to/fast5s/ genome.fasta --corrected-group RawGenomeCorrected_001 --basecall-group Basecall_1D_001 --overwrite`
The re-squiggle used the basecall information from Guppy and save the corrected result in `--RawGenomeCorrected_001` in .fast5
1. Extract the base information from Event in `--RawGenomeCorrected_001` and concatenate the sequence as the **Tombo sequence**
![Screen Shot 2020-08-15 at 5 33 48 PM](https://user-images.githubusercontent.com/44417006/90322058-86647e80-df1d-11ea-8e53-a21698327426.png)
1. Check the **Guppy sequence** and **Tombo sequence**.  You can easily tell that the two sequences are different in the snapshots above.

So, is it possible to explain more about the base information in the Tombo event?

Thank you so much for your help!

**Comment by BoredMa** [comment]
First of all, I am not the author. It's right you mentioned that
> re-squiggle utilizes the raw signal and associated base calls to re-assign the raw signal to the reference sequence based on an expected current level model.

but the sequence in events should be consistent with the sequence of reference(not exactly the same ), not the basecalled sequence. you know the basecalled reads are used to mapping to reference(minimap2), giving the information where signals should be located.

The above is only my opinion.

**Comment by Chris-Kimmel** [comment]
I'm not an expert on Tombo, but this is my understanding:

When you run `tombo resquiggle`, Tombo does not reference the FASTQ HDF5 dataset _at all_. The resquiggle algorithm relies only on (1) raw current-level measurements from the fast5 file and (2) the reference sequence file that you provide to the `tombo resquiggle` command.

If you are assembling an unknown genome from nanopore sequencing data, you would obtain this reference sequence by aggregating information from all the FASTQ files in a separate step.

Try performing a sequence alignment between your "Tombo sequence" and your reference sequence - when I did this, our Tombo sequence was a perfect subsequence of our reference sequence.

Hope this helps,
Chris

**Comment by PanZiwei** [comment]
> First of all, I am not the author. It's right you mentioned that
> 
> > re-squiggle utilizes the raw signal and associated base calls to re-assign the raw signal to the reference sequence based on an expected current level model.
> 
> but the sequence in events should be consistent with the sequence of reference(not exactly the same ), not the basecalled sequence. you know the basecalled reads are used to mapping to reference(minimap2), giving the information where signals should be located.
> 
> The above is only my opinion.

Hi,
Thanks for the discussion. Are you suggesting that sequence in the event and basecalled sequence may map to a different location of reference, even if the sequence are for the same read?

Thanks!

**Comment by PanZiwei** [comment]
> I'm not an expert on Tombo, but this is my understanding:
> 
> When you run `tombo resquiggle`, Tombo does not reference the FASTQ HDF5 dataset _at all_. The resquiggle algorithm relies only on (1) raw current-level measurements from the fast5 file and (2) the reference sequence file that you provide to the `tombo resquiggle` command.
> 
> If you are assembling an unknown genome from nanopore sequencing data, you would obtain this reference sequence by aggregating information from all the FASTQ files in a separate step.
> 
> Try performing a sequence alignment between your "Tombo sequence" and your reference sequence - when I did this, our Tombo sequence was a perfect subsequence of our reference sequence.
> 
> Hope this helps,
> Chris

Hi Chris,
The re-squiggle requires raw read FAST5 files with basecalls as the input(you have to assign the basecall group, see command below), and the basecalls group is obtained from Guppy, I thought they should be still relevant?
```
tombo resquiggle path/to/fast5s/ genome.fasta --corrected-group path/to/correctedGroup --basecall-group path/to/basecallGroup --overwrite 
```

**Comment by BoredMa** [comment]
> > First of all, I am not the author. It's right you mentioned that
> > > re-squiggle utilizes the raw signal and associated base calls to re-assign the raw signal to the reference sequence based on an expected current level model.
> > 
> > 
> > but the sequence in events should be consistent with the sequence of reference(not exactly the same ), not the basecalled sequence. you know the basecalled reads are used to mapping to reference(minimap2), giving the information where signals should be located.
> > The above is only my opinion.
> 
> Hi,
> Thanks for the discussion. Are you suggesting that sequence in the event and basecalled sequence may map to a different location of reference, even if the sequence are for the same read?
> 
> Thanks!

No, The truth is Tombo uses basecalled reads to decide where signals should be mapped to(maybe the only function of basecalled reads), then applies DTW algorithm to get the best aligning sequence pairs between signals and reference. 

when I say
>the sequence in events should be consistent with the sequence of reference(not exactly the same )

what I actually mean is the sequence should be the same with the sequence of reference at the most time, but not absolutely in theory (some events are unmapped to reference, I am not sure how Tombo handles unmapped events, but Nanopolish still keeps the unmapped events)

**Comment by PanZiwei** [comment]
> > > First of all, I am not the author. It's right you mentioned that
> > > > re-squiggle utilizes the raw signal and associated base calls to re-assign the raw signal to the reference sequence based on an expected current level model.
> > > 
> > > 
> > > but the sequence in events should be consistent with the sequence of reference(not exactly the same ), not the basecalled sequence. you know the basecalled reads are used to mapping to reference(minimap2), giving the information where signals should be located.
> > > The above is only my opinion.
> > 
> > 
> > Hi,
> > Thanks for the discussion. Are you suggesting that sequence in the event and basecalled sequence may map to a different location of reference, even if the sequence are for the same read?
> > Thanks!
> 
> No, The truth is Tombo uses basecalled reads to decide where signals should be mapped to(maybe the only function of basecalled reads), then applies DTW algorithm to get the best aligning sequence pairs between signals and reference.
> 
> when I say
> 
> > the sequence in events should be consistent with the sequence of reference(not exactly the same )
> 
> what I actually mean is the sequence should be the same with the sequence of reference at the most time, but not absolutely in theory (some events are unmapped to reference, I am not sure how Tombo handles unmapped events, but Nanopolish still keeps the unmapped events)

Hi,
Thank you so much for the explanation! Correct me if I’m wrong in the following statement:

Based on your description that the re-squiggle will: 1. Use basecalled sequence information from Guppy to map the read to genome reference by Minimap2 2. Match the raw signals to the sequence.

In this case, the sequence in tombo event is a region of genome reference where the read is aligned to.

Also, I am not sure whether Tombo discards the unmapped ones or not... But I think Tombo has several types for the unmapped ones in the re-squiggle step(See the example of my re-squiggle result).

```
[11:43:52] Final unsuccessful reads summary (6.0% reads unsuccessfully processed; 12 total reads):
     3.5% (      7 reads) : Read event to sequence alignment extends beyond bandwidth                       
     2.0% (      4 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`) 
     0.5% (      1 reads) : Reference mapping contains non-canonical bases (transcriptome reference cannot contain U bases)
[11:43:53] Saving Tombo reads index to file.
```

**Comment by Chris-Kimmel** [comment]
> Hi Chris,
> The re-squiggle requires raw read FAST5 files with basecalls as the input(you have to assign the basecall group, see command below), and the basecalls group is obtained from Guppy, I thought they should be still relevant?
> 
> `tombo resquiggle path/to/fast5s/ genome.fasta --corrected-group RawGenomeCorrected_001 --basecall-group Basecall_1D_001 --overwrite`

Yep. I was wrong. I agree with @BoredMa:

> The truth is Tombo uses basecalled reads to decide where signals should be mapped to(maybe the only function of basecalled reads)

It seems @BoredMa and I are in agreement that a sequence from your Fast5 file `events` table should align better with your reference sequence than your fastQ sequence.

**Comment by BoredMa** [comment]
> Hi @BoredMa,
> Thank you so much for the explanation! Correct me if I’m wrong in the following statement:
> 
> Based on your description that the re-squiggle will: 1. Use basecalled sequence information from Guppy to map the read to genome reference by Minimap2 2. Match the raw signals to the sequence.
> 
> In this case, the sequence in tombo event is a region of genome reference where the read is aligned to.
> 
> Also, I am not sure whether Tombo discards the unmapped ones or not... But I think Tombo has several types for the unmapped ones in the re-squiggle step(See the example of my re-squiggle result).
> 
> ```
> [11:43:52] Final unsuccessful reads summary (6.0% reads unsuccessfully processed; 12 total reads):
>      3.5% (      7 reads) : Read event to sequence alignment extends beyond bandwidth                       
>      2.0% (      4 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`) 
>      0.5% (      1 reads) : Reference mapping contains non-canonical bases (transcriptome reference cannot contain U bases)
> [11:43:53] Saving Tombo reads index to file.
> ```

Yes, you got me exactly.

**Comment by marcus1487** [comment]
Hi All,

A couple of clarifications/confirmations on the discussion here. The basecalled sequence is used to map to the provided reference. The basecalls are indeed then ignored and the section of reference sequence is used going forward in the resquiggle algorithm. The k-mer model is then applied to the extracted reference sequence. Tombo segments the raw signal and performs DTW to assign the segmented signal to the reference expected levels. The result of this is stored in the Tombo events table.

One point of clarification is that the Tombo events table will always exactly match a stretch of reference sequence. Tombo allows gaps in the initial DTW when using segmented signal, but an additional DTW step against the raw signal is applied to fill these gaps. Thus there are no skipped reference bases and each reference base is assigned a stretch of signal (aka event). There are a number of checks on this process to ensure the signal mapping results are accurate (e.g. the `Read event to sequence alignment extends beyond bandwidth` and `Poor raw to expected signal matching (revert with tombo filter clear_filters)` errors).

**Comment by PanZiwei** [comment]
> Hi All,
> 
> A couple of clarifications/confirmations on the discussion here. The basecalled sequence is used to map to the provided reference. The basecalls are indeed then ignored and the section of reference sequence is used going forward in the resquiggle algorithm. The k-mer model is then applied to the extracted reference sequence. Tombo segments the raw signal and performs DTW to assign the segmented signal to the reference expected levels. The result of this is stored in the Tombo events table.
> 
> One point of clarification is that the Tombo events table will always exactly match a stretch of reference sequence. Tombo allows gaps in the initial DTW when using segmented signal, but an additional DTW step against the raw signal is applied to fill these gaps. Thus there are no skipped reference bases and each reference base is assigned a stretch of signal (aka event). There are a number of checks on this process to ensure the signal mapping results are accurate (e.g. the `Read event to sequence alignment extends beyond bandwidth` and `Poor raw to expected signal matching (revert with tombo filter clear_filters)` errors).

Hi @marcus1487 ,
I found that in some reads, base information concatenated from Tombo event are **NOT** in the reference genome, even though I provide the same genome(format `genome.fasta`) in the re-squiggle step. However, according to your reply before, I think the Tombo events should be exactly the subset of the genome reference. Do you have an idea on this problem?

Here is the code that I used for comparison:
```
fast5read = h5py.File(test_file, mode='r') 
event = fast5read['/Analyses/RawGenomeCorrected_001/BaseCalled_template/Events']
seq += str([x.decode("UTF-8") for x in event['base']])
reference = SeqIO.to_dict(SeqIO.parse(`genome species name.fasta`, "fasta")) 
seq in reference['genome species name'].seq
```

`test_file` is the location for the specific `.fast5` file. I simply tried to use command `seq in reference` in python for checking and some results are FALSE while some are TRUE.

Thank you so much for your help!

**Comment by marcus1487** [comment]
Reads can map to the reverse strand. The stored read sequence should always exactly match the reference sequence either on the forward or reverse complement strand. This is noted in the Alignment group stored within the Tombo Analysis group in the FAST5 file.
