### ISSUE TITLE
Resquiggling algorithm and dwell times of 6

### ISSUE THREAD

**Issue by Chris-Kimmel** [nanoporetech/tombo#280]
Hi!

I extracted dwell times from a Tombo fast5 file using the Python API function `tombo.tombo_helper.get_single_slot_genome_centric`.¹

A lot of our dwell times equal "6". Is this is an artifact of some default in the resquiggling algorithm.

![quick_hist(1)](https://user-images.githubusercontent.com/59748593/90431642-5b059f00-e097-11ea-9607-1d990eca6c0e.png)

¹All our strands are in the "+" orientation, so `tombo.tombo_helper.get_single_slot_genome_centric` [is the same as](https://github.com/nanoporetech/tombo/blob/7473afe6e023bf37e7e1f0d7e5f973a1318b888a/tombo/tombo_helper.py#L1649) `tombo.tombo_helper.get_single_slot_`**`read`**`_centric`. Guidance on when to use one or the other would be helpful. (I already confirmed that our data isn't backwards using the `reads` column of the fast5 `events` table.)

Edit: We're using RNA.

**Comment by Chris-Kimmel** [comment]
I just found the default segmentation parameters in the Tombo source code:
* running_stat_width = 12
* min_obs_per_base = 6
* raw_min_obs_per_base = 2
* mean_obs_per_event = 15

Clearly this explains the peaks at 2, 6, and 12 in the histogram I just posted.

Tombo source links:
* https://github.com/nanoporetech/tombo/blob/7473afe6e023bf37e7e1f0d7e5f973a1318b888a/tombo/_default_parameters.py#L29-L37
* https://github.com/nanoporetech/tombo/blob/7473afe6e023bf37e7e1f0d7e5f973a1318b888a/tombo/tombo_stats.py#L1540-L1542
* https://github.com/nanoporetech/tombo/blob/13a506da63f19d65913f07ec90534724e578f69d/tombo/resquiggle.py#L2063-L2068

**Comment by marcus1487** [comment]
Note that these values are also accessible from the command line help. Run `tombo resquiggle --print-advanced-arguments` and see the `--segmentation-parameters` help text.

**Comment by Chris-Kimmel** [comment]
> 
> 
> Note that these values are also accessible from the command line help. Run `tombo resquiggle --print-advanced-arguments` and see the `--segmentation-parameters` help text.

Ooh thank you. That's a little more straightforward. :)
