### ISSUE TITLE
Information about Tombo 

### ISSUE THREAD

**Issue by lucio-cyber** [nanoporetech/tombo#282]
Hi Marcus, I'm Lucio, I'm trying to launch tombo's resquiggle and then use deepsignal for DNA. I'd like to better understand what “- - corrected-group RawGenomeCorrected_001 - -basecalling-group Basecall_1D_000” mean and what they are for and if whether they are necessary or not. Eventually it would help me to understand also based on what I choose them or if they are standard.
Also I wanted to ask you if before resquiggle it was necessary to index my genome first with bwa. Are new files created after resquiggle ?
Best Regards

**Comment by marcus1487** [comment]
Tombo writes information back to the single read FAST5 files. The `--basecalling-group` indicates from where the basecalls should be extracted. The default is the standard location Guppy/MinKNOW store the basecalling output. If the basecaller is run multiple times on the same files then an alternative value may be required (i.e. `Basecall_1D_001`). The `--corrected-group` is the output location for Tombo. This should only really be changed if one is testing different settings and would like to save all results for downstream processing instead of overwriting old results. This default value is the default input value for all other Tombo commands, so makes sense to leave as the default in most all settings. [Here are the relevant docs](https://nanoporetech.github.io/tombo/resquiggle.html#tombo-fast5-format).

Tombo uses minimap2, so no BWA index files are necessary. Tombo will also accept a minimap2 index file as input.

**Comment by lucio-cyber** [comment]
Another question, if by chance I don't set the - - corrected-group is it wrong? In case what would happen, would they be overwritten on fast5 and therefore no longer usable for a second analysis?

**Comment by marcus1487** [comment]
The `--corrected-group` defaults to `RawGenomeCorrected_001`. Not setting the option uses this default. Results will only be overwritten if the `--overwrite` flag is set and only results in the specified `--corrected-group` would be overwritten.

**Comment by lucio-cyber** [comment]
Yes I have set “- - overwrite” without specifying the - - corrected-group, it is right to do so. If you do overwrite, you can't use them for a second analysis and then specify the output?

**Comment by marcus1487** [comment]
If `--corrected-group` is not set, this is the exact same as setting `--corrected-group RawGenomeCorrected_001 `. Setting the `-overwrite` flag overwrites whatever was in the `--corrected-group` slot. Thus those previous results are lost as they have been overwritten.

**Comment by lucio-cyber** [comment]
So it still creates me RawGenomeCorrected and would save it to me in Fast5?

**Comment by marcus1487** [comment]
Yes. If `--corrected-group` is not set, this is the exact same as setting `--corrected-group RawGenomeCorrected_001`.

**Comment by lucio-cyber** [comment]
Thank you so much for helping me.
Best Regards

**Comment by kwonej0617** [comment]
@marcus1487 

> Tombo writes information back to the single read FAST5 files. The `--basecalling-group` indicates from where the basecalls should be extracted. The default is the standard location Guppy/MinKNOW store the basecalling output. If the basecaller is run multiple times on the same files then an alternative value may be required (i.e. `Basecall_1D_001`). The `--corrected-group` is the output location for Tombo. This should only really be changed if one is testing different settings and would like to save all results for downstream processing instead of overwriting old results. This default value is the default input value for all other Tombo commands, so makes sense to leave as the default in most all settings. [Here are the relevant docs](https://nanoporetech.github.io/tombo/resquiggle.html#tombo-fast5-format).
> 
Based on what you explained, it looks like RawGenomeCorrected_001 is a kind of output file from --corrected-group. I am not sure where to find the file. Could you please give me the information on the file location?

Also, even though I didn't specify --corrected-group in resquiggle step, was RawGenomeCorrected_001 generated by default? Or, should I have specified at least --corrected-group  to get RawGenomeCorrected_001?

Finally, can I run resquiggle multiple times with the same fast5 dataset? The first resquiggle was running successfully. However, when I run the second time with some options added, I got the following errors. **Reads do not to contain basecalls. Check --basecall-group option if basecalls are stored in non-standard location or use `tombo preprocess annotate_raw_with_fastqs` to add basecalls from FASTQ files to raw FAST5 files**
My resquiggle command like was `tombo resquiggle --rna --processes 40 --corrected-group RawGenomeCorrected_001 --basecall-group Basecall_1D_001 --include-event-stdev --overwrite --ignore-read-locks ${wt_fast5} ${ref}`

I am looking forward to hearing from you.
