### ISSUE TITLE
Are start position for mapped chromosome and start position for event both 0-based?

### ISSUE THREAD

**Issue by PanZiwei** [nanoporetech/tombo#287]
To whom it may concern,
I am using the re-squiggle step in Tombo and the results are saved in `Analyses/RawGenomeCorrected_001` in fast5 file. Now I am trying to use the base location in a read and the read location in a genome to get the 0-based position of all the "A" in the chromosome, and here is what I have done: 

1. For each read, I extract the mapped start location in `mapped_start` attribution. 
```
fast5read = h5py.File(test_file, mode='r') 
mapped_start_in_chromosome = fast5read[/Analyses/RawGenomeCorrected_001/BaseCalled_template/Alignment].attrs['mapped_start']
```
Is the start attribute the 0-based mapping from `minimap2`?

2. Find the A location in the read from in the Tombo event(`event['base']`):
```
event = fast5read['/Analyses/RawGenomeCorrected_001/BaseCalled_template/Events']
seq += str([x.decode("UTF-8") for x in event['base']])
A_in_read = [m.start() for m in re.finditer('A', seq)] 
```
Is the start attribute in the event 0-based also?

3. For a specific A in the genome, which one is correct? Will the A location be 0-based also?
```
for i in A_in_read:
    A_in_reference = mapped_start_in_chromosome + i 
```
or 
```
for i in A_in_read:
    A_location_in_reference = mapped_start_in_chromosome + i - 1
```

Thank you so much for your help!

**Comment by marcus1487** [comment]
Both of these coordinates are 0-based, but be aware that coordinates must be flipped for reverse strand mapping reads. The `event['base']` vector is read-centric. So if a read maps to the reverse strand the last event/base will be at `mapped_start_in_chromosome`.
