### ISSUE TITLE
error when running plot_most_significant

### ISSUE THREAD

**Issue by ma-diroma** [nanoporetech/tombo#29]
Hi Marcus,

I am trying to plot most significant regions for an RNA sample, aligned to the transcriptome.

`tombo plot_most_significant --fast5-basedirs myfast5_dir --statistics-filename sample.tombo.stats --plot-standard-model`

I got this error

```
******************** ERROR ********************
        Must have rpy2, R and R package ggplot2 installed in order to plot. If these packages are installed, run:
                `python -c "import rpy2.robjects; from rpy2.robjects.packages import importr; importr(str('ggplot2'));"`
         to see installation issues.
```

I checked if rpy2 and ggplot2 were installed, and they were.
When running 

```
python2.7 -c "import rpy2.robjects; from rpy2.robjects.packages import importr; 
importr(str('ggplot2'));"
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/madiroma/.local/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "/home/madiroma/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: /home/madiroma/bin/anaconda2/bin/../lib/libreadline.so.6: undefined symbol: PC
```
Do you have any idea about this issue?
Thank you,

Maria Angela

**Comment by JohnUrban** [comment]
Take a look at #27 - I just went through this.

Try this:
```
python -m rpy2.tests
```

Look for the lines that say something like:
```
- built against R version: 3-4.1--72865
- running linked to R version: R version 3.3.1 (2016-06-21)
```

It should say the same version.

To see where R is coming from, try:
```
which R
```
If it doesn't say the R version it was built under, then you're going to need to get that R out of your path.

Try:
```
echo $PATH 
```

You might see that wrong version of R is in front of the right version of R in the PATH.

**Comment by JohnUrban** [comment]
It might help to start with a fresh new installation by following the install instructions toward the end of #27 as well:
e.g. if Linux:
```
wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh
bash Anaconda3-5.0.1-Linux-x86_64.sh
#enter
#yes+enter
#~/data/software/conda/anaconda3 + enter

conda update --all

conda config --add channels r
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda

conda create -n tombo python=3.6
conda activate tombo 
conda install -c bioconda ont-tombo
```

Then try:
```
python -c "import rpy2.robjects; from rpy2.robjects.packages import importr"
```
and
```
python -m rpy2.tests
```
...and the other stuff in my previous post.

**Comment by marcus1487** [comment]
Thanks @JohnUrban ! @ma-diroma do let us know if this solves your issues.

**Comment by ma-diroma** [comment]
Thanks for your help, but I am getting different errors...
I followed all the instructions, everything is ok till

```
python -c "import rpy2.robjects; from rpy2.robjects.packages import importr"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/madiroma/.local/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 20, in <module>
    from rpy2.robjects.vectors import (BoolVector,
  File "/home/madiroma/.local/lib/python3.6/site-packages/rpy2/robjects/vectors.py", line 9, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
```
I installed jinja2 with conda. Now 
```
python -c "import rpy2.robjects; from rpy2.robjects.packages import importr"
Segmentation fault (core dumped)
```

```
python -m rpy2.tests
rpy2 version: 2.9.2
- built against R version: 3-4.1--72865
- running linked to R version: R version 3.4.1 (2017-06-30)
Segmentation fault (core dumped)
```
When I run plot_most_significant

```
Loading statistics from file.
Parsing tombo index file(s).
Traceback (most recent call last):
  File "/home/madiroma/bin/anaconda3/envs/tombo/bin/tombo", line 6, in <module>
    sys.exit(tombo.__main__.main())
  File "/home/madiroma/bin/anaconda3/envs/tombo/lib/python3.6/site-packages/tombo/__main__.py", line 180, in main
    plot_commands.plot_main(args)
  File "/home/madiroma/bin/anaconda3/envs/tombo/lib/python3.6/site-packages/tombo/plot_commands.py", line 2129, in plot_main
    plot_most_signif(*base_args, **kwargs)
  File "/home/madiroma/bin/anaconda3/envs/tombo/lib/python3.6/site-packages/tombo/plot_commands.py", line 1770, in plot_most_signif
    f5_dirs1, corrected_group, basecall_subgroups)
  File "/home/madiroma/bin/anaconda3/envs/tombo/lib/python3.6/site-packages/tombo/tombo_helper.py", line 819, in parse_fast5s
    new_corr_grp))
  File "/home/madiroma/bin/anaconda3/envs/tombo/lib/python3.6/site-packages/tombo/tombo_helper.py", line 771, in parse_fast5s_w_index
    index_data = pickle.load(index_fp)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
```

**Comment by marcus1487** [comment]
Something in your path is mixing up the packages being used. Note the beginning of your tombo path in the first command (`/home/madiroma/.local`) and the second command (`/home/madiroma/bin/`). This is somehow resulting in an index created with python2 and then you are trying to read that index in with a python3 installation on tombo. This creates some invalid characters for python3. You generally want to point to the same python version for all processing.

**Comment by ma-diroma** [comment]
I am sorry, forget the first tombo command. I have completely reinstalled it following the instructions by @JohnUrban. Now I am using python3, and all the errors point to python3.6 site_packages, as you can see in my previous post.

which python
~/bin/anaconda3/envs/tombo/bin/python
which R
~/bin/anaconda3/envs/tombo/bin/R

**Comment by marcus1487** [comment]
So you re-run the `resquiggle` and `test_significance` commands on this set of runs after conversion to python3 and then you are still getting the `UnicodeDecodeError` from the `plot_most_significant` command?

**Comment by ma-diroma** [comment]
I re-run the resquiggle and test_significance with tombo (python 3). No UnicodeDecodeError but

```
******************** ERROR ********************
        No reads in any selected regions.
```

even if modified bases are in my out.fraction_modified_reads.(plus/minus).wig files...

**Comment by marcus1487** [comment]
This likely indicates that there are no valid tested locations from your test_significance command. Check the wiggle output from the statistics file (fraction wiggle type) and consider lowering the coverage threshold in you testing command.

**Comment by ma-diroma** [comment]
I used default values in `test_significance` (`--fishers-method-context 1`, `--minimum-test-reads 1`) and I lowered the `--single-read-threshold` to 0.1, but unfortunately no plot.
Do you think changing parameters in the `resquiggle` command, such as `--segmentation-parameters`, `--signal-align-parameters`, `--outlier-threshold` and `--obs-per-base-filter`, could help?
I have to say that when I (wrongly) aligned my RNA sample to the genome, rather than thanscriptome, the plot_most_significant function worked well.

**Comment by marcus1487** [comment]
Just to check that this is not something else, do you see valid values when you run ‘write_wiggles’ with the ‘—wiggle-types fraction’ argument passing the same statistics file provided here?

As for adjusting the re-squiggle parameters, I would not expect that to help much in this setting unless there is a particular error mode causing many reads to fail.

**Comment by ma-diroma** [comment]
Yes, there are valid values ranging from 0.0 to 1.0.

**Comment by marcus1487** [comment]
Sorry for all the questions, but you are passing exactly the same read paths to the ‘resquiggle’, ‘test_significance’ and plotting commands correct?

**Comment by ma-diroma** [comment]
Yes, it's always the same fast5 folder.

**Comment by marcus1487** [comment]
This is very weird. I cannot see how this would be happening. The one thought I have is that if you are processing the reads using several different references (genome, fasta or other reference) the results are overwritten each time, so this might be causing the clash of the sites identified from the statistics file and the reads.

To nail down where this is coming from in your case would you mind running these commands:

```
from tombo import tombo_stats as ts
from tombo import tombo_helper as th

# adjust these to match your run
stats_fn=''
f5_dirs=['',]

corrected_group='RawGenomeCorrected_000'
basecall_subgroups=['BaseCalled_template',]

all_stats, stat_type = ts.parse_stats(stats_fn)
plot_intervals = ts.get_most_signif_regions(all_stats, 5, 1)
raw_read_coverage = th.parse_fast5s(f5_dirs, corrected_group, basecall_subgroups)
all_reg_data = th.get_region_reads(plot_intervals, raw_read_coverage)
print(plot_intervals)
print(all_reg_data)

```
Hopefully this will help identify why your command is failing. Thanks!

**Comment by JohnUrban** [comment]
Apologies for eavesdropping here -- and apologies for this potentially so-obvious-it-is-insulting question -- but are you using ```--overwrite``` with your ```tombo resquiggle``` command @ma-diroma ? It could be helpful just to see the exact resquiggle command (and others) you're using.

**Comment by marcus1487** [comment]
Does the plot command work without the `--plot-standard-model` option?

**Comment by ma-diroma** [comment]
No, I have already tried. The error is the same

**Comment by marcus1487** [comment]
I want to make sure your read coverage chromosome names match those from your stats regions. Can you show me the result from the previous code of the code printing `list(raw_read_coverage.keys())[:3]`. I'm thinking something is possibly broken in the fasta parsing for this case. Thanks!

**Comment by ma-diroma** [comment]
>>> list(raw_read_coverage.keys())[:3]
[('ENST00000242057.8_1|ENSG00000106546.12_2|OTTHUMG00000149967.3_2|OTTHUMT00000314620.2_1|AHR-201|AHR|6276|protein_coding|', '+'), ('ENST00000374242.8_1|ENSG00000148153.13_2|OTTHUMG00000020509.3_2|OTTHUMT00000053692.2_1|INIP-203|INIP|4233|protein_coding|', '+'), ('ENST00000489671.5_2|ENSG00000114126.17_4|OTTHUMG00000164975.4_4|OTTHUMT00000353294.5_2|TFDP2-215|TFDP2|9857|protein_coding|', '+')]

**Comment by marcus1487** [comment]
This appears to be our culprit!

I am storing the chromosome names as a length-32 string (arbitrarily chosen length) in the statistics file in order to save space and not store variable length strings in an HDF5 dataset. This is causing the names to clash here since the full chromosome names are not the same. The long fix for this involves removing the chromosome and strand from this table as they are the same over each whole table, but this involves fixing the interface to this statistics table throughout the code, so this will likely just be included in the next release (and has been logged internally). I think I'll close this issue and open a new one with this specific point since this issue is a bit of a combination of a couple other install issues as well.

As a quick fix for now you should be able to trim your reference FASTA names down to <32 characters. It looks like replacing vertical bar characters to spaces might do the trick. Thank you for helping to track this down!

**Comment by ma-diroma** [comment]
Great! Glad to have helped you.
Thanks for your help, I will do as you suggest with my fasta file.

Best wishes,
Maria Angela

**Comment by alexredon** [comment]
Hi !
I have a similar error when I am trying to plot most significant regions : 

`tombo plot most_significant --fast5-basedirs my_fastDir --statistics-filename test.tombo.stats

******************** ERROR ********************
	R and rpy2 must be linked during installation.
		Run python -c "from rpy2 import robjects; from rpy2.robjects.packages import importr to identify installation linking issues.
		If using conda, check that R and rpy2 are installed from the same channel with conda list | grep "r-base\|rpy2" (last columns should match).`

When running:

`python2.7 -c "import rpy2.robjects; from rpy2.robjects.packages import importr"`

I get this : 

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/rinterface/__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: dlopen(/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/rinterface/_rinterface.so, 2): Library not loaded: @rpath/libintl.9.dylib
  Referenced from: /Users/black/anaconda3/envs/nanopore/lib/R/lib/libR.dylib
  Reason: image not found`

and when running : 

`python -m rpy2.tests`

I get : 

`Traceback (most recent call last):
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/tests.py", line 23, in <module>
    import rpy2.tests_rpy_classic
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/tests_rpy_classic.py", line 3, in <module>
    import rpy2.rpy_classic as rpy
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/rpy_classic.py", line 5, in <module>
    import rpy2.rinterface as ri
  File "/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/rinterface/__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: dlopen(/Users/black/anaconda3/envs/nanopore/lib/python2.7/site-packages/rpy2/rinterface/_rinterface.so, 2): Library not loaded: @rpath/libintl.9.dylib
  Referenced from: /Users/black/anaconda3/envs/nanopore/lib/R/lib/libR.dylib
  Reason: image not found`

conda list : 

` packages in environment at /Users/black/anaconda3/envs/nanopore:

Name                    Version                   Build  Channel
_r-mutex                  1.0.0               anacondar_1  
basecRAWller              0.1                       <pip>
blas                      1.0                         mkl  
bwa                       0.7.15                        1    bioconda
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2018.03.07                    0  
cairo                     1.14.8                        0  
certifi                   2018.4.16                py27_0  
curl                      7.60.0               ha441bb4_0  
cython                    0.28.3           py27h1de35cc_0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
fribidi                   1.0.4                h1de35cc_0  
funcsigs                  1.0.2                     <pip>
future                    0.16.0                   py27_1  
gettext                   0.19.8.1             hb0f4f8b_2  
glib                      2.50.2                        1  
graphite2                 1.3.11               h2098e52_2  
gsl                       2.4                  h1de35cc_4  
h5py                      2.7.0            py27h217cc45_1  
harfbuzz                  0.9.39                        2  
hdf5                      1.10.1               ha036c08_1  
icu                       54.1                          0  
intel-openmp              2018.0.3                      0  
jpeg                      9b                   he5867d9_2  
libcurl                   7.60.0               hf30b1f0_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libdeflate                0.8                           0    bioconda
libffi                    3.2.1                h475c297_4  
libgcc                    4.8.5               hdbeacc1_10  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.14                          0  
libpng                    1.6.34               he12f830_0  
libssh2                   1.8.0                h322a93b_4  
libtiff                   4.0.9                hcb84e12_1  
libxml2                   2.9.4                         0  
linecache2                1.0.0            py27hdcabdf0_0  
mappy                     2.10                     py27_1    bioconda
mkl                       2018.0.3                      1  
mkl_fft                   1.0.1            py27h917ab60_0  
mkl_random                1.0.1            py27h78cc56f_0  
mock                      2.0.0                     <pip>
ncurses                   5.9                          10  
numpy                     1.14.5           py27h9bb19eb_0  
numpy-base                1.14.5           py27ha9ae307_0  
ont-tombo                 1.3             py27r341h24bf2e0_1    bioconda
openjdk                   8.0.121                       1  
openssl                   1.0.2o               h26aff7b_0  
pango                     1.40.3                        1  
pbr                       4.0.2                     <pip>
pcre                      8.39                          1  
picard                    2.18.4                   py27_0    bioconda
pip                       10.0.1                   py27_0  
pixman                    0.34.0               hca0a616_3  
protobuf                  3.1.0                     <pip>
pyfaidx                   0.5.3                    py27_0    bioconda
python                    2.7.3                         5  
r-base                    3.4.1                         0  
r-colorspace              1.3_2                  r3.4.1_0  
r-dichromat               2.0_0                  r3.4.1_2  
r-digest                  0.6.12                 r3.4.1_0  
r-ggplot2                 2.2.1                  r3.4.1_0  
r-gridextra               2.2.1                  r3.4.1_0  
r-gtable                  0.2.0                  r3.4.1_0  
r-labeling                0.3                    r3.4.1_2  
r-lazyeval                0.2.0                  r3.4.1_0  
r-magrittr                1.5                    r3.4.1_2  
r-mass                    7.3_47                 r3.4.1_0  
r-munsell                 0.4.3                  r3.4.1_0  
r-plyr                    1.8.4                  r3.4.1_0  
r-rcolorbrewer            1.1_2                  r3.4.1_3  
r-rcpp                    0.12.11                r3.4.1_0  
r-reshape2                1.4.2                  r3.4.1_0  
r-rlang                   0.1.1                  r3.4.1_0  
r-scales                  0.4.1                  r3.4.1_0  
r-stringi                 1.1.5                  r3.4.1_0  
r-stringr                 1.2.0                  r3.4.1_0  
r-tibble                  1.3.3                  r3.4.1_0  
readline                  6.2                           2  
rpy2                      2.8.6              py27r3.4.1_2  
samtools                  1.8                           3    bioconda
scipy                     1.1.0            py27hcaad992_0  
setuptools                39.2.0                   py27_0  
singledispatch            3.4.0.3          py27he22c18d_0  
six                       1.11.0           py27h7252ba3_1  
sqlite                    3.13.0                        0  
tensorflow                0.12.0                    <pip>
tk                        8.6.7                h35a86e2_3  
tqdm                      4.23.4                   py27_0  
traceback2                1.4.0            py27hece0a87_0  
unittest2                 1.1.0            py27hf661856_0  
wheel                     0.31.1                   py27_0  
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               hf3cbc9b_2 

`


I'm very new in this domain, and until now I didn't find any solution.

Can someone help me ?

Thank you
Alex
