### ISSUE TITLE
outlier-robust log-likelihood ratios from alternative_model

### ISSUE THREAD

**Issue by mollybrothers** [nanoporetech/tombo#290]
The 'outlier-robust' log-likelihood ratios that come out of the alternative model can be negative or positive (extracted using your stats dump script). Based on the legend of plotting per-read stats, it seems that the negative log likelihood ratio corresponds to likelihood ratio of a modified based while positive corresponds to the likelihood ratio of canonical base. Is this correct? (hopefully this question makes sense!!)

**Comment by marcus1487** [comment]
I think you have this correct, but the wording is slightly off. I would say that a positive likelihood ratio indicates that a canonical base is more likely than a modified base. A negative log likelihood indicates that a modified base is more likely than a canonical.

**Comment by mollybrothers** [comment]
Perfect, thanks for the clarification (and help with accurate language!)
