### ISSUE TITLE
Error with tombo resquiggle

### ISSUE THREAD

**Issue by q1134269149** [nanoporetech/tombo#291]
Hi,
When I ran tombo resquiggle, I got the following error:
**[10:56:52] Loading minimap2 reference.
tombo.sh: line 4:  2806 Illegal instruction     (core dumped) tombo resquiggle --rna --processes 15 --corrected-group RawGenomeCorrected_001 --basecall-group Basecall_1D_001 --include-event-stdev --overwrite --ignore-read-locks $data $transref**
I checked my fast5 file, it contains the Basecall_1D_001 group. Because this error message is too simple, I can't find the problem.
Could you help me? Thanks.
Hang Qin

**Comment by marcus1487** [comment]
I see that you have set the `--ignore-read-locks` flag. This is generally for debugging purposes only. Before using this parameter it should be checked that zombie tombo workers from a previous run are not still active (e.g. using top or htop). Such zombie processes working on the same read files can cause such errors.

**Comment by q1134269149** [comment]
> I see that you have set the `--ignore-read-locks` flag. This is generally for debugging purposes only. Before using this parameter it should be checked that zombie tombo workers from a previous run are not still active (e.g. using top or htop). Such zombie processes working on the same read files can cause such errors.

Thanks, I have solved this error.

**Comment by ashafik1** [comment]
I am getting the same issue. I previously successfully ran this, but now I get this error. How was it solved?
