### ISSUE TITLE
Mismatch between length of read and number of events

### ISSUE THREAD

**Issue by mollybrothers** [nanoporetech/tombo#293]
This is likely due to not understanding the definition of "events", but shouldn't the number of bases in the fastq from guppy match the number of events given by tombo for each read?

For example, I have a read that has 4,892 called bases (Basecall_1D_000/BaseCalled_template/Fastq in the fast5 file for this read) but only 4,824 events (RawGenomeCorrected_000/BaseCalled_template/Events in the fast5 file for the same read).

Is this a fair comparison to make? Where is my understanding lacking?

Thank you!

**Comment by marcus1487** [comment]
The Events resulting from Tombo resquiggle represent reference (genome/transcriptome) positions. In the resquiggle methods the basecalled sequence is used to map the read to the reference. From then forward only the reference sequence is used and the basecalls are essentially discarded. For more details on the resquiggle algorithm see [the docs here](https://nanoporetech.github.io/tombo/resquiggle.html).
