### ISSUE TITLE
Tombo resquiggle Bus errors

### ISSUE THREAD

**Issue by q1134269149** [nanoporetech/tombo#295]
Hi,
   I used tombo to resquggle my data, but I got the "Bus errors" in the log:

**_nohup: ignoring input
[14:25:23] Loading minimap2 reference.
[14:25:31] Getting file list.
[17:10:33] Re-squiggling reads (raw signal to genomic sequence alignment).
100%|██████████| 1123405/1123405 [238:37:26<00:00,  1.31it/s]
[15:48:00] Final unsuccessful reads summary (19.8% reads unsuccessfully processed; 222171 total reads):
    14.6% ( 164039 reads) : Alignment not produced
     4.8% (  54280 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`)
     0.3% (   3842 reads) : Read event to sequence alignment extends beyond bandwidth
     0.0% (      8 reads) : Reference mapping contains non-canonical bases (transcriptome reference cannot contain U bases)
     0.0% (      2 reads) : Not enough raw signal around potential genomic deletion(s)
[15:48:00] Saving Tombo reads index to file.
tombo.sh: line 1:  **5901 Bus error**               tombo resquiggle --rna --processes 15 --corrected-group RawGenomeCorrected_001 --basecall-group Basecall_1D_001 --include-event-stdev --overwrit workspace ref.fasta_**

I donot know what the problem is. And do I need to do resquiggle again?
Thanks
hqin

**Comment by marcus1487** [comment]
I have not encountered this error before and likely cannot replicate this issue. One thought would be to check the disk memory on the device where the output is being stored. It looks like this is happening when writing to disk. Could the disk be full?

**Comment by q1134269149** [comment]
> I have not encountered this error before and likely cannot replicate this issue. One thought would be to check the disk memory on the device where the output is being stored. It looks like this is happening when writing to disk. Could the disk be full?

Yes, during the program run, the disk is full once. Do I need to start over again in this situation?
Thanks

**Comment by marcus1487** [comment]
Yes. You will need to restart processing in this case.
