### ISSUE TITLE
On preprocess annotate_raw_with_fastqs command

### ISSUE THREAD

**Issue by PeterWu-Biomath** [nanoporetech/tombo#298]
Currently I'm trying to set up the tombo pipeline and run with open data set, I've downloaded two files:

`https://openstack.cebitec.uni-bielefeld.de:8080/swift/v1/nanopore_course_data/Data_Group1.tar.gz
https://openstack.cebitec.uni-bielefeld.de:8080/swift/v1/nanopore_course_data/Results_Group1.tar.gz`

In the first tar ball contains a fast5 file in data1/fast5_tiny/, which looks like :

 
![image](https://user-images.githubusercontent.com/49771207/96532376-5be8c600-12be-11eb-83c7-b64ead2eca19.png)

and there're called fastq files in second tarball, I've unzipped and concat them, the first read id looks like 
`@003a4858-6b80-4c35-b665-b4b63a0f5bed runid=b110eefd3ba5e91817c69585fcd2257218eeb796 sampleid=Run00014_MIN106_RBK004 read=1163 ch=503 start_time=2018-12-17T11:43:07Z`

and with command "tombo preprocess annotate_raw_with_fastqs --fast5-basedir data1/fast5_tiny/ --fastq-filenames basecall_tiny.fastq" output looks like 
`[10:24:00] Preparing reads and extracting read identifiers.
****** WARNING ****** Basecalls exsit in specified slot for some reads. Set --overwrite option to overwrite these basecalls.  
100%|███████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.89it/s]
[10:24:00] Annotating FAST5s with sequence from FASTQs.
****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.
0it [00:00, ?it/s]
[10:24:01] Added sequences to a total of 0 reads.`
and once trying to resquiggle them "tombo resquiggle --dna data1/fast5_tiny/ data1/Reference.fna" I got error
`[10:25:08] Loading minimap2 reference.
[10:25:09] Getting file list.
******************** ERROR ********************
        Reads do not to contain basecalls. Check --basecall-group option if basecalls are stored in non-standard location or use tombo preprocess annotate_raw_with_fastqs to add basecalls from FASTQ files to raw FAST5 files.`

Did I misunderstand something?

**Comment by PeterWu-Biomath** [comment]
seemingly same with https://github.com/nanoporetech/tombo/issues/286
I solved with multi_to_single_fast5 command, sorry for interrruption

**Comment by sumin5784** [comment]
I, I checked #286, and I think I did correct way.

1. I demultiplexed multi-fast5 files, using multi_to_single_fast5 command.
=> I have some questions on this. For example, I have test.fast5, which is multi-fast5 file, and one corresponding fastq file. If I demultiplex fast5, then there are many fast5 files, then how these single fast5 files can be annotated with single fastq file?

2. I annotate those single fast5 files with fastq, using annotate_raw_with_fastqs command. 
But I had following outputs: 

[12:24:20] Preparing reads and extracting read identifiers.
****** WARNING ****** Basecalls exsit in specified slot for some reads. Set --overwrite option to overwrite these basecalls.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4001/4001 [00:17<00:00, 230.62it/s]
[12:24:38] Annotating FAST5s with sequence from FASTQs.
****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.
0it [00:00, ?it/s]
[12:24:38] Added sequences to a total of 0 reads.

3. I did re-squiggling, and it did not causes errors, but output seems weird.


Any feedbacks would be appreciated! Thank you.
