### ISSUE TITLE
--minimap2-index argument

### ISSUE THREAD

**Issue by niphilli** [nanoporetech/tombo#301]
Hi Marcus...I have run into the need again to pass the .idx file from minimap2 to tombo after tweaking the k and w parameters. 
I ran this command:
`tombo resquiggle <path_to_fast5s>    reference.fa    --minimap-index reference.idx    --tombo-model-filename Canonical_mtDNAtrained    --processes 4 --overwrite`

I am getting the following error:
'tombo: error: unrecognized arguments: --minimap-index Synthetic_Oligo_3_reference_k12w8.idx'

Thoughts? Thanks in advance!

**Comment by marcus1487** [comment]
The minimap2 index can be passed in place of the FASTA reference. The `--minimap-index` option is only needed for the event_resquiggle method.

**Comment by niphilli** [comment]
got it...thank you!
