### ISSUE TITLE
multi fast5 support?

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/tombo#304]
Hi

Are there any plans on updating tombo to support multifast5s? (I had completely forgotten how bad the computer handles the many files)

Best regards
Rasmus

**Comment by marcus1487** [comment]
Hi Rasmus,

We are not likely to add multi fast5 support to the existing Tombo repository. As noted in several other threads this would require a re-working of most interfaces with the data (across most all modules). We are instead working on a ground up re-write of Tombo that will contain most all of the core functionality in a much cleaner interface.

**Comment by Kirk3gaard** [comment]
Cool. I will be looking forward to tombo 2.0 then ;)
