### ISSUE TITLE
per read stats

### ISSUE THREAD

**Issue by JohnUrban** [nanoporetech/tombo#31]
Just a question -- what is the ```stat``` in ```myfile.tombo.per_read_stats``` ??

**Comment by marcus1487** [comment]
The `stat` field of the per-read statistics file is either a hypothesis test p-value for the sample comparison or de novo testing methods or a log likelihood ratio for the alternative model comparison method. Here is a more complete description from the documentation: https://nanoporetech.github.io/tombo/modified_base_detection.html#per-read-statistics-file-format

**Comment by JohnUrban** [comment]
Hmmm so basically I need to RTFM. Got it! Thanks :)
