### ISSUE TITLE
Output files

### ISSUE THREAD

**Issue by kewei2019** [nanoporetech/tombo#314]
Hi - I'm trying to use tombo to call out DAM methylation sites on genome. The output files are two bedgraph files showing coverage and wig files showing dampened fraction. What is the title for each row? Thank you very much!

bedgraph:
![image](https://user-images.githubusercontent.com/52051945/105257674-82c8c980-5b45-11eb-8fad-247711ee255d.png)

wig:
![image](https://user-images.githubusercontent.com/52051945/105257700-91af7c00-5b45-11eb-8ec3-b33b619b8b4b.png)

Kewei Xu

**Comment by marcus1487** [comment]
https://genome.ucsc.edu/goldenPath/help/bedgraph.html
https://genome.ucsc.edu/goldenPath/help/wiggle.html
