### ISSUE TITLE
Current signal assigned to specific base issue

### ISSUE THREAD

**Issue by Zhaoxinjia** [nanoporetech/tombo#317]
The basecalling algorithm converts each event into a 5-mer state. In other words, each current level represents 5 bases simultaneously occupied the nanopore confinement. So I wonder the resquiggle algorithm assign a normalized current signal as one base, actually, which base in 5-mer? The first base in 5-mer model or other base?

**Comment by marcus1487** [comment]
The tombo k-mer model has the concept of a "central base". When a model is estimated the `--before-bases` and `--after-bases` determine the length of the k-mer and the position within the k-mer of the central base. This central base is the position in which the signal is assigned. You can see in the k-mer signal level plot ([in docs here](https://nanoporetech.github.io/tombo/plotting.html#k-mer-signal-levels)) that the central base within the k-me is usually quite obvious for DNA.

This value can be different for different models. For the CpG model a 6-mer is modeled and the second base in the 6-mer is the central base. Other models can be loaded and accessed via the `TomboModel` object through the API. See the [docs here](https://nanoporetech.github.io/tombo/tombo.html#python-api-examples).

**Comment by Zhaoxinjia** [comment]
I really appreciate your help.
