### ISSUE TITLE
threshold  of dampened_fraction.

### ISSUE THREAD

**Issue by lqsae** [nanoporetech/tombo#318]
hi, 
 how can i to determine the threshold  of which is 6mA，from the dampened_fraction。

**Comment by marcus1487** [comment]
See the help in the `tombo detect_modifications alternative_model --help` command. Specifically the `--single-read-threshold` argument gives the threshold range for the DNA and RNA models. Note that values between the range are considered uncertain and do not contribute to the dampened fraction output.
