### ISSUE TITLE
ValueError: cannot convert float NaN to integer in Ubuntu 20.04

### ISSUE THREAD

**Issue by Zinksulfid** [nanoporetech/tombo#319]
Hi,

I used to run tombo commands successfully on Ubuntu 18.04. Since upgrading to 20.04, I get the error below with the tombo resquiggle command. An index file is not created and `tombo detect_modifications alternative_model` returns the error `ValueError: cannot convert float NaN to integer`. The low alignment rate is expected as aligning against mitochondrial DNA. 

```
tombo resquiggle basecalled/single_threshold-7_testarea/ Mus_musculus.GRCm38.dna.chromosome.MT.fasta --processes 4 --num-most-common-errors 5 --overwrite
[19:50:59] Loading minimap2 reference.
[19:50:59] Getting file list.
[19:51:00] Loading default canonical ***** RNA ***** model.
[19:51:00] Re-squiggling reads (raw signal to genomic sequence alignment).
5 most common unsuccessful read types (approx. %):
    94.7% (  42445 reads) : Alignment not produced                                                          
     5.5% (   2447 reads) : Unexpected error                                                                
     -----
     -----
     -----
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44906/44906 [24:21<00:00, 30.72it/s]
******************** WARNING ********************
	Unexpected errors occured. See full error stack traces for first (up to) 50 errors in "unexpected_tombo_errors.2242.err"
[20:15:22] Final unsuccessful reads summary (100.0% reads unsuccessfully processed; 44906 total reads):
    94.5% (  42458 reads) : Alignment not produced                                                          
     5.5% (   2448 reads) : Unexpected error                                                                
[20:15:22] Saving Tombo reads index to file.
```

The unexpected errors traceback:
```

BaseCalled_template:::basecalled/single_threshold-7_testarea/workspace/0/02f881fa-9622-4be6-97eb-bde5b0d3a788.fast5
:::
Traceback (most recent call last):
  File "/home/machine/.local/lib/python3.8/site-packages/tombo/resquiggle.py", line 1570, in _resquiggle_worker
    map_res = adjust_map_res(map_res)
  File "/home/machine/.local/lib/python3.8/site-packages/tombo/resquiggle.py", line 1522, in adjust_map_res
    stall_ints=ts.identify_stalls(
  File "/home/machine/.local/lib/python3.8/site-packages/tombo/tombo_stats.py", line 313, in identify_stalls
    stall_metric[:] = np.NAN
ValueError: cannot convert float NaN to integer
```

Do you have any idea what the issue might be? Thanks for help!
Florian

**Comment by DelphIONe** [comment]
I have the same problem. Any help ?

**Comment by marcus1487** [comment]
This may have to do with some recent changes in the ont_fast5_api. Could you try to downgrade to version <3.2 (e.g. `pip install ont_fast5_api<3.2`).

**Comment by DelphIONe** [comment]
Thanks for your help Marcus.
I tried with 3.1.6, 3.1.5, 3.1.4, 3.1.3, 3.1.2, 3.1.1 and 3.1.0 but it's the same result :-(

**Comment by DelphIONe** [comment]
To be clearer :
my result is

[18:00:32] Loading minimap2 reference.
[18:00:32] Getting file list.
[18:00:32] Re-squiggling reads (raw signal to genomic sequence alignment).
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:11<00:00,  4.34it/s]
[18:00:44] Final unsuccessful reads summary (12.0% reads unsuccessfully processed; 6 total reads):
     8.0% (      4 reads) : Read event to sequence alignment extends beyond bandwidth                       
     2.0% (      1 reads) : Read contains too many potential genomic deletions                              
     2.0% (      1 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`) 
[18:00:44] Saving Tombo reads index to file.
[18:00:44] Parsing Tombo index file(s).
[18:00:44] Performing alternative model testing.
[18:00:44] Performing specific alternate base(s) testing.
[18:00:44] Calculating read coverage regions.
[18:00:44] Calculating read coverage.
[18:00:45] Performing modified base detection across genomic regions.
  0%|                                                                                                                                                                                 | 0/6 [00:00<?, ?it/s]Process Process-10:
Traceback (most recent call last):
  File "/home/xx/miniconda3/envs/meteore_tombo_env/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/xx/miniconda3/envs/meteore_tombo_env/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xx/miniconda3/envs/meteore_tombo_env/lib/python3.9/site-packages/tombo/tombo_stats.py", line 4449, in _get_stats_queue
    all_stats[alt_name] = ModelStats(
  File "/home/xx/miniconda3/envs/meteore_tombo_env/lib/python3.9/site-packages/tombo/tombo_stats.py", line 2697, in __init__
    self._create_new_stats_file()
  File "/home/xx/miniconda3/envs/meteore_tombo_env/lib/python3.9/site-packages/tombo/tombo_stats.py", line 2625, in _create_new_stats_file
    self.running_most_signif_sites[:] = np.NAN
ValueError: cannot convert float NaN to integer
 67%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                        | 4/6 [00:00<00:00, 19.82it/s] # #

and it's blocked on that ...
Maybe I can play with the tombo filter ? Help please...

**Comment by Zinksulfid** [comment]
@marcus1487 thanks for your reply, it didn't solve the problem for me either, unfortunately.

However, what did work was to re-install R, and then rpy2 again. @DelphIONe would you mind trying that as well?

**Comment by lpryszcz** [comment]
Hey, I've have the same issue. Downgrading ont_fast5_api didn't help, as the issue seems to be numpy related. [Apparently np.NaN casting used in tombo isn't compatible with numpy 1.20+](https://github.com/nanoporetech/tombo/blob/master/tombo/tombo_stats.py#L313)
![image](https://user-images.githubusercontent.com/988152/108836363-09534980-75d1-11eb-8579-e04b4cbebf74.png)

For me the solutions was to downgrade numpy to version<1.20. 
```
pip install "numpy<1.20"
```
Cheers!

**Comment by marcus1487** [comment]
Thank you for this update. I think this is likely the solution for now. I'll update the tombo requirements with this version pin.

**Comment by Zinksulfid** [comment]
Thanks, all!

**Comment by DelphIONe** [comment]
Thanks for the help.
For me, the error is become :
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by DelphIONe** [comment]
It's ok with python 3.6 (I used 3.9)
Thanks !

**Comment by Laffey-z** [comment]
> python 3.6 没问题（我用的是 3.9） 谢谢！



> python 3.6 没问题（我用的是3.9） 谢谢！

I tried downgrading python to 3.6 ，but got another error.The specific error is as follows, I don't know how to solve it.


[13:56:19] Final unsuccessful reads summary (73.1% reads unsuccessfully processed; 16465 total reads):
    52.5% (  11831 reads) : Alignment not produced                                                          
    10.6% (   2377 reads) : Base calls not found in FAST5 (see `tombo preprocess`)                          
     9.4% (   2113 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`) 
     0.6% (    144 reads) : Read event to sequence alignment extends beyond bandwidth                       
[13:56:19] Saving Tombo reads index to file.
(mxy) [abd@node01 ~]$ tombo filter clear_filters
usage: tombo filter clear_filters --fast5-basedirs FAST5_BASEDIRS
                                  [FAST5_BASEDIRS ...]
                                  [--corrected-group CORRECTED_GROUP]
                                  [--quiet] [--help]
tombo filter clear_filters: error: the following arguments are required: --fast5-basedirs


Hope to get help. thank you very much.

**Comment by NuriaDiaz** [comment]
> Thank you for this update. I think this is likely the solution for now. I'll update the tombo requirements with this version pin.

Hi! I've encountered the same issue. I've just downloaded tombo in a new conda environment and it automatically downloads numy 1.21.6, then the resquiggling doesn't work. Would it be possible to change it in a way that when tombo is downloaded through conda the right version of the dependencies get downloaded?

Thanks!

**Comment by doshirLV** [comment]
> > Thank you for this update. I think this is likely the solution for now. I'll update the tombo requirements with this version pin.
> 
> Hi! I've encountered the same issue. I've just downloaded tombo in a new conda environment and it automatically downloads numy 1.21.6, then the resquiggling doesn't work. Would it be possible to change it in a way that when tombo is downloaded through conda the right version of the dependencies get downloaded?
> 
> Thanks!

Bumping this post and I second this reply. The conda recipe should be changed to `numpy=1.19.5`.
