### ISSUE TITLE
Question on Tombo per-site aggregation result

### ISSUE THREAD

**Issue by PanZiwei** [nanoporetech/tombo#321]
Hi,
1. I found that **DNA:-1.5, 2.5, RNA:-2.5, 2.5** is set for `--single-read-threshold` when using `tombo detect_modifications alternative_model --help`. So do DNA and RNA use different thresholds for aggregation result? Just want to double-check.

2. You mentioned that in https://github.com/nanoporetech/tombo/issues/232#issuecomment-603540494 that "Calls with scores between -2.5 and 2.5 will not contribute to the methylation fraction at that site", In this case, do you mean that **these unqualified calls won't contribute to coverage** also?

Thank you so much for your help!

**Comment by marcus1487** [comment]
Yes. The default thresholds for aggregation are different for DNA and RNA. Tombo has two values for coverage: coverage and valid coverage. Valid coverage is used to determine the number of reads contributing to the fraction of modified bases. These can both be output from the `tombo text_output browser_files` command with the `coverage` and `valid_coverage` options to the `--file-types` argument.
