### ISSUE TITLE
error in preprocessing

### ISSUE THREAD

**Issue by sdy-xu** [nanoporetech/tombo#322]
Hi Marcus,

I am trying to use tombo (v1.5.1, python 3.7,installed with conda) for annotation of raw fast5 files with fastq.

```bash
multi_to_single_fast5 -i fast5_pass -s single_fast5 -t 10

cat ./fastq_pass/*.fastq > test.fq

tombo preprocess annotate_raw_with_fastqs --fast5-basedir single_fast5 --fastq-filenames test.fq --overwrite --processes 18

```

I got this error
```bash
[17:08:35] Preparing reads and extracting read identifiers.
100%|█| 1023323/1023323 [17:49<00:00, 957.22it/s]
[17:26:53] Annotating FAST5s with sequence from FASTQs.
****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.0it [01:13, ?it/s]
[17:28:07] Added sequences to a total of 0 reads.
```

I also tried to use `--sequencing-summary-filenames`,but not work. [preprocessing issues - warning for adding basecall information from Guppy #245](https://github.com/nanoporetech/tombo/issues/245).
```bash
$ tombo preprocess annotate_raw_with_fastqs --fast5-basedir ./single_fast5 --fastq-filenames test.fq --sequencing-summary-filenames sequencing_summary.txt --overwrite --processes 10
[16:37:46] Getting read filenames.
[16:38:13] Parsing sequencing summary files.
******************** WARNING ********************
        Some FASTQ records from sequencing summaries do not appear to have a matching file.
[16:38:17] Annotating FAST5s with sequence from FASTQs.
****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencin
g summary files.
0it [01:07, ?it/s]
[16:39:25] Added sequences to a total of 0 reads.
```

What's more,I checked the writability of *.fast5 and their directory, They are all write-able.  [preprocess and resquiggle data input issues #316](https://github.com/nanoporetech/tombo/issues/316)
```bash
cd single_fast5
ls -lh
drwxr-xr-x 2 ...  0
drwxr-xr-x 2 ... 1
drwxr-xr-x 2 ... 10
drwxr-xr-x 2  ...100

cd 0
-rw-r--r-- 1 ... ffe3e160-53b5-4a9e-969d-b1f43a930a77.fast5
-rw-r--r-- 1 ... ffef0336-947d-482f-9395-97b4918f365e.fast5
-rw-r--r-- 1 ... fff6bbb5-02ad-46f1-8b28-7ef68be573e5.fast5
-rw-r--r-- 1 ... fffaaff4-27af-4610-a730-6df8741f7d53.fast5
```
Could you please help me?

Thanks，
sdy_xu

**Comment by marcus1487** [comment]
Could you confirm that these files (FAST5s and FASTQs) are matched? Could you perform a test (even on a small subset) to re-basecall the FAST5s with guppy and annotate with these new basecalls?

**Comment by ViHammer** [comment]
I think I have had the same issue. Adding the default parameters
` --basecall-group Basecall_1D_000 --basecall-subgroup BaseCalled_template ` 
helped im my case.

**Comment by Xiaojuan-Liang** [comment]
> I think I have had the same issue. Adding the default parameters
> `--basecall-group Basecall_1D_000 --basecall-subgroup BaseCalled_template`
> helped im my case.

Hello, I have added the default parameters, but there are some errors :

$tombo preprocess annotate_raw_with_fastqs --fast5-basedir nanopore_data/0 --fastq-filenames nanopore_data/0_guppy/*.fastq --basecall-group Basecall_1D_000 --basecall-subgroup BaseCalled_template --overwrite --processes 12
[16:53:16] Preparing reads and extracting read identifiers.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8000/8000 [00:02<00:00, 3061.29it/s]
[16:53:19] Annotating FAST5s with sequence from FASTQs.
****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.
0it [00:00, ?it/s]
[16:53:19] Added sequences to a total of 0 reads.

Could you help me?
Thanks!

**Comment by sdy-xu** [comment]
> Could you confirm that these files (FAST5s and FASTQs) are matched? Could you perform a test (even on a small subset) to re-basecall the FAST5s with guppy and annotate with these new basecalls?

thank you！
In fact, I ignored this step, and it seems to have no effect on the subsequent analysis

**Comment by mrubio-chavarria** [comment]
I followed these instructions and, for some reason, I was not able to assign the reads. Surprisingly, I was able to execute, exactly the same commands with Python 2.7 and Tombo. Hope it helps, no need to do more.

**Comment by BeatrizFaustino** [comment]
Good afternoon, did you use the cat command before the tombo preprocess?
