### ISSUE TITLE
runtime of tombo resquiggle

### ISSUE THREAD

**Issue by ViHammer** [nanoporetech/tombo#324]
EDIT: The runtime seems to be normal on my server infrastructure. I did not close this issue yet as the unexpected behavior described in my second and third message is not yet resolved.
__________________________________________________

I am currently "resquiggling" promethION reads and I would like to know how long I should expect this step to take. It has already been running for over 37 hours and has only reached 67% completion.

Most reads have a length of around 15kb, only very few are longer than 75kb. The commands I used:

```
multi_to_single_fast5 -i /.../fast5_pass -s /.../fast5_pass_single -t 10 --recursive

tombo preprocess annotate_raw_with_fastqs \
	        --fast5-basedir /.../fast5_pass_single \
		--fastq-filenames /.../fastqs_pass.fastq \
		--overwrite \
		--basecall-group Basecall_1D_000 \
		--basecall-subgroup BaseCalled_template \
	        --processes 5

tombo resquiggle /.../fast5_pass_single \
	         /.../GRCh38.fa \
	 	 --processes 30 --ignore-read-locks
```
![grafik](https://user-images.githubusercontent.com/43847498/111812330-4f51b380-88d8-11eb-99da-04138d7d87aa.png)

Most processes/ threads seems to be in a sleeping state. 

Progress displayed: `4128600/6198126 [46:38:06<23:22:35, 24.59it/s]`

The environment I am using:
[env.txt](https://github.com/nanoporetech/tombo/files/6172830/env.txt)

Are these long run times to be expected? Thanks in advance!

**Comment by ViHammer** [comment]
My script failed sometime this weekend. My tmux session only shows me the last 1700 lines of output, but this is what it looks like (I cut off the first 1600+ OMP messages for readability):
```

OMP: Info #250: KMP_AFFINITY: pid 14673 tid 34628 thread 109 bound to OS proc set 53
OMP: Info #250: KMP_AFFINITY: pid 14673 tid 34636 thread 117 bound to OS proc set 54
OMP: Info #250: KMP_AFFINITY: pid 14673 tid 34637 thread 118 bound to OS proc set 58
OMP: Info #250: KMP_AFFINITY: pid 14673 tid 34638 thread 119 bound to OS proc set 62
OMP: Info #250: KMP_AFFINITY: pid 14673 tid 34639 thread 120 bound to OS proc set 35
OMP: Info #250: KMP_AFFINITY: pid 14673 tid 34640 thread 121 bound to OS proc set 39
OMP: Info #250: KMP_AFFINITY: pid 14673 tid 34641 thread 122 bound to OS proc set 43
OMP: Info #250: KMP_AFFINITY: pid 14673 tid 34642 thread 123 bound to OS proc set 47
OMP: Info #250: KMP_AFFINITY: pid 14673 tid 34643 thread 124 bound to OS proc set 51
OMP: Info #250: KMP_AFFINITY: pid 14673 tid 34644 thread 125 bound to OS proc set 55
OMP: Info #250: KMP_AFFINITY: pid 14673 tid 34645 thread 126 bound to OS proc set 59
OMP: Info #250: KMP_AFFINITY: pid 14673 tid 34647 thread 128 bound to OS proc set 0
OMP: Info #250: KMP_AFFINITY: pid 14673 tid 34646 thread 127 bound to OS proc set 63

[1]+  Stopped                 ./methylation2.sh
```

Is this error server side? Is there a way to check which reads were successfully resquiggled?

**Comment by ViHammer** [comment]
Another update:
I have now learnt that the last error message was infact only a notification that the resquiggle process was stopped, but did not fail. What I do not understand is why did the next step in my bash script start? I was under the impression that the script should have waited for an exit code to start the next command. Does tombo produce an exit code when stopped?

**Comment by drdivine** [comment]
Hi,
I wondering how to optimize my tombo preprocess and resquiggle commands. Here's what it looks like for me.

`tombo preprocess annotate_raw_with_fastqs   --fast5-basedir ${fast5_singles} \  
                                                --fastq-filenames ${fasta_file} \  
                                                --sequencing-summary-filenames  ${sequencing_summary_filename_singles} \  
                                                --overwrite \  
                                                --processes ${tombo_processes} \  
                                                --basecall-group Basecall_1D_000 \  
                                                --basecall-subgroup BaseCalled_template`
Afterwards, I'm running the following:

`tombo resquiggle ${fast5_singles} \
                     ${reference_fasta} \
                    --processes ${tombo_processes} \
                    --overwrite \
                    --threads-per-process ${tombo_threads_per_process}`

- Should fastq be one file or multiple files?
- how many processes?
- how many threads per process?

Thanks for your support!

Best Regards

Matt

**Comment by ViHammer** [comment]
> 
> 
> Hi,
> I wondering how to optimize my tombo preprocess and resquiggle commands. Here's what it looks like for me.
> 
> `tombo preprocess annotate_raw_with_fastqs --fast5-basedir ${fast5_singles} \ --fastq-filenames ${fasta_file} \ --sequencing-summary-filenames ${sequencing_summary_filename_singles} \ --overwrite \ --processes ${tombo_processes} \ --basecall-group Basecall_1D_000 \ --basecall-subgroup BaseCalled_template`
> Afterwards, I'm running the following:
> 
> `tombo resquiggle ${fast5_singles} \ ${reference_fasta} \ --processes ${tombo_processes} \ --overwrite \ --threads-per-process ${tombo_threads_per_process}`
> 
>     * Should fastq be one file or multiple files?
> 
>     * how many processes?
> 
>     * how many threads per process?
> 
> 
> Thanks for your support!
> 
> Best Regards
> 
> Matt

I create one fastq file from all the individual ones I have with
` cat /.../*.fastq > "/.../fastqs_pass.fastq"`.

The `preprocess` step seems to be mostly limited by the read and write speed of the server, one or two cores are all I need/ can use. Using more is actually detrimental in my case. 
I use as many cores/ threads as I can for resquiggling. You can check how many you can use on your system with `htop`.

Lastly, from what I understand the terms processes/ threads/ cores are often mixed up. You can check how many threads you can use with `lscpu`, and then checking the `CPU(s)` value. I think that this is what is meant by the `--processes` flag, but NO guarantee for correctness.

Please open a new issue of you have additional questions.

**Comment by marcus1487** [comment]
@ViHammer , I've not seen this error code for stopped tombo processes. I'm not sure exactly how your system is stopping tombo, so I'm not sure what error code tombo would return as an error code. Unfortunately, we don't have full support on this project so I won't be able to dig too much deeper into this issue. If you do find a conclusion posting here may help other users so is much appreciated.

**Comment by ViHammer** [comment]
To summarize the issue I had before closing this topic:
a server side error caused tombo resquiggle to stop, but not fail (this is my understanding at least). This for some reason still returned an exit code, which prompted the next command in my script to run. 
I do not know how to reproduce this error, let alone fix it. 

Before rerunning tombo resquiggle I simply had to kill all processes assigned to the command.
