### ISSUE TITLE
PerReadStats.get_region_per_read_stats uses discontinued h5py interface

### ISSUE THREAD

**Issue by Chris-Kimmel** [nanoporetech/tombo#325]
Hi Marcus.

The method `PerReadStats.get_region_per_read_stats` attempts to read an `h5py.dataset.value` attribute:

https://github.com/nanoporetech/tombo/blob/de496ff122e0125023b8e6790c33ea264bc3aebf/tombo/tombo_stats.py#L3400-L3401

This interface was removed in h5py 3.0. See https://docs.h5py.org/en/stable/whatsnew/2.1.html#dataset-value-property-is-now-deprecated and https://docs.h5py.org/en/stable/whatsnew/3.0.html?highlight=dataset.value#breaking-changes-deprecations.

Now when I run this line in a Python script:
```python
tombo_stats.PerReadStats(args.prs_path).get_region_per_read_stats(reg)
```
the script fails with the following error message:
> Traceback (most recent call last):
>   File "/fs/project/PAS1405/prsconv2/prsconv2.py", line 44, in <module>
>     .get_region_per_read_stats(reg)
>   File "/users/PAS1405/kimmel/.conda/envs/sci-computing-env/lib/python3.7/site-packages/tombo/tombo_stats.py", line 3400
> , in get_region_per_read_stats
>     zip(self.per_read_blocks[block_name]['read_ids'].value,
> AttributeError: 'Dataset' object has no attribute 'value'

I am running Tombo version 1.5.1 with h5py version 3.1.0. (A copy of my Tombo environment is attached: [sci-computing-env.txt](https://github.com/nanoporetech/tombo/files/6190764/sci-computing-env.txt).)

[Edit: The same script worked without error in a different conda environment: [tombo2.txt](https://github.com/nanoporetech/tombo/files/6190980/tombo2.txt).]

I suggest using the new h5py interface and adding an `h5py<3` dependency to the existing `ont-tombo` package.

~Chris

**Comment by marcus1487** [comment]
Thank you for the pull request. This has been merged and I have pinned the h5py version to <3 in github master.
