### ISSUE TITLE
Tombo statistics file chromosome name truncation

### ISSUE THREAD

**Issue by marcus1487** [nanoporetech/tombo#33]
As found in the process of fixing #29, it was determined that the Tombo statistics file only stores the first 32 characters of a chromosome name which causes issues with several other Tombo commands. This issue separates out this particular issue from #29 which also addresses some other installation issues. To fix this, the chromosome (and strand) information should be removed from the statistics data tables and stored separately in the Tombo statistics HDF5 file (since each statistics block only covers a particular genomic region). This interface will need to be corrected throughout the statistics file interface within Tombo.

For others encountering this issue in the current release (1.2), clipping FASTA unique reference names (all characters before the first space) down to less than 32 characters should solve this issue.

**Comment by ma-diroma** [comment]
Hi Marcus,

could you please tell me if this bug can be the cause of an error arising when `test_significance` is run with `--control-fast5-basedirs` option?

```
Parsing tombo index file(s).
Performing two-sample comparison significance testing.
Parsing tombo index file(s).
Performing significance testing across 25195 regions. (Will print a dot for each batch completed)
Process Process-2:
Traceback (most recent call last):
  File "/home/madiroma/bin/anaconda3/envs/tombo/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/madiroma/bin/anaconda3/envs/tombo/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/madiroma/bin/anaconda3/envs/tombo/lib/python3.6/site-packages/tombo/tombo_stats.py", line 1740, in _test_s
ignif_worker
    r_data for r_data in ctrl_read_coverage[(chrm, strand)]
KeyError: ('ENST00000529086.5_1|ENSG00000170946.14_2|OTTHUMG00000133712.3_2|OTTHUMT00000388480.1_1|DNAJC24-209|DNAJC24|2
745|retained_intron|', '+')
...
```
(error repeated for all the processes)

Thanks,
Maria Angela

**Comment by marcus1487** [comment]
I think this is somewhat related, but a different issue. This is likely due to the control reads being re-squiggled against a different reference genome FASTA file. That being said this should absolutely not throw an error here and so this is still a bug. Especially since this will happen simply if the control and sample reads don't map to all the same FASTA records. The fix for this issue is much more simple than the fix for the long chromosome names though, so I may push a hotfix fix for this particular "sub-issue" to the github repo. I'll add a note here with that hotfix.

**Comment by ma-diroma** [comment]
I am pretty sure I used the same reference fasta file for my sample and the control.

**Comment by marcus1487** [comment]
Ya. Now that I think about it when mapping to a transcriptome you are much more likely to get fasta records where only one or the other sample maps, so that is most likely what is happening here. Thanks for the bug report!

**Comment by marcus1487** [comment]
@ma-diroma  This issue should be resolved with the last commit (after re-install from github). Please do let me know if you do encounter this issue still.

**Comment by ma-diroma** [comment]
Thank you!

**Comment by marcus1487** [comment]
I have 2 thoughts. First, if the previous alternative base incorporation rate was obtained from an older version of Tombo, the signal handling has changed quite significantly in this most recent version and could certainly cause this change. If both of these runs were with the most recent version (1.2), then this is irrelevant and you can ignore this first suggestion. 

My other thought is that this is due to the uniqueness of the new (truncated) transcript names. If more than one transcript has the same record name, then this will throw Tombo off in ways I have not investigated and could also cause this issue in theory (I would have to check exactly what would happen in this case). To check for this could you check to see that all of you record names are unique after modifying them to make them shorter?

I am working on the fix for the truncated names, so hopefully that will be fixed soon in any case.

**Comment by ma-diroma** [comment]
Both model training were carried on by the same version of tombo (the last).
I have checked the uniqueness of truncated transcript names, they are unique.

**Comment by marcus1487** [comment]
I am sorry that I can't think of anything that would cause these results to change here. The chromosome names should certainly not have any effect on the re-squiggle or modeling commands. To be sure I understand, the only difference between these two runs was the truncation of the fasta record names, correct? And all steps (re-squiggle and modeling) were completed on the newest version of Tombo? Hopefully we can track down why these results have changed here. Thanks for bearing with me!

**Comment by ma-diroma** [comment]
Yes, exactly.
If it can be useful, these are the logs of the 2 `resquiggle` commands, differing only for the trascriptome references used (long and short headers for each transcript)

(truncated fasta headers)
```
Correcting 15911 files with 1 subgroup(s)/read(s) each (Will print a dot for each 1000 reads completed).
...............
Failed reads summary (3689 total failed):
        Alignment not produced :        550
        Not enough raw signal around potential genomic deletion(s) :    6
        Poor raw to expected signal matching :  1569
        Poor raw to expected signal matching at read start :    1478
        Read event to sequence alignment extends beyond --bandwidth :   86
```
        

(long fasta headers)
```
Correcting 15911 files with 1 subgroup(s)/read(s) each (Will print a dot for each 1000 reads completed).
..............
Failed reads summary (3688 total failed):
        Alignment not produced :        550
        Not enough raw signal around potential genomic deletion(s) :    6
        Poor raw to expected signal matching :  1570
        Poor raw to expected signal matching at read start :    1479
        Read event to sequence alignment extends beyond --bandwidth :   83
```

There are small differences in the numbers since this step.

These are the logs of the estimate_alt_reference on the same fast5 dataset, with the same command line, using the 2 references

(truncated fasta headers)
```
Parsing base levels from alternative reads
        1000 reads processed. Current minimum k-mer observations: 345 towards goal of 1000
        2000 reads processed. Current minimum k-mer observations: 681 towards goal of 1000
Fitting kernel densities for k-mer levels
Parsing base levels from standard reads
        1000 reads processed. Current minimum k-mer observations: 588 towards goal of 1000
Fitting kernel densities for k-mer levels
Isolating alternative base distribtuions
Alternative base incorporation rate estimate: 0.21787157296973914
```


(long fasta headers)
```
Parsing base levels from alternative reads
        1000 reads processed. Current minimum k-mer observations: 326 towards goal of 1000
        2000 reads processed. Current minimum k-mer observations: 714 towards goal of 1000
Fitting kernel densities for k-mer levels
Parsing base levels from standard reads
        1000 reads processed. Current minimum k-mer observations: 524 towards goal of 1000
Fitting kernel densities for k-mer levels
Isolating alternative base distribtuions
Alternative base incorporation rate estimate: 0.3160446892629687
```

I need further information about plotting most significant modified bases, but probably it is better to start a new issue.

If you need all the command lines used to reproduce these results, I can send them to your email address. Please, let me know.
