### ISSUE TITLE
extracting modified bases per read

### ISSUE THREAD

**Issue by eoziolor** [nanoporetech/tombo#331]
Hi! Thank you for a really useful piece of software!

I am running model_sample_compare and wondering if I can somehow extract a data.frame or any type of readable file with annotation for each read from my sample and which bases on it are considered "modified"? I've tried browsing through the tutorials, but can't seem to find the exact way to do this and would much appreciate your help and guidance!

Thank you for considering!

-Elias

**Comment by eoziolor** [comment]
Oh I think I found it through the python API. Is this the right method?

sample_per_read_stats = tombo_stats.PerReadStats(
    'test_stats.alt_model.5mC.tombo.per_read_stats')
# reg_per_read_stats contains a numpy array containing per-read stats
# over all reads covering the region of interest
reg_per_read_stats = sample_per_read_stats.get_region_per_read_stats(
    reg_data)

**Comment by SAMtoBAM** [comment]
Hello @eoziolor 
I also could not find anything in the tutorials about this
Did you figure out how to produce a readable per-read statistics file?

Thanks

**Comment by eoziolor** [comment]
@SAMtoBAM yep. If you use the flag --per-read-statistics-basename in your command to detect modifications, it will output a per-read-stats file. You can open this stats file in python, extract stats on significance of modification for each base on each read and save it as a csv using the following set of python script:

`
from tombo import tombo_helper, tombo_stats, resquiggle
import pandas as pd

# Specify genomic region to explore
reg_data = tombo_helper.intervalData(
    chrm='<chr-name>', start=1, end=8460, strand='+')

# Specify tombo file to explore
sample_per_read_stats = tombo_stats.PerReadStats(
    '<per-read-stats-file>')

# Get test stat for each read at each site
reg_per_read_stats = sample_per_read_stats.get_region_per_read_stats(reg_data)

# Dump np.array as csv file
pd.DataFrame(reg_per_read_stats).to_csv("<location-to-csv-out>")
`

Hope this helps!

-Elias

**Comment by eoziolor** [comment]
Oh and @SAMtoBAM, the directions for this I found here:
https://nanoporetech.github.io/tombo/tombo.html#tombo-python-api
