### ISSUE TITLE
Running tombo sample compare on a subset of sequences

### ISSUE THREAD

**Issue by drivenbyentropy** [nanoporetech/tombo#349]
Hello, 

I was wondering if it is possible to run ```tombo sample compare``` on a subset of sequences (e.g. downsampling, clusters, etc) without the need to create a distinct copy for the fast5 files?

Taking downsampling as an example (1 treatment and 1 control with 500.000 reads each), I would like to randomly sample data in 5% increments to study when and how we loose a particular signal of interest. The only way I have found so far to do this is to 

* Create an index file (readids) with the sequence ids of interest for each subset
* Use ```fast5_subset``` to extract these sequences and ```multi_to_single_fast5``` to convert into single read files
* Resquiggle each subset to the genome
* Use these subsets as input to tombo for analysis

Is there a way to provide tombo with a list of read ids for sample and control so that I do not have to store multiple copies of the same fast5 file? Could this be done using the API? 

I am asking because the number of individual files to manage grows fast and can supersede per-user limits imposed in HPC environments (e.g. the maximum number of files allowed per user in my case it 30 million)

Thank you in advance.

**Comment by Chris-Kimmel** [comment]
> Taking downsampling as an example (1 treatment and 1 control with 500.000 reads each), I would like to randomly sample data in 5% increments to study when and how we loose a particular signal of interest. Is there a way to provide tombo with a list of read ids for sample and control so that I do not have to store multiple copies of the same fast5 file?

Last year I downsampled some of our lab's fast5 base-directories to see how sampling variance affected our Tombo results. I just took the hit and had 10^6 inodes.

If I had to do that project again, I would hack Tombo's `.tombo.index` files instead. Tombo index files are really just Python [pickles](https://docs.python.org/3/library/pickle.html). Inside one you'll find a list of Tombo [`readData`](https://github.com/nanoporetech/tombo/blob/afdb4d87249806d3a171d009f948f5b8558d35a0/tombo/tombo_helper.py#L127-L156) objects. Try unpickling an index, deleting some reads, and repickling the file. You can use symlinks to trick Tombo into thinking a directory contains a fast5 base-directory and index-file of your choosing.

> Could this be done using the API?

No.

Good luck, entropy.

**Comment by drivenbyentropy** [comment]
@Chris-Kimmel, this is really helpful, thank you. I will look into the index files and see if I can it working the way you describe.

**Comment by marcus1487** [comment]
Hi @Chris-Kimmel and @drivenbyentropy ,

This is not well documented, but there is a `filtered` attribute for each object in the tombo index. This is how the tombo filter commands work. You could work up your own script via the API to set this filtered attribute instead of moving files around etc. Here is an example filter script: https://github.com/nanoporetech/tombo/blob/master/tombo/_filter_reads.py#L86

**Comment by drivenbyentropy** [comment]
Hi @marcus1487, thank you for this, it is certainly a viable alternative, especially when combing this whith the ```reset_filter``` routine. 

One downside I can see over using symlinks and @Chris-Kimmel's appoach is that it would only allow processing datasets one at a time. For cluster environments, it might be desirable to process multiple datasets in parallel.

**Comment by drivenbyentropy** [comment]
Thanks again @Chris-Kimmel  and @marcus1487  for your suggestions. I ended up modifying the pickled index by sampling the ```readData``` objects at random and combining this with symbolic links to avoid duplicate files.
