### ISSUE TITLE
filters

### ISSUE THREAD

**Issue by DelphIONe** [nanoporetech/tombo#35]
Hi,

Filters available with Tombo are very useful! Is it possible to know which reads are filtered ?

Thanks for your reply,
Delphine

**Comment by marcus1487** [comment]
Hi Delphine,

There is nothing from the command line, but you could use the Tombo API. The index file is just a pickled python object so you could adapt something similar to [this fragment of code](https://github.com/nanoporetech/tombo/blob/1.2/tombo/tombo_helper.py#L765). The `filtered` value is a boolean indicating whether the currently applied filters have tagged this read to be filtered. As you can see these reads are not included in the `raw_reads_coverage` object returned from this function. Note that this filter tag does not indicate which filter marked this read for filtering as filters can be applied iteratively. Then you can do whatever you please with those reads that have either been filtered or not filtered in python. 

I hope this addresses your question. Also if there are more filters that would be particularly useful please let me know!
