### ISSUE TITLE
tombo detect_modifications level_sample_compare

### ISSUE THREAD

**Issue by Bessyyi** [nanoporetech/tombo#350]
Hello, I completed the first step index construction. But when i compare the two sets of data to find the methylation sites, I encountered a trouble. When I run  this step, the program will stop and the interface will remain motionless. How can i solve this  problem ?
The following is a screenshot of my operation, the interface has been stopped in this state
thanks！
![1](https://user-images.githubusercontent.com/73151161/122059967-bae7e600-ce1f-11eb-9e3a-dd00772df597.PNG)

**Comment by marcus1487** [comment]
This looks like an issue with numpy > 1.20. Downgrading with `pip install "numpy<1.20"`should resolve this issue.

**Comment by Bessyyi** [comment]
> This looks like an issue with numpy > 1.20. Downgrading with `pip install "numpy<1.20"`should resolve this issue.

Thank you very much! I will try the solution you said.

**Comment by Bessyyi** [comment]
> > This looks like an issue with numpy > 1.20. Downgrading with `pip install "numpy<1.20"`should resolve this issue.
> 
> Thank you very much! I will try the solution you said.
Hi,teacher!  I solve the problem when i  downgrade the numpy. But when i run 'tombo detect_modifications level_sample_compare'  i meet another problem.Can you give me some advice ?Thank you very much !
![12](https://user-images.githubusercontent.com/73151161/122212573-956be280-ceda-11eb-80b7-f861ab7ea133.PNG)

**Comment by Bessyyi** [comment]
> This looks like an issue with numpy > 1.20. Downgrading with `pip install "numpy<1.20"`should resolve this issue.

Hi,teacher! I solve the problem when i downgrade the numpy. But when i run 'tombo detect_modifications level_sample_compare' i meet another problem.Can you give me some advice ?Thank you very much !
![12](https://user-images.githubusercontent.com/73151161/122212672-b46a7480-ceda-11eb-9d94-27a56d35a532.PNG)

**Comment by marcus1487** [comment]
I believe this bug has been fixed in the most recent version of tombo. Please upgrade to confirm.

**Comment by marcus1487** [comment]
This issue can be tracked in https://github.com/nanoporetech/tombo/issues/352
