### ISSUE TITLE
detect_modifications WARNING: Tombo index file does not exist for one or more directories. 

### ISSUE THREAD

**Issue by Derryxu** [nanoporetech/tombo#361]
Hi, After running resquiggle, I am trying to perform a modified base analysis with tombo's "detect_modifications" command. Unfortunately, I am getting a warning that a tombo index file does not exist. And the resulting.tombo.stat file was only 10KB. Then, I open the.tombo.stat file with HDFView，it is empty. Then I invoke the option --corrected-group RawGenomeCorrected_001，the result is still the same. 

I have checked all the directories involved in my resquiggle command, and there is tomobo.index file in my current folder. 
Any help would be appreciated, thanks.

```
(ont-tombo) xujr@ubuntu:/homec/xujr/nano_data/Synthesised_DRS$ tombo detect_modifications de_novo --fast5-basedirs /guppy_unmod_rep2/ --corrected-group RawGenomeCo
rrected_001 --statistics-file-basename MINES/guppy_unmod_rep2 --processes 100
[16:01:34] Parsing Tombo index file(s).
******************** WARNING ********************
        Tombo index file does not exist for one or more directories.
                If --skip-index was not set for re-squiggle command, ensure that the specified directory is the same as for the re-squiggle command.
[16:01:34] Performing de novo model testing against canonical model.
[16:01:34] Calculating read coverage regions.
[16:01:34] Calculating read coverage.
[16:01:34] Performing modified base detection across genomic regions.
0it [00:00, ?it/s]
(ont-tombo) xujr@ubuntu:/homec/xujr/nano_data/Synthesised_DRS$
```
![image](https://user-images.githubusercontent.com/26498301/125048316-5e03e680-e0d2-11eb-8373-c4b58cf29deb.png)

**Comment by patbohn** [comment]
It looks to me like you have an extra "/" in front of your --fast5-basedirs directory (i.e. it is right now a full file path looking for the folder guppy_unmod_rep2 in root directory. Try 

`--fast5-basedirs guppy_unmod_rep2/`

instead (for relative filepath) or

`--fast5-basedirs /homec/xujr/nano_data/Synthesised_DRS/guppy_unmod_rep2/`

for the full file path.

**Comment by Derryxu** [comment]
Thank you so much!
