### ISSUE TITLE
How to use multiple threads to run ont-Tombo

### ISSUE THREAD

**Issue by mantonglaw** [nanoporetech/tombo#367]
I have a sample of DRS nanopore sequceing. I find that there are 4,217,054 reads in the dataset. I ran the following command

tombo preprocess annotate_raw_with_fastqs --fast5-basedir \
/share/home/lius/tredata/T076_methylation_test/total/fast5_lns2 \
--fastq-filenames /share/home/lius/tredata/T076/after_guppy_file/pass/*.fastq \
--overwrite --processes 1 \
--sequencing-summary-filenames /share/home/lius/tredata/T076/after_guppy_file/sequencing_summary.txt

24 hours passed, but the program is still running.

Are there any methods to set multi-threads to run the program?
Or could you give me some advices to run the program faster?

**Comment by jouhpf** [comment]
Hello，I have the same question as you asked before. Have you had any solutions to this problem?  Is there a method to use multiple threads to run ont-Tombo?
