### ISSUE TITLE
python compatibility

### ISSUE THREAD

**Issue by PanZiwei** [nanoporetech/tombo#373]
Hi,
I noticed that Tombo is compatible with python at most 3.6, since the end of support for python = 3.6 is the end of this year(2021-12-23) [notice link](https://www.python.org/downloads/), have you ever consider upgrade the compatibility of Tombo to the latest version?

Thanks!

**Comment by marcus1487** [comment]
We will unfortunately not have the bandwidth for this task. We are working on replacements for Tombo internally, as there are too many core issues with Tombo to continue support. As such Tombo support is likely to end with a replacement software in the relatively near future.

**Comment by PanZiwei** [comment]
Thanks for the information. Looking forward to the replacement software and wish it can continue the support of the re-squiggle feature in the Tombo if possible.

**Comment by marcus1487** [comment]
Yes. The replacement for Tombo will absolutely support a resquiggle-like command, hopefully in a much more robust framework!
