### ISSUE TITLE
Question re: mapper

### ISSUE THREAD

**Issue by niphilli** [nanoporetech/tombo#38]
Hello Marcus.  I am having a problem getting my reads to map in tombo.  We generated a test set for detection of a new modified base (two samples: one with canonical bases and one with modified bases at known positions) using ligated synthetic oligonucleotides. I am having issues with mapping these data in tombo--it is a repetitive reference (~155bp repeat) with known locations of modified bases.  The number of repeats is variable in the data.  Using BWA-MEM, I am able to map to the 155bp repeat motif as a reference without problem; however, essentially none of my reads are mapping to the same reference with the built-in minimap2. I understand from previous posts that the mapping parameters are not yet accessible to users, but I was curious if you may have an alternative solution in mind. I have been playing around with the reference sequence, but am not having any luck. Thanks in advance--your active role here has been very helpful!

**Comment by marcus1487** [comment]
While the mapping parameters are not accessible you can modify some parameters at the minimap2 index stage and pass this index to Tombo via the `--minimap2-index` option. As @JohnUrban noted in [this comment](https://github.com/nanoporetech/tombo/issues/28#issuecomment-365749821), he was able to do some work in tuning the `-k` and `-w` parameters to minimap2. The mapping setting `map-ont` is set internally to Tombo and cannot be changed, but hopefully by playing around with the `-k` and `-w` parameters to minimap2 you might be able to get better mappings.

John did notice that changing these parameters can result in drastically increased runtimes, but in your case it sounds as thought the reference might be quite short and thus less of an issue. I don't have any experience tuning these parameters personally, but hopefully this path might help you in this case. 

Best of luck mod-base hunting!

**Comment by niphilli** [comment]
Got it...did some tweaking and was able to improve mapping. Thanks a million! And thanks to @JohnUrban.

**Comment by niphilli** [comment]
Hi Marcus...I have run into the need again to pass the .idx file from minimap2 to tombo after tweaking the k and w parameters.  I am getting the following error:
` tombo: error: unrecognized arguments: --minimap-index Synthetic_Oligo_3_reference_k12w8.idx`
Thoughts?  Thanks in advance!
