### ISSUE TITLE
Tombo resquiggle error

### ISSUE THREAD

**Issue by AnWiercze** [nanoporetech/tombo#381]
Hi, 

I basecalled direct RNA-seq reads from a MinION seq. run with guppy (see command below) and now I'm trying to do resquiggling in order to detect RNA modification based on raw current. 

1. I first directly tried to use **tombo resquiggle** with the --basecall-group flag and the fast5 output folder (workspace) from guppy which should contain the basecalled reads, but I got the following Error:

```
tombo resquiggle --rna --basecall-group Basecall_1D_001 --num-most-common-errors 5 guppy_output/workspace reference.fa
[09:13:33] Loading minimap2 reference.
[09:13:33] Getting file list.
******************** ERROR ********************
	Reads do not to contain basecalls. Check --basecall-group option if basecalls are stored in non-standard location or use `tombo preprocess annotate_raw_with_fastqs` to add basecalls from FASTQ files to raw FAST5 files.
```

2. Then I tried to run **tombo preprocess annotate_raw_with_fastqs** which revealed many Warnings and 0 added sequences: 
```
tombo preprocess annotate_raw_with_fastqs --fast5-basedir guppy_output/workspace --fastq-filenames dRNA.fastq --basecall-group Basecall_1D_001 --overwrite --sequencing-summary-filenames guppy_output/sequencing_summary.txt --processes 8
[09:19:24] Getting read filenames.
[09:19:24] Parsing sequencing summary files.
******************** WARNING ********************
	Some FASTQ records from sequencing summaries do not appear to have a matching file.
[09:19:37] Annotating FAST5s with sequence from FASTQs.
****** WARNING ****** Some read files could not be accessed.                                                                                                                                                       
****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.                                                                                        
****** WARNING ****** Basecalls exsit in specified slot for some reads. Set --overwrite option to overwrite these basecalls.                                                                                       
  0%|                                                                                                                                                                                   | 0/393914 [30:30<?, ?it/s]
[09:50:08] Added sequences to a total of 0 reads.
******************** WARNING ********************
	Not all read ids from FAST5s or sequencing summary files were found in FASTQs.
		This can result from reads that failed basecalling or if full sets of FAST5s/sequence summaries are not processed with full sets of FASTQs.
```
Does someone know what is the problem here? Is there something wrong with the fast5 files? I haven't found any solution for this problem, yet! 

Thanks for your help! 
Anna

_Guppy command:_
```
guppy_basecaller \
      --input_path fast5_files_minknow \
      --save_path guppy_output \
      --fast5_out \
      --compress_fastq \
      --device cuda:0,1:50% \
      --config rna_r9.4.1_70bps_hac.cfg \
      --reverse_sequence 1 \
      --u_substitution 1 \
      --calib_detect \
      -r \
      --trim_strategy none
```

**Comment by ky66** [comment]
Same issue.

**Comment by SamMcGreig** [comment]
Hi,

I was able to fix this issue by first converting the multi fast5 files into single fast 5 files (`pip install ont-fast5-api`), and putting all of these single fast 5 files into one directory. I then updated the sequencing summary file from guppy to from:

filename	read_id
AJC342_3ffeecd9_2.fast5	169589ff-1053-4562-b56b-f5a5453312d3
AJC342_3ffeecd9_2.fast5	f50eb19e-b5c5-4bff-b796-6e7c1c39dd11

to:

filename	read_id
169589ff-1053-4562-b56b-f5a5453312d3.fast5	169589ff-1053-4562-b56b-f5a5453312d3
f50eb19e-b5c5-4bff-b796-6e7c1c39dd11.fast5	f50eb19e-b5c5-4bff-b796-6e7c1c39dd11

I then ran:

`tombo preprocess annotate_raw_with_fastqs --fast5-basedir fast5_A_single/All --fastq-filenames SampleA.fastq --processes 4 --sequencing-summary-filenames sequencing_summaryA_modified.txt --overwrite`

`[16:05:30] Getting read filenames.
[16:05:31] Parsing sequencing summary files.
[16:05:31] Annotating FAST5s with sequence from FASTQs.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2656/2656 [00:10<00:00, 254.53it/s]
[16:05:41] Added sequences to a total of 2656 reads.
`

Hope this helps!

**Comment by ky66** [comment]
@SamMcGreig Your solution works. Thanks so much ... did not know I had to change the summary file. Saved me a week of work!

**Comment by AnWiercze** [comment]
@SamMcGreig Thanks a lot! That works! I wanted to avoid the multi-to-single fast5 conversion step since it takes forever to convert fast5s with >1 Gbp of reads in my case. But I guess I have to live with the fact that there is no resquiggling algorithm yet that works with multi fast5s.
