### ISSUE TITLE
Compiling error when installing with R version 3.4.3

### ISSUE THREAD

**Issue by AnjuniPeiris** [nanoporetech/tombo#39]
Hi,

Thanks for the great piece of software. Just noticed these error messages when trying to install Tombo with R version 3.4.3:

Command "python setup.py egg_info" failed with error code 1 in /short/sd34/ap5514/tmp/pip-build-nnfbxpry/rpy2/

/apps/R/3.4.3/lib64/R/bin/exec/R: symbol lookup error: /apps/intel-ct/2018.1.163/cc/../common/lib/libirng.so: undefined symbol: __intel_skx_avx512_memcpy

subprocess.CalledProcessError: Command '('/apps/R/3.4.3/lib64/R/bin/R', '--version')' returned non-zero exit status 127

The installation didn't work with R/3.4.3 but it worked with R/3.4.0 so it might just be a compiling error with the newest version of R.

**Comment by marcus1487** [comment]
I'm glad you are pleased with Tombo! Always good to hear that.

This certainly looks like a compiling error between rpy2 and this newest version of R. I am not able to reproduce this error on my local machine though. I am able to install Tombo against the R version 3.4.3, so I think this might be another installation issue. The exit status 127 mean "command not found", so this might be an issue with where rpy2 is looking for your R installation. Best of luck!
