### ISSUE TITLE
Error estimating reference

### ISSUE THREAD

**Issue by niphilli** [nanoporetech/tombo#41]
Hello! Running **estimate_reference** and am getting the following error: 

ValueError: need at least one array to concatenate

Ideas? I am sure it is something silly...maybe just a usage error.  Resquiggle and plotting functions are working fine.  Thanks in advance!

**Comment by marcus1487** [comment]
My guess would be that maybe there aren't any locations with the minimum read coverage and that is causing an empty list at some point. This could even be just on one chromosome. Would you mind posting the full stack trace? That would help me track down exactly what might be causing this issue.

**Comment by marcus1487** [comment]
Taking a quick look through the code, I think it might be [this line](https://github.com/nanoporetech/tombo/blob/1.2.1/tombo/tombo_stats.py#L511) that is causing this issue. I will add a fix to catch this error and report a useful error message.

In terms of fixing this in your case, I think you might have a a sample where some k-mer is never observed covered by `--minimum-test-reads`. If you can confirm that much of your sample is covered by `--minimum-test-reads`, then I would suggest to lower the size of the k-mer being fitted via the `--upstream-bases` and `--downstream-bases` options at least to confirm that this is the issue. The other option would be to lower the `--minimum-test-reads` values, but note that this might result in a poorly fit model.

**Comment by marcus1487** [comment]
I just pushed a potential fix for this issue. If you could install from the github repo, I hope that this might address this issue.

**Comment by niphilli** [comment]
I’ve been out of the office most of the afternoon...I will be working on this again first thing tomorrow, and I’ll circle back. Thanks for the prompt response.

**Comment by niphilli** [comment]
Hello...sorry for the delayed response.  I was able to download and install the modification from github, and the new error message displayed appropriately.  I think I have pinpointed the problem in my reference, and you are right, there were unrepresented/low coverage k-mers.  Now, strangely, I am getting an error on resquiggle attempts that I was not encountering before the install from github.  

![image](https://user-images.githubusercontent.com/19784719/37569611-13ab47dc-2ab3-11e8-9bed-4c1261ecb764.png)
 (apologies for the screenshot--working on a remote server)

Any ideas?  I am having trouble chasing down the problem...this is an exact command that I ran prior to the software revision with no issues.  Would you prefer that I move this into a new thread?  I **really** appreciate all of your help!

**Comment by marcus1487** [comment]
Ah. This appears to be a python2 bug that slipped through the cracks. I will push a fix for this shorty. Thank you for the bug report!

**Comment by niphilli** [comment]
that's great. thank you!

**Comment by marcus1487** [comment]
This issue has been resolved along with one other minor python2 bug from this release. I have pushed this as a micro release. The package available on pip is updated and the bioconda version should be updated shortly as well.
