### ISSUE TITLE
problem with --genome-locations input

### ISSUE THREAD

**Issue by khatamimaryam** [nanoporetech/tombo#42]
Hello Marcus.
First of all, thanks for the efforts of tombo software.

I have a simple question about 'plot_per_read' command. I am interested in reads from:
plasmid:pFMP233
segment:601_25mer
I write the following command but honestly not sure about input for --genome-locations:

tombo plot_per_read --per-read-statistics-filename sample.5mC.tombo.per_read_stats --genome-fasta /path2/pFMP233.fa --fast5-basedirs /path2/FAST5s/ --genome-locations pFMP233|601_25mer:3750 pFMP233|601_25mer:3760:+

and I got this error:

601_25mer:3760:+: command not found
601_25mer:3750: command not found
Parsing genome locations.
Traceback (most recent call last):
  File "/miniconda3/bin/tombo", line 6, in <module>
    sys.exit(tombo.__main__.main())
  File "/miniconda3/lib/python3.6/site-packages/tombo/__main__.py", line 174, in main
    plot_commands.plot_main(args)
  File "/miniconda3/lib/python3.6/site-packages/tombo/plot_commands.py", line 2215, in plot_main
    plot_per_read_mods_genome_location(*base_args, **kwargs)
  File "/miniconda3/lib/python3.6/site-packages/tombo/plot_commands.py", line 1542, in plot_per_read_mods_genome_location
    chrm, pos, strand = chrm_pos_strand
ValueError: not enough values to unpack (expected 3, got 1)

Any ideas?
Thanks in advance.

**Comment by marcus1487** [comment]
I'm glad that you have found Tombo useful! Always good to hear!

I believe that this is a unix command line issue. My guess is that the `|` characters in the sequence identifiers are being parsed by unix as a pipe. You should be able to quote the genome locations and (I hope) solve this issue. The command would look like this:

```
tombo plot_per_read --per-read-statistics-filename sample.5mC.tombo.per_read_stats \
    --genome-fasta /path2/pFMP233.fa --fast5-basedirs /path2/FAST5s/ \
    --genome-locations "pFMP233|601_25mer:3750" "pFMP233|601_25mer:3760:+"
```

 I will add a better error message to the genome locations parser to make this error a bit easier to diagnose.

**Comment by khatamimaryam** [comment]
Thanks a lot for the prompt answer and for the guide. 
Yes it is solved with this hint:)

**Comment by amy1847** [comment]
Hi Marcus/Tombo community.

I have run the alternate model for 5mC (RNA). I would now like to hone in on a particular transcript/genome location of interest to view the likelihood of each C being modified. If the transcript/gene of interest is on chromosome 1, position 2345, would I input this as chr1_2345? Also, when I tried using the above command "tombo plot_per_read" I receive the error message tombo: error: argument service_command: invalid choice: 'plot_per_read'. I am using Ubuntu. As I am new to Tombo, could I please have an example set of commands (if they differ from the ones above)? 

Thanks

**Comment by marcus1487** [comment]
RNA Tombo commands should be applied to a transcriptome, so the positions should be relative to the sequence record names from the provided reference FASTA. For use with Tombo commands this could be something like "gene1:100" to center on the 100th base of "gene1". You can find more information about processing direct RNA with Tombo [here](https://nanoporetech.github.io/tombo/rna.html).

The `tombo plot_per_read` command should be updated to `tombo plot per_read`. The Tombo command structure changed as of version 1.3 to hopefully make the command line help a bit easier to navigate ([1.3 release note](https://github.com/nanoporetech/tombo/releases/tag/1.3)).
