### ISSUE TITLE
Tombo installation issue with bioconda

### ISSUE THREAD

**Issue by szakallasn3** [nanoporetech/tombo#430]
Dear All, 

I have some issues with the installation of tombo with bioconda. I read from previous issue posts, that the version of python and the update of conda could resolve the problem, however these did not work for me. I also rearranged properly the conda channels, that also did not solve it. Could somebody give me some tips regarding this or does anybody has the solution? Or should I install tombo with pip instead? 

Many thanks

**Comment by kenneditodd** [comment]
@szakallasn3 Can you show your error message? I recently re-installed miniconda3 and can install it in my environment no problem. However, my problem is i'm having trouble getting tombo preprocess to run with my reformatted guppy output.

**Comment by kenneditodd** [comment]
@szakallasn3 What version are you using? I recently reinstalled miniconda3 and was able to create a new environment and install tombo.

Conda version
```
$ conda -V
conda 23.3.1
```

Conda channels
```
$ conda config --show channels
channels:
  - conda-forge
  - bioconda
  - defaults
```

Create an tombo_env.yml file containing the text below.
```
name: tombo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - backports=1.0=pyhd8ed1ab_3
  - backports.zoneinfo=0.2.1=py37h540881e_5
  - binutils_impl_linux-64=2.39=he00db2b_1
  - binutils_linux-64=2.39=h5fc0e48_13
  - biopython=1.79=py37h540881e_2
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.5.7=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h6cf1ce9_1008
  - colorama=0.4.6=pyhd8ed1ab_0
  - curl=7.86.0=h2283fc2_1
  - expat=2.5.0=hcb278e6_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hca18f0e_1
  - fribidi=1.0.10=h36c2ea0_0
  - future=0.18.2=py37h89c1867_5
  - gcc_impl_linux-64=9.5.0=h99780fb_19
  - gcc_linux-64=9.5.0=h4258300_13
  - gettext=0.21.1=h27087fc_0
  - gfortran_impl_linux-64=9.5.0=hf1096a2_19
  - gfortran_linux-64=9.5.0=hdb51d14_13
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.6=he838d99_2
  - gxx_impl_linux-64=9.5.0=h99780fb_19
  - gxx_linux-64=9.5.0=h43f449f_13
  - h5py=3.7.0=nompi_py37hf1ce037_101
  - harfbuzz=3.1.1=h83ec7ef_0
  - hdf5=1.12.2=nompi_h4df4325_100
  - icu=68.2=h9c3ff4c_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h0b41bf4_3
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h08a2579_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - libblas=3.9.0=17_linux64_openblas
  - libcblas=3.9.0=17_linux64_openblas
  - libcurl=7.86.0=h2283fc2_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=9.5.0=h0a57e50_19
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libglib=2.76.3=hebfc3b9_0
  - libgomp=13.1.0=he5830b7_0
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=17_linux64_openblas
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libpng=1.6.39=h753d276_0
  - libsanitizer=9.5.0=h2f262e1_19
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=9.5.0=h0a57e50_19
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.2.0=hf544144_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.0=h0b41bf4_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.9.12=h72842e0_0
  - libzlib=1.2.13=h166bdaf_4
  - make=4.3=hd18ef5c_1
  - mappy=2.26=py37ha26db04_0
  - markupsafe=2.1.1=py37h540881e_1
  - ncurses=6.4=hcb278e6_0
  - numpy=1.21.6=py37h976b520_0
  - ont-fast5-api=4.1.1=pyhdfd78af_0
  - ont-tombo=1.5.1=py37r36h70f9b12_2
  - openssl=3.1.1=hd590300_1
  - packaging=23.1=pyhd8ed1ab_0
  - pango=1.48.10=h54213e6_2
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.40=hc3806b6_0
  - pip=23.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - progressbar33=2.4=py_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyfaidx=0.7.2.1=pyh7cba7a3_1
  - python=3.7.12=hf930737_100_cpython
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.7=3_cp37m
  - pytz-deprecation-shim=0.1.0.post0=py37h89c1867_2
  - pyvcf3=1.0.3=pyhdfd78af_0
  - r-assertthat=0.2.1=r36h6115d3f_2
  - r-backports=1.2.1=r36hcfec24a_0
  - r-base=3.6.3=hbcea092_8
  - r-bit=4.0.4=r36hcfec24a_0
  - r-bit64=4.0.5=r36hcfec24a_0
  - r-blob=1.2.1=r36h6115d3f_1
  - r-brio=1.1.2=r36hcfec24a_0
  - r-cachem=1.0.5=r36hcfec24a_0
  - r-callr=3.7.0=r36hc72bb7e_0
  - r-cli=2.5.0=r36hc72bb7e_0
  - r-colorspace=2.0_1=r36hcfec24a_0
  - r-crayon=1.4.1=r36hc72bb7e_0
  - r-dbi=1.1.1=r36hc72bb7e_0
  - r-dbplyr=2.1.1=r36hc72bb7e_0
  - r-desc=1.3.0=r36hc72bb7e_0
  - r-diffobj=0.3.4=r36hcfec24a_0
  - r-digest=0.6.27=r36h03ef668_0
  - r-dplyr=1.0.6=r36h03ef668_1
  - r-ellipsis=0.3.2=r36hcfec24a_0
  - r-evaluate=0.14=r36h6115d3f_2
  - r-fansi=0.4.2=r36hcfec24a_0
  - r-farver=2.1.0=r36h03ef668_0
  - r-fastmap=1.1.0=r36h03ef668_0
  - r-generics=0.1.0=r36hc72bb7e_0
  - r-ggplot2=3.3.3=r36hc72bb7e_0
  - r-glue=1.4.2=r36hcfec24a_0
  - r-gridextra=2.3=r36h6115d3f_1003
  - r-gtable=0.3.0=r36h6115d3f_3
  - r-isoband=0.2.4=r36h03ef668_0
  - r-jsonlite=1.7.2=r36hcfec24a_0
  - r-labeling=0.4.2=r36h142f84f_0
  - r-lattice=0.20_44=r36hcfec24a_0
  - r-lifecycle=1.0.0=r36hc72bb7e_0
  - r-magrittr=2.0.1=r36hcfec24a_1
  - r-mass=7.3_54=r36hcfec24a_0
  - r-matrix=1.3_3=r36he454529_0
  - r-memoise=2.0.0=r36hc72bb7e_0
  - r-mgcv=1.8_35=r36he454529_0
  - r-munsell=0.5.0=r36h6115d3f_1003
  - r-nlme=3.1_152=r36h859d828_0
  - r-pillar=1.6.1=r36hc72bb7e_0
  - r-pkgconfig=2.0.3=r36h6115d3f_1
  - r-pkgload=1.2.1=r36h03ef668_0
  - r-plogr=0.2.0=r36h6115d3f_1003
  - r-praise=1.0.0=r36h6115d3f_1004
  - r-processx=3.5.2=r36hcfec24a_0
  - r-ps=1.6.0=r36hcfec24a_0
  - r-purrr=0.3.4=r36hcfec24a_1
  - r-r6=2.5.0=r36hc72bb7e_0
  - r-rcolorbrewer=1.1_2=r36h6115d3f_1003
  - r-rcpp=1.0.6=r36h03ef668_0
  - r-rematch2=2.1.2=r36h6115d3f_1
  - r-rlang=0.4.11=r36hcfec24a_0
  - r-rprojroot=2.0.2=r36hc72bb7e_0
  - r-rsqlite=2.2.5=r36h03ef668_0
  - r-rstudioapi=0.13=r36hc72bb7e_0
  - r-scales=1.1.1=r36h6115d3f_0
  - r-testthat=3.0.2=r36h03ef668_0
  - r-tibble=3.1.2=r36hcfec24a_0
  - r-tidyselect=1.1.1=r36hc72bb7e_0
  - r-utf8=1.2.1=r36hcfec24a_0
  - r-vctrs=0.3.8=r36hcfec24a_1
  - r-viridislite=0.4.0=r36hc72bb7e_0
  - r-waldo=0.2.5=r36hc72bb7e_0
  - r-withr=2.4.2=r36hc72bb7e_0
  - readline=8.2=h8228510_1
  - rpy2=2.9.4=py37r36hd767a1f_3
  - scipy=1.7.3=py37hf2a6cf1_0
  - sed=4.8=he412f7d_0
  - setuptools=67.7.2=pyhd8ed1ab_0
  - simplegeneric=0.8.1=py_1
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.42.0=h2c6b66d_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tar=1.34=hb2e2bae_1
  - tk=8.6.12=h27826a3_0
  - tktable=2.10=hb7b940f_3
  - tqdm=4.65.0=pyhd8ed1ab_1
  - tzdata=2023c=h71feb2d_0
  - tzlocal=4.2=py37h89c1867_1
  - wheel=0.40.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.4=h8ee46fc_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
  - pip:
      - cython==0.29.35
prefix: /tools/miniconda3/envs/tombo
```

Replicate this environment using the code below.
```
conda env create -f tombo_env.yml
```

**Comment by skranz0** [comment]
I had a lot of trouble installing tombo, too. For me it only worked with python 3.6

**Comment by Juni-H** [comment]
> 你用的是什么版本？我最近重新安装了 miniconda3，并能够创建一个新环境并安装 tombo。
> 
> Conda 版本
> 
> ```
> $ conda -V
> conda 23.3.1
> ```
> 
> Conda 频道
> 
> ```
> $ conda config --show channels
> channels:
>   - conda-forge
>   - bioconda
>   - defaults
> ```
> 
> 创建一个包含以下文本的tombo_env.yml文件。
> 
> ```
> name: tombo
> channels:
>   - conda-forge
>   - bioconda
>   - defaults
> dependencies:
>   - _libgcc_mutex=0.1=conda_forge
>   - _openmp_mutex=4.5=2_gnu
>   - _r-mutex=1.0.1=anacondar_1
>   - backports=1.0=pyhd8ed1ab_3
>   - backports.zoneinfo=0.2.1=py37h540881e_5
>   - binutils_impl_linux-64=2.39=he00db2b_1
>   - binutils_linux-64=2.39=h5fc0e48_13
>   - biopython=1.79=py37h540881e_2
>   - bwidget=1.9.14=ha770c72_1
>   - bzip2=1.0.8=h7f98852_4
>   - c-ares=1.19.1=hd590300_0
>   - ca-certificates=2023.5.7=hbcca054_0
>   - cached-property=1.5.2=hd8ed1ab_1
>   - cached_property=1.5.2=pyha770c72_1
>   - cairo=1.16.0=h6cf1ce9_1008
>   - colorama=0.4.6=pyhd8ed1ab_0
>   - curl=7.86.0=h2283fc2_1
>   - expat=2.5.0=hcb278e6_1
>   - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
>   - font-ttf-inconsolata=3.000=h77eed37_0
>   - font-ttf-source-code-pro=2.038=h77eed37_0
>   - font-ttf-ubuntu=0.83=hab24e00_0
>   - fontconfig=2.14.2=h14ed4e7_0
>   - fonts-conda-ecosystem=1=0
>   - fonts-conda-forge=1=0
>   - freetype=2.12.1=hca18f0e_1
>   - fribidi=1.0.10=h36c2ea0_0
>   - future=0.18.2=py37h89c1867_5
>   - gcc_impl_linux-64=9.5.0=h99780fb_19
>   - gcc_linux-64=9.5.0=h4258300_13
>   - gettext=0.21.1=h27087fc_0
>   - gfortran_impl_linux-64=9.5.0=hf1096a2_19
>   - gfortran_linux-64=9.5.0=hdb51d14_13
>   - graphite2=1.3.13=h58526e2_1001
>   - gsl=2.6=he838d99_2
>   - gxx_impl_linux-64=9.5.0=h99780fb_19
>   - gxx_linux-64=9.5.0=h43f449f_13
>   - h5py=3.7.0=nompi_py37hf1ce037_101
>   - harfbuzz=3.1.1=h83ec7ef_0
>   - hdf5=1.12.2=nompi_h4df4325_100
>   - icu=68.2=h9c3ff4c_0
>   - jinja2=3.1.2=pyhd8ed1ab_1
>   - jpeg=9e=h0b41bf4_3
>   - kernel-headers_linux-64=2.6.32=he073ed8_15
>   - keyutils=1.6.1=h166bdaf_0
>   - krb5=1.19.3=h08a2579_0
>   - ld_impl_linux-64=2.39=hcc3a1bd_1
>   - libblas=3.9.0=17_linux64_openblas
>   - libcblas=3.9.0=17_linux64_openblas
>   - libcurl=7.86.0=h2283fc2_1
>   - libedit=3.1.20191231=he28a2e2_2
>   - libev=4.33=h516909a_1
>   - libexpat=2.5.0=hcb278e6_1
>   - libffi=3.4.2=h7f98852_5
>   - libgcc-devel_linux-64=9.5.0=h0a57e50_19
>   - libgcc-ng=13.1.0=he5830b7_0
>   - libgfortran-ng=13.1.0=h69a702a_0
>   - libgfortran5=13.1.0=h15d22d2_0
>   - libglib=2.76.3=hebfc3b9_0
>   - libgomp=13.1.0=he5830b7_0
>   - libiconv=1.17=h166bdaf_0
>   - liblapack=3.9.0=17_linux64_openblas
>   - libnghttp2=1.52.0=h61bc06f_0
>   - libnsl=2.0.0=h7f98852_0
>   - libopenblas=0.3.23=pthreads_h80387f5_0
>   - libpng=1.6.39=h753d276_0
>   - libsanitizer=9.5.0=h2f262e1_19
>   - libsqlite=3.42.0=h2797004_0
>   - libssh2=1.11.0=h0841786_0
>   - libstdcxx-devel_linux-64=9.5.0=h0a57e50_19
>   - libstdcxx-ng=13.1.0=hfd8a6a1_0
>   - libtiff=4.2.0=hf544144_3
>   - libuuid=2.38.1=h0b41bf4_0
>   - libwebp-base=1.3.0=h0b41bf4_0
>   - libxcb=1.15=h0b41bf4_0
>   - libxml2=2.9.12=h72842e0_0
>   - libzlib=1.2.13=h166bdaf_4
>   - make=4.3=hd18ef5c_1
>   - mappy=2.26=py37ha26db04_0
>   - markupsafe=2.1.1=py37h540881e_1
>   - ncurses=6.4=hcb278e6_0
>   - numpy=1.21.6=py37h976b520_0
>   - ont-fast5-api=4.1.1=pyhdfd78af_0
>   - ont-tombo=1.5.1=py37r36h70f9b12_2
>   - openssl=3.1.1=hd590300_1
>   - packaging=23.1=pyhd8ed1ab_0
>   - pango=1.48.10=h54213e6_2
>   - pcre=8.45=h9c3ff4c_0
>   - pcre2=10.40=hc3806b6_0
>   - pip=23.1.2=pyhd8ed1ab_0
>   - pixman=0.40.0=h36c2ea0_0
>   - progressbar33=2.4=py_0
>   - pthread-stubs=0.4=h36c2ea0_1001
>   - pyfaidx=0.7.2.1=pyh7cba7a3_1
>   - python=3.7.12=hf930737_100_cpython
>   - python-tzdata=2023.3=pyhd8ed1ab_0
>   - python_abi=3.7=3_cp37m
>   - pytz-deprecation-shim=0.1.0.post0=py37h89c1867_2
>   - pyvcf3=1.0.3=pyhdfd78af_0
>   - r-assertthat=0.2.1=r36h6115d3f_2
>   - r-backports=1.2.1=r36hcfec24a_0
>   - r-base=3.6.3=hbcea092_8
>   - r-bit=4.0.4=r36hcfec24a_0
>   - r-bit64=4.0.5=r36hcfec24a_0
>   - r-blob=1.2.1=r36h6115d3f_1
>   - r-brio=1.1.2=r36hcfec24a_0
>   - r-cachem=1.0.5=r36hcfec24a_0
>   - r-callr=3.7.0=r36hc72bb7e_0
>   - r-cli=2.5.0=r36hc72bb7e_0
>   - r-colorspace=2.0_1=r36hcfec24a_0
>   - r-crayon=1.4.1=r36hc72bb7e_0
>   - r-dbi=1.1.1=r36hc72bb7e_0
>   - r-dbplyr=2.1.1=r36hc72bb7e_0
>   - r-desc=1.3.0=r36hc72bb7e_0
>   - r-diffobj=0.3.4=r36hcfec24a_0
>   - r-digest=0.6.27=r36h03ef668_0
>   - r-dplyr=1.0.6=r36h03ef668_1
>   - r-ellipsis=0.3.2=r36hcfec24a_0
>   - r-evaluate=0.14=r36h6115d3f_2
>   - r-fansi=0.4.2=r36hcfec24a_0
>   - r-farver=2.1.0=r36h03ef668_0
>   - r-fastmap=1.1.0=r36h03ef668_0
>   - r-generics=0.1.0=r36hc72bb7e_0
>   - r-ggplot2=3.3.3=r36hc72bb7e_0
>   - r-glue=1.4.2=r36hcfec24a_0
>   - r-gridextra=2.3=r36h6115d3f_1003
>   - r-gtable=0.3.0=r36h6115d3f_3
>   - r-isoband=0.2.4=r36h03ef668_0
>   - r-jsonlite=1.7.2=r36hcfec24a_0
>   - r-labeling=0.4.2=r36h142f84f_0
>   - r-lattice=0.20_44=r36hcfec24a_0
>   - r-lifecycle=1.0.0=r36hc72bb7e_0
>   - r-magrittr=2.0.1=r36hcfec24a_1
>   - r-mass=7.3_54=r36hcfec24a_0
>   - r-matrix=1.3_3=r36he454529_0
>   - r-memoise=2.0.0=r36hc72bb7e_0
>   - r-mgcv=1.8_35=r36he454529_0
>   - r-munsell=0.5.0=r36h6115d3f_1003
>   - r-nlme=3.1_152=r36h859d828_0
>   - r-pillar=1.6.1=r36hc72bb7e_0
>   - r-pkgconfig=2.0.3=r36h6115d3f_1
>   - r-pkgload=1.2.1=r36h03ef668_0
>   - r-plogr=0.2.0=r36h6115d3f_1003
>   - r-praise=1.0.0=r36h6115d3f_1004
>   - r-processx=3.5.2=r36hcfec24a_0
>   - r-ps=1.6.0=r36hcfec24a_0
>   - r-purrr=0.3.4=r36hcfec24a_1
>   - r-r6=2.5.0=r36hc72bb7e_0
>   - r-rcolorbrewer=1.1_2=r36h6115d3f_1003
>   - r-rcpp=1.0.6=r36h03ef668_0
>   - r-rematch2=2.1.2=r36h6115d3f_1
>   - r-rlang=0.4.11=r36hcfec24a_0
>   - r-rprojroot=2.0.2=r36hc72bb7e_0
>   - r-rsqlite=2.2.5=r36h03ef668_0
>   - r-rstudioapi=0.13=r36hc72bb7e_0
>   - r-scales=1.1.1=r36h6115d3f_0
>   - r-testthat=3.0.2=r36h03ef668_0
>   - r-tibble=3.1.2=r36hcfec24a_0
>   - r-tidyselect=1.1.1=r36hc72bb7e_0
>   - r-utf8=1.2.1=r36hcfec24a_0
>   - r-vctrs=0.3.8=r36hcfec24a_1
>   - r-viridislite=0.4.0=r36hc72bb7e_0
>   - r-waldo=0.2.5=r36hc72bb7e_0
>   - r-withr=2.4.2=r36hc72bb7e_0
>   - readline=8.2=h8228510_1
>   - rpy2=2.9.4=py37r36hd767a1f_3
>   - scipy=1.7.3=py37hf2a6cf1_0
>   - sed=4.8=he412f7d_0
>   - setuptools=67.7.2=pyhd8ed1ab_0
>   - simplegeneric=0.8.1=py_1
>   - six=1.16.0=pyh6c4a22f_0
>   - sqlite=3.42.0=h2c6b66d_0
>   - sysroot_linux-64=2.12=he073ed8_15
>   - tar=1.34=hb2e2bae_1
>   - tk=8.6.12=h27826a3_0
>   - tktable=2.10=hb7b940f_3
>   - tqdm=4.65.0=pyhd8ed1ab_1
>   - tzdata=2023c=h71feb2d_0
>   - tzlocal=4.2=py37h89c1867_1
>   - wheel=0.40.0=pyhd8ed1ab_0
>   - xorg-kbproto=1.0.7=h7f98852_1002
>   - xorg-libice=1.1.1=hd590300_0
>   - xorg-libsm=1.2.4=h7391055_0
>   - xorg-libx11=1.8.4=h8ee46fc_1
>   - xorg-libxau=1.0.11=hd590300_0
>   - xorg-libxdmcp=1.1.3=h7f98852_0
>   - xorg-libxext=1.3.4=h0b41bf4_2
>   - xorg-libxrender=0.9.10=h7f98852_1003
>   - xorg-renderproto=0.11.1=h7f98852_1002
>   - xorg-xextproto=7.3.0=h0b41bf4_1003
>   - xorg-xproto=7.0.31=h7f98852_1007
>   - xz=5.2.6=h166bdaf_0
>   - zlib=1.2.13=h166bdaf_4
>   - zstd=1.5.2=h3eb15da_6
>   - pip:
>       - cython==0.29.35
> prefix: /tools/miniconda3/envs/tombo
> ```
> 
> 使用以下代码复制此环境。
> 
> ```
> conda env create -f tombo_env.yml
> ```

thank you！！you are a great help!
