### ISSUE TITLE
call methylation site

### ISSUE THREAD

**Issue by duhuipeng** [nanoporetech/tombo#432]
Dear author

Can I go directly to call methylation of the modification sites on fast5 of the reads without relying on Ref and then extract the methylation information？Could you provide the operation of the process？

Best
HuipengDu

**Comment by kenneditodd** [comment]
@duhuipeng 
I am working on modification calling and got up to preprocess to work. I'm currently resquiggling but it's taking a while to run. Here are the steps I have done so far that are working.

1. Basecall with guppy
2. Create new environment and install tombo.
3. Use multi_to_single_fast5 (from ont_fast5_api) to convert your guppy multi-fast5 files (default output) to single-fast5.
4. Use the python code to fix your sequencing_summary.txt file
```
#!/usr/bin/python3

with open('sequencing_summary.txt') as file, open('sequencing_summary_fix.txt', 'w') as outfile:
    header = next(file)
    outfile.write(header)
    for line in file:
        line = line.split()
        line[0] = f"{line[1]}.fast5"
        line.append('\n')
        outfile.write("\t".join(line))
```
5. Run tombo preprocess
6. Run tombo resquiggle. Make sure you have the hdf5 plugin in order for this to work. Use the steps below for linux if you don't.
```
wget https://github.com/nanoporetech/vbz_compression/releases/download/v1.0.1/ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz
tar xvzf ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz
export HDF5_PLUGIN_PATH=/your/path/to/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin
```

**Comment by marcus1487** [comment]
Tombo is deprecated. See the top of the readme for recommended replacement tools.
