### ISSUE TITLE
preprocessing for tombo

### ISSUE THREAD

**Issue by meneki** [nanoporetech/tombo#433]
Hello.
I am not an English speaker, so I am not sure if my question will be well understood.

Also, this is my first time to do a direct RNA sequence using ONT nanopore, so maybe I am doing something wrong in the sequencing phase.

Devices used: flongle, RNA002

1. multi_to_single_fast5 --input_path <fast5_dir> --save_path <output_dir> --recursive
2. basecall using [FLO-MIN106 RNA002 - High-Accuracy] in MinKNOW GUI
3. tombo preprocess annotate_raw_with_fastqs --fast5-basedir <single_fast5_dir> --fastq-filenames <merged.fastq> --sequencing-summary- filenames <sequencing_summary.txt> --overwrite --processes 6

Then the following is displayed.
******************** WARNING ********************
        Not all read ids from FAST5s or sequencing summary files were found in FASTQs.
                This can result from reads that failed basecalling or if full sets of FAST5s/sequence summaries are not processed with full sets of FASTQs.

Does this error mean that it should not be used in the next stage of tombo resquiggle?

Thank you in advance for any help you may be able to provide.

**Comment by rugilemat** [comment]
Hi @meneki, did you manage to sort this out? I've been having the same problem.

**Comment by keenhl** [comment]
As a first step, you could do something like this to confirm that you have the same number of fast5 files and fastq sequences.

## count number of fast5 files

find single_fast5_dir -name "*fast5" | wc -l

## count number of fastq sequences

echo(gzip -dc merged.fastq.gz | wc -l)/4 | bc
