### ISSUE TITLE
Model sample compare with different lengths of DNA

### ISSUE THREAD

**Issue by SanityTree** [nanoporetech/tombo#436]
Hi this is more a question than an issue. I usually do model sample comparisons between an unmethylated and methylated sample to detect 5mC's, and that gives me a region of peaks and we can determine a methylation site based on what enzymes we are using. I am planning to do an experiment but due to some technical aspects the DNA I am using will always be methylated. I want to determine the methylation in the same way, however, the only unmethylated sample I can do is a shorter version of the same DNA. 

Will Tombo work if I use the same reference for the resquiggle, even if the methylated DNA is longer than the reference?

**Comment by marcus1487** [comment]
Tombo is deprecated. I would recommend transferring this analysis over to Remora.
