### ISSUE TITLE
Tombo for RNA modification prediction using direct RNA sequencing

### ISSUE THREAD

**Issue by gsukrit** [nanoporetech/tombo#438]
Hi Team, 

I have reads generated using Nanopore's direct RNA sequencing platform for a single sample. Can I get a compilation of all the commands / log to run tombo prediction for m5C and 6mA for RNA modifications without giving a second sample to compare, as the commands on the RNA processing documentation page are unclear. I have already basecalled my data using the MinKnow software in the high accuracy mode and have a list of fastq as well as bam files. Please let me know how to proceed further. 

I would greatly appreciate any help you could give me with this. 

Thanks,

**Comment by marcus1487** [comment]
Tombo is deprecated. We do not currently have a solution for m6A and m5C in RNA. We are hoping to produce an m6A model in the very near term that will be run-able in Remora and Dorado. For further research we suggest using the Remora signal analysis tools.
