### ISSUE TITLE
Unable to install ont-tombo via condo and pip

### ISSUE THREAD

**Issue by skranz0** [nanoporetech/tombo#439]
I want to compare multiple epigenetic tools and many of them require Tombo. Every installation tells my to install with either `pip install ont-tombo` or `conda install -c bioconda ont-tombo`. Neither way works.
The pip installation ends with 
`ERROR: Could not build wheels for ont-tombo, which is required to install pyproject.toml-based projects`
The condo installation gives me
```
UnsatisfiableError: The following specifications were found to be incompatible with the existing python installation in your environment: 

Specifications: 

- ont-tombo -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']                                                                                          

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.                                                        
When python appears to the right, that indicates that the thing on the left is somehow not available for the python version you are constrained to. Note that conda will not change your python version to a different minor version unless you explicitly specify that.
   
The following specifications were found to be incompatible with your system:
   
  - feature:/linux-64::__glibc==2.35=0                              
  - ont-tombo -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']                                                        
  - python=3.8 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.35
```

Python 3.8 is what the installation script of the tools want me to use. And to my understanding, that should satisfy >=3.7,<3.8.0a0

**Comment by GuardSkill** [comment]
same

**Comment by skranz0** [comment]
Thanks to a thread on [Reddit](https://www.reddit.com/r/bioinformatics/comments/15yy04b/trouble_installing_onttombo_for_epigenetic/), I learned tombo requires Python 3.6, even though the tools I'm trying to use state 3.8 in their install guides. With the downgraded Python `mamba install -c bioconda ont-tombo` is successfull though.
As one comment suggested, it might be reasonable to create an extra 3.6 environment just for tombo.

**Comment by marcus1487** [comment]
Tombo is deprecated. I would recommend trying to update pipelines to use Remora if possible.

**Comment by keenhl** [comment]
@skranz0 Thanks for the suggestion.  I had been trying unsuccessfully to get tombo installed with different versions of Python, with conda install, and with pip install, and nothing worked.  With Python 3.6 and the mamba install, it worked.
