### ISSUE TITLE
Resquiggle Process stuck at 0

### ISSUE THREAD

**Issue by AzlanNI** [nanoporetech/tombo#440]
Hello everyone, 

I am currently using Tombo v1.5 to analyze some bacterial methylation data. 
Since an Update to our basecaller my tombo requiggle run is stuck at 0% and does not continue. 

I tried: 
0. install tombo, etc.
1. basecall fast5 files with --fast5 option using guppy
2. convert to single fast5 files using ont_fast5_api
3. fastq -> fasta
4. run 'tombo resquiggle'
5. extract data from fast5 file and visualise

this procedure but the Results stay the same it is stuck at 0%. Now i have a question i heared of  vbz compression and HDF5 plugin. Should i ask the ppl who updated our basecallers if they installed this pluggin? Or is this a pluggin i have to install on the working device i want to run Tombo with ? 
Sorry if this question is very simple. 
my Command looks like this: 
module load Tombo 1.5

tombo resquiggle /path/to/fast5s/ /path/to/reference/fasta \
  --processes 8 --num-most-common-errors 5 --overwrite --ignore-read-locks

I am happy for any suggestions. Since we are struggling with this Problem now for some time! 
Kind regards, 
Azlan Nisar

**Comment by marcus1487** [comment]
Tombo is deprecated. I would strongly suggest switching your raw signal analysis and signal visualization tasks over to Remora.

**Comment by AzlanNI** [comment]
Hey marcus, 

Thanks for ur answer! So is it possible to do Bacterial Methylation Analysis with Guppy and the remora backend ? Last time i asked it was suggested to use Tombo.

**Comment by marcus1487** [comment]
Dorado provides all-context 5mC and 6mA modified base calling models (trained from Remora). modkit provides downstream processing functionalities. We are working hard towards a 4mC model as well, but do not have a model for public release at this time. This should complete the majority of bacterial methylation needs, but please do raise an issue in the appropriate repo if there are gaps in required analysis.

**Comment by keenhl** [comment]
@AzlanNI I get the same issue, resquiggle stuck on zero.  Did you find a solution to the problem? Thanks.
