### ISSUE TITLE
Tombo preprocess error

### ISSUE THREAD

**Issue by keenhl** [nanoporetech/tombo#444]
When I run the following command

tombo preprocess annotate_raw_with_fastqs \
--fast5-basedir ../single_fast5 \
--fastq-filenames merged.fastq.gz

Everything gets to 100%, and then there is an error.  Any thoughts about this.  I'm going to check if unzipping the fastq file will fix the problem. I will provide an update.  Thanks.

100%|██████████| 706499/706499 [4:53:11<00:00, 40.16it/s]
[17:51:46] Annotating FAST5s with sequence from FASTQs.
0it [00:00, ?it/s]Process Process-4:
Traceback (most recent call last):
  File "/Users/keenhl/miniconda3/envs/tombo_2/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/keenhl/miniconda3/envs/tombo_2/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/keenhl/miniconda3/envs/tombo_2/lib/python3.6/site-packages/tombo/_preprocess.py", line 148, in _feed_seq_records_worker
    fastq_rec = list(islice(fastq_fp, 4))
  File "/Users/keenhl/miniconda3/envs/tombo_2/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by keenhl** [comment]
If I unzip the fastq file, the error above goes away.

I do get the following error.  So why are the read ids in the fastq file not matching the reads in the fast5 files?


[18:46:42] Annotating FAST5s with sequence from FASTQs.
****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.
0it [00:22, ?it/s]
[18:47:05] Added sequences to a total of 0 reads.

**Comment by NoguchiRyo** [comment]
Hi. I also got this error and somehow solved it. It seems the bug is not fixed if you install tombo from conda.
I changed the line 378 in "tombo/_preprocess.py" like this.

before:
`with h5py.File(fast5_fn) as fast5_data:`

after:
`with h5py.File(fast5_fn, 'r+') as fast5_data:`

Then it worked.

**Comment by keenhl** [comment]
Thank you very much. That's very helpful. I will see if this works for me and come back and provide an update.

**Comment by keenhl** [comment]
@NoguchiRyo I just test the modification suggested.  It completely solved the problem.  Thank you so so much.  Here is the exact code that I ran.


```
conda activate tombo_2

tombo preprocess annotate_raw_with_fastqs \
--fast5-basedir ./128/ \
--overwrite \
--fastq-filenames FAW42444_pass_4d4af51e_82807403_100.fastq
```
