### ISSUE TITLE
Cannot annotate fast5

### ISSUE THREAD

**Issue by JSluo888** [nanoporetech/tombo#457]
I have some nanopore sequences stored in pod5s. 

I first converted pod5 to fast5, then used multi-to-single-fast5 command to have single-read fast5s, then I try to annotate the fast5 using the fastq file from Dorado basecaller. 

And I got the following error message:
```
[12:43:40] Annotating FAST5s with sequence from FASTQs.
****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.
0it [00:46, ?it/s]
[12:44:27] Added sequences to a total of 0 reads.
```
Should Tombo be working well with Dorado?

**Comment by marcus1487** [comment]
Tombo is deprecated and not supported as noted in the readme. Please open an issue in the relevant repository if there are features missing for replacements for Tombo features. Raw signal analysis tasks are now supported by Remora.
