### ISSUE TITLE
Setting up Tombo

### ISSUE THREAD

**Issue by cweldo00** [nanoporetech/tombo#46]
I need help to install Tombo onto my Mac laptop.

The error message is attached below:

![tombo issue](https://user-images.githubusercontent.com/32604538/37836170-be4a2ce0-2ea9-11e8-9bdd-ee3b94a2c95a.jpg)
 
Regards,

Carika

**Comment by marcus1487** [comment]
For the `full` `pip` installation the `R` programming language needs to be installed first (a pre-requisite for the `rpy2` dependency). Tombo can be installed without plotting functionality by omitting the `[full]` bit on the end of the pip install command. As noted at the [end of the README here](https://github.com/nanoporetech/tombo#advanced-installation-instructions), this allows the detection of modified bases and output via genome-browser (wiggle format), but not any plotting functions.

For R installation on a mac, there are a number of options. [Homebrew](http://formulae.brew.sh/repos/Homebrew/homebrew-core/formula/r) and [conda](https://anaconda.org/r/r) are probably 2 of the easier ways to perform this installation on a mac, although there are certainly many other methods to install R on a system. Best of luck and let me know if you have any further difficulty!

**Comment by cweldo00** [comment]
Dear Marcus,

Thank you very much.  I am now struggling to know If I have Homebrew or not.  I am sure I downloaded it last summer already.  How can I check?

Also I want to detect signal changes between normal RNA and RNA that has all guanines with the modification. Do I need the plotting functions for this?

Regards,

Carika

On 23 Mar 2018, at 15:19, Marcus Stoiber <notifications@github.com<mailto:notifications@github.com>> wrote:


For the full pip installation the R programming language needs to be installed first (a pre-requisite for the rpy2 dependency). Tombo can be installed without plotting functionality by omitting the [full] bit on the end of the pip install command. As noted at the end of the README here<https://github.com/nanoporetech/tombo#advanced-installation-instructions>, this allows the detection of modified bases and output via genome-browser (wiggle format), but not any plotting functions.

For R installation on a mac, there are a number of options. Homebrew<http://formulae.brew.sh/repos/Homebrew/homebrew-core/formula/r> and conda<https://anaconda.org/r/r> are probably 2 of the easier ways to perform this installation on a mac, although there are certainly many other methods to install R on a system. Best of luck and let me know if you have any further difficulty!

**Comment by cweldo00** [comment]
I tried to install just the combo without the [full] command and it gave this error:

[cid:96631AAC-A5F7-474C-BBD9-7BA3353D814E@tenant.dmu.ac.uk]

On 23 Mar 2018, at 15:19, Marcus Stoiber <notifications@github.com<mailto:notifications@github.com>> wrote:


For the full pip installation the R programming language needs to be installed first (a pre-requisite for the rpy2 dependency). Tombo can be installed without plotting functionality by omitting the [full] bit on the end of the pip install command. As noted at the end of the README here<https://github.com/nanoporetech/tombo#advanced-installation-instructions>, this allows the detection of modified bases and output via genome-browser (wiggle format), but not any plotting functions.

For R installation on a mac, there are a number of options. Homebrew<http://formulae.brew.sh/repos/Homebrew/homebrew-core/formula/r> and conda<https://anaconda.org/r/r> are probably 2 of the easier ways to perform this installation on a mac, although there are certainly many other methods to install R on a system. Best of luck and let me know if you have any further difficulty!

**Comment by marcus1487** [comment]
You should be able to tell if Homebrew is installed with the `brew -h` to print the help message.

As for the plotting commands, I find them very helpful to see if the signal assignments look reasonable. They are not strictly required in order to detect deviations in signal between two samples, but the visualizations can be quite helpful to understand the shifts in signal.

**Comment by cweldo00** [comment]
I checked if Homebrew is there.  I think its safe to say it is?


On 23 Mar 2018, at 15:33, Marcus Stoiber <notifications@github.co<mailto:notifications@github.co>[cid:72DA45CB-859A-441D-9348-45CAE8F267F3@tenant.dmu.ac.uk]m> wrote:


You should be able to tell if Homebrew is installed with the brew -h to print the help message.

As for the plotting commands, I find them very helpful to see if the signal assignments look reasonable. They are not strictly required in order to detect deviations in signal between two samples, but the visualizations can be quite helpful to understand the shifts in signal.

**Comment by cweldo00** [comment]
Here is the full output
[cid:285653B3-C572-483B-B2F8-B34D7ED9CDBE@tenant.dmu.ac.uk]

On 23 Mar 2018, at 15:35, Marcus Stoiber <notifications@github.com<mailto:notifications@github.com>> wrote:


For the conda error, I am not sure about this error. Would you mind posting the full installation command as well as the full output resulting in this error?

**Comment by marcus1487** [comment]
Is this a link? maybe the link is broken. I don't see any error message here.

**Comment by cweldo00** [comment]
<img width="570" alt="pastedgraphic-4" src="https://user-images.githubusercontent.com/32604538/37839110-8a6b3f06-2eb1-11e8-8def-72eee49463b0.png">

**Comment by marcus1487** [comment]
How about the base pip instal (without the `[full]` bit)?

**Comment by cweldo00** [comment]
![tombo issue](https://user-images.githubusercontent.com/32604538/37841161-e7e08b28-2eb6-11e8-871e-d816f50be562.jpeg)
 This is what it looks like

**Comment by marcus1487** [comment]
This certainly looks like a pip permissions local setup issue and not really a Tombo issue. This is the main reason for the conda install recommendation as the permission structure is much more reliable.

**Comment by cweldo00** [comment]
Ok. Thank you!

**Comment by marcus1487** [comment]
One other quick tip that might help the permissions issue is to use the `--user` option to `pip install`. Hopefully that might help get you going.

**Comment by cweldo00** [comment]
I am currently downloading Anacondo.  Hopefully it works that way as the pip install is beyond my knowledge.

**Comment by cweldo00** [comment]
I now have the GUI of Anaconda.  I am guessing I don't need to use the command line to install Tombo.  Is there somewhere where I can find what to do next?

![anaconda](https://user-images.githubusercontent.com/32604538/37845084-8b583c38-2ec1-11e8-9833-01599395b68a.jpeg)

**Comment by marcus1487** [comment]
I have never used the conda GUI before, so I'm afraid I can't be of much help there. You might be able to install Tombo from this application, but Tombo is a command line utility. You should be able to install tombo from the command line using the [command from the README](https://github.com/nanoporetech/tombo#installation) if conda is now installed. `conda install -c bioconda ont-tombo` is the install command from the command line.

**Comment by cweldo00** [comment]
It seems this Tombo installation is just not working for me today.  I used the command line you just sent and its saying there is a conflict? I am really sorry for bothering you so much.

This is a screenshot.
![conda issue](https://user-images.githubusercontent.com/32604538/37845902-efe2c310-2ec3-11e8-80b7-804fedc20c9b.jpeg)

**Comment by marcus1487** [comment]
Try to uninstall the offending package (`conda uninstall r-rjdbc`).

**Comment by cweldo00** [comment]
Its finally install! Thank you so much. I had to uninstall quite a lot of packages (~60).

**Comment by cweldo00** [comment]
How do you create the genome.fasta file? I am trying to run the command tombo resquiggle users/carika/desktop/minion/tombo/normal/fast5 genome.fasta --processes 4 but its saying it can't fine the genome.fasta file.  I have a file with the exact name genome.fasta in the same place as the fasta5 files.  

My sequence is a particular 682 nucleotides as my RNA is in vitro transcribed so I want this sequence as the reference. 

Thank you for your help in advance.
