### ISSUE TITLE
event mapping and normalization without resquiggling

### ISSUE THREAD

**Issue by JohnUrban** [nanoporetech/tombo#48]
Hi Marcus,

If you remember -- in the nanoraw days I asked about support for older chemistries:
https://github.com/marcus1487/nanoraw/issues/32

Essentially, I have older R7.3 data. Overall, I still need to look into that older data -- generating new data is not necessarily an option. 

For some of it, I have the raw data, which used to be stored in a separate file. In that thread, we discussed making a conversion script to make R7.3 files compatible w/ nanoraw. I never did get around to that. Did you ever make such a script? If not, any new thoughts on that?

For some of the older data, I do not have the raw data - and will have to rely on the original segmentation. To this point -- is there any way I can use Tombo to simply median normalize the events? That would be useful with or without mapping -- however, it would be most useful to map the reads, median normalize the events, and present them as re-squiggled events are presented in the fast5 by Tombo. Is there a way to do this? Is there any chance of adding a sub-command that doesn't re-squiggle with the raw data, but does map and median normalize? 

So overall, there are 2 issues here:
(i) Dealing w/ older data when I do have access to raw data to do the conversion
(ii) Dealing w/ older data when I can only use the events as is...

Many thanks for everything as usual.

Best,

  John

**Comment by marcus1487** [comment]
Hi John,

For the R7.3 conversion script, no I never did get around to making that script. As far as I can tell, this script would mostly be about annotating the R7 base called FAST5 files with the raw signal and ensuring that the correct read files were linked in this process.

As for processing reads without raw data, I don't foresee adding this to Tombo. There are several reasons for this. First is that the results would not work with a number of downstream Tombo commands, given that the raw signal does not exist. Second, the re-squiggle procedure would have to stop before actually assigning each base a bit of raw signal when this could not be determined from the events alone (this is likely to be a vast majority of reads). This again would cause unexpected output compared to the normal Tombo output and require special handling downstream.

For the median normalization, this could be added without much problem, but I'm not sure the results would hook up with any other Tombo commands (for the same reasons above), and so I don't foresee adding this functionality to Tombo. Aside from these issues, the median normalization may have adverse effects when performed at the event level as opposed to from the raw signal. I have not tested the difference between performing normalization from raw signal versus event signal, but this would have to be looked into as well.

For the older data with raw signal, I think the path forward would be to process the reads to mimic the R9 format (with raw and base called events in the same FAST5). To run the standard (event-less) re-squiggle method this would also require the production of a R7 median normalized model. I don't think that this will be added to Tombo either as it would involve a significant amount of work and new data is not likely to be produced for this sample type.

I hope you might be able to analyze the old data with raw signal at least, but there is not really an easy fix to be added to Tombo to enable this unfortunately. If you do end up writing the script to annotate R7 files to mimic R9, I would be happy to fold that in as a script into the Tombo repo as others might find this useful as well.

**Comment by JohnUrban** [comment]
Hi Marcus,

Thanks for your response. That all makes sense. 

I have been digging around what I thought contained the way data all morning, and it appears that raw data was only saved for Channel 1 in all of my bulk fast5 files. Otherwise I only have access to the events and the 'reads' denoting where each starts and ends in the events. So basically, I do not have the raw data like I thought.

For my purposes on this particular project, I don't need any of the downstream Tombo stuff. I'd love to just align the events to the genome and have them normalized in some way that they are comparable between reads, channels, runs, etc (median norm is not necessary per se). Then I can look at specific sites I know to be methylated. If I was really ambitious, it sounds like I'd be able to re-purpose some Tombo code to do what I want. However, it looks like nanopolish's eventalign can accomplish what I need (event mapping and normalization) - although I don't think it decorates the fast5 file with mapping information and the normalized events the way Tombo does. I believe it just spits out a text file or SAM/BAM. Either way I should be able to handle it.

Thanks again.

--John

**Comment by marcus1487** [comment]
Yes. It does sounds like nanopolish is more suited to this particular task. I do think you could jerry-rigged some of the Tombo API functions to help out here, but that would certainly require a good bit of work. Best of luck!
