### ISSUE TITLE
tombo resquiggle

### ISSUE THREAD

**Issue by Fairenough** [nanoporetech/tombo#5]
Does the command *tombo resquiggle* requires a dir for FAST5 and a reference fasta file for genome.fa?

**Comment by marcus1487** [comment]
I'm not sure I understand your question. The resquiggle command does require a directory of FAST5 files (or a nested set of directories) and a FASTA genome file to map the reads. The command also requires the executable for one of the supported mappers. Let me know if this answers your question.

**Comment by Fairenough** [comment]
Yes, your answer's right what I want to know. Another question, another question, why my reads all go to failed after resquiggle:

user@x499-desktop:/media/user/1- 10TB//Tombo$ tombo resquiggle fn/ mito-1.fa --minimap2-executable ./minimap2 --processes 4
Getting file list.
Correcting 59694 files with 1 subgroup(s)/read(s) each (Will print a dot for each 500 reads completed).
.......................................................................................................................
Failed reads summary (59694 total failed):
	Tombo data exsists in [--corrected-group] and [--overwrite] is not set :59694

One more thing to mention that I was trying to extract methylation from mitochoria DNA. So the FAST5 are only the signal level data from MT: https://github.com/nanopore-wgs-consortium/NA12878/blob/master/Genome.md. And the reference is the hg38 MT(about 16kb). Is that OK?

**Comment by marcus1487** [comment]
The resquiggle command writes the new signal to genomic base assignment back into the FAST5 file. If you run resquiggle twice then there will be data within the the default --corrected-group slot of the fast5. In order to keep users from overwriting results accidentally the --overwrite option must be set in order to overwrite the contents of this slot with another run (possibly with new options).

For the question about your biological sample, that is something I will leave up to the user. If the reads come from a different source than the passed genome there can certainly be issues with the output, but I cannot determine that for all settings. I will note that the reads must be basecalled (with albacore fast5 mode set) in order to be processed by tombo.

**Comment by Fairenough** [comment]
Hi Marcus,
I have used h5ls -r to view the structure of my fast5 file, do you think this is with the FASTQ slot and basecalled format? Can it be used as raw data for tombo?
h5ls -r DEAMERNANOPORE_20161117_FNFAB43577_MN16450_sequencing_run_MA_821_R9_4_NA12878_11_17_16_88738_ch1_read932_strand.fast5
/                        Group
/Analyses                Group
/Analyses/Basecall_1D_000 Group
/Analyses/Basecall_1D_000/BaseCalled_template Group
/Analyses/Basecall_1D_000/BaseCalled_template/Events Dataset {1020}
/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/Analyses/Basecall_1D_000/Configuration Group
/Analyses/Basecall_1D_000/Configuration/aggregator Group
/Analyses/Basecall_1D_000/Configuration/basecall_1d Group
/Analyses/Basecall_1D_000/Configuration/calibration_strand Group
/Analyses/Basecall_1D_000/Configuration/components Group
/Analyses/Basecall_1D_000/Configuration/event_detection Group
/Analyses/Basecall_1D_000/Configuration/general Group
/Analyses/Basecall_1D_000/Configuration/genome_mapping Group
/Analyses/Basecall_1D_000/Configuration/split_hairpin Group
/Analyses/Basecall_1D_000/Log Dataset {SCALAR}
/Analyses/Basecall_1D_000/Summary Group
/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/Analyses/Calibration_Strand_000 Group
/Analyses/Calibration_Strand_000/Configuration Group
/Analyses/Calibration_Strand_000/Configuration/aggregator Group
/Analyses/Calibration_Strand_000/Configuration/basecall_1d Group
/Analyses/Calibration_Strand_000/Configuration/basecall_2d Group
/Analyses/Calibration_Strand_000/Configuration/calibration_strand Group
/Analyses/Calibration_Strand_000/Configuration/components Group
/Analyses/Calibration_Strand_000/Configuration/general Group
/Analyses/Calibration_Strand_000/Configuration/genome_mapping Group
/Analyses/Calibration_Strand_000/Configuration/hairpin_align Group
/Analyses/Calibration_Strand_000/Configuration/post_processing.3000Hz Group
/Analyses/Calibration_Strand_000/Configuration/split_hairpin Group
/Analyses/Calibration_Strand_000/Log Dataset {SCALAR}
/Analyses/Calibration_Strand_000/Summary Group
/Analyses/EventDetection_000 Group
/Analyses/EventDetection_000/Configuration Group
/Analyses/EventDetection_000/Configuration/aggregator Group
/Analyses/EventDetection_000/Configuration/basecall_1d Group
/Analyses/EventDetection_000/Configuration/calibration_strand Group
/Analyses/EventDetection_000/Configuration/components Group
/Analyses/EventDetection_000/Configuration/event_detection Group
/Analyses/EventDetection_000/Configuration/general Group
/Analyses/EventDetection_000/Configuration/split_hairpin Group
/Analyses/EventDetection_000/Log Dataset {SCALAR}
/Analyses/EventDetection_000/Reads Group
/Analyses/EventDetection_000/Reads/Read_932 Group
/Analyses/EventDetection_000/Reads/Read_932/Events Dataset {1042}
/Analyses/EventDetection_000/Summary Group
/Analyses/EventDetection_000/Summary/event_detection Group
/Analyses/Segment_Linear_000 Group
/Analyses/Segment_Linear_000/Configuration Group
/Analyses/Segment_Linear_000/Configuration/aggregator Group
/Analyses/Segment_Linear_000/Configuration/basecall_1d Group
/Analyses/Segment_Linear_000/Configuration/calibration_strand Group
/Analyses/Segment_Linear_000/Configuration/components Group
/Analyses/Segment_Linear_000/Configuration/general Group
/Analyses/Segment_Linear_000/Configuration/split_hairpin Group
/Analyses/Segment_Linear_000/Log Dataset {SCALAR}
/Analyses/Segment_Linear_000/Summary Group
/Analyses/Segment_Linear_000/Summary/split_hairpin Group
/Raw                     Group
/Raw/Reads               Group
/Raw/Reads/Read_932      Group
/Raw/Reads/Read_932/Signal Dataset {5440/Inf}
/UniqueGlobalKey         Group
/UniqueGlobalKey/channel_id Group
/UniqueGlobalKey/context_tags Group
/UniqueGlobalKey/tracking_id Group

**Comment by marcus1487** [comment]
Yes, this should work fine for Tombo. The two important slots are the `/Analyses/Basecall_1D_000/BaseCalled_template/Fastq` and `/Raw/Reads/Read_932/Signal` slots.

**Comment by Fairenough** [comment]
And maybe you should notice people do bwa index to their reference genome..

**Comment by marcus1487** [comment]
Yes, I am working on a much more detailed documentation right now. I should have this posted by the end of the week.

**Comment by Fairenough** [comment]
@marcus1487 Yeah, with great power comes greater responsibility...
By the way, does tombo require a specific version of bwa? Since I encounter the message:

Failed reads summary (59694 total failed):
	Fastq slot not present in --basecall-group :	1566
	Problem running/parsing genome mapper. Ensure you have a compatible version installed.Potentially failed to locate BWA index files. :	58128

**Comment by marcus1487** [comment]
A particular version of bwa should not be required. The command line options are given [here](https://github.com/nanoporetech/tombo/blob/master/tombo/resquiggle.py#L1263) in the code. If you try to bwa mem with these options on a small test data set does that work?

**Comment by Fairenough** [comment]
I used bwa mem -x ont2d -v 1 -t 32 to map my references to my references and no problem...

@SQ	SN:MT	LN:16569
@PG	ID:bwa	PN:bwa	VN:0.7.12-r1039	CL:bwa mem -x ont2d -v 1 -t 32 mito-1.fa mito-1.fa
MT	0	MT	1	60	16569M	*	0	0	GATC...GATG	*	NM:i:1	MD:Z:3106C13462	AS:i:16567	XS:i:0
[main] Version: 0.7.12-r1039
[main] CMD: bwa mem -x ont2d -v 1 -t 32 mito-1.fa mito-1.fa
[main] Real time: 0.015 sec; CPU: 0.020 sec

**Comment by marcus1487** [comment]
What is the command you are running exactly? The argument passed to `--bwa-mem-executable` must be executable. I usually pass the full or relative path to the binary. I am not sure if a globally installed version would work in this setting (as it is being called via a system call from Tombo).

**Comment by Fairenough** [comment]
Oh my god, I've made a very stupid mistake...

**Comment by marcus1487** [comment]
No problem. Hopefully this thread might help another user solve their issue!

**Comment by marcus1487** [comment]
I am working on a more detailed version of the documentation right now (should be out by the end of the week), but I think you are referring to the tombo.stats file. I will preface with the fact that this file is not intended for direct use, but instead for use in passing to downstream tombo commands for the desired output (`write_wiggles`, `write_most_significant_fasta`, `plot_most_significant`, etc). 

Briefly though these headers are the statistics associated with each covered genomic position (note 0-based; part of the reason not to use this file). The `stat`and `mt_stat` (multiple testing stat) are combined testing values for that position. For the hypothesis test (de novo or sample comparison) this is a Fisher's method combined p-value (note that this is quite sensitive to read depth and thus should be used with care). For the alternative model comparison this will be the average likelihood ratio over all reads. The `frac` and `alt_frac` values are the fraction of values which are significant based on the input values to `test_significance` (`--single-read-threshold`; default 1% FRD or 2 Log likelihood ratio). Finally the `cov` and `control_cov` values are the read depth at the genomic location for the sample and the control sample (control only applicable for the sample comparison testing method). 

I hope this helps. And I will have this in a bit more detail in the documentation shortly.

**Comment by GabyBG** [comment]
Hello! I am trying to use Tombo I had the same error as you Problem running/parsing genome mapper. Ensure you have a compatible version installed.Potentially failed to locate BWA index files

I would like to know what was the stupid mistake :D please @Fairenough

**Comment by marcus1487** [comment]
I would suggest upgrading to the most recent version of tombo. This option was removed and now the python api to minimap2 (mappy) is used. So there is no need to provide an executable mapper anymore. Hopefully this will solve your issue.

**Comment by Fairenough** [comment]
I just forget to specify the aligner and blindly run the program. Shame for that... @GabyBG

**Comment by drkennetz** [comment]
Hi marcus, thank you for working on this. Using tombo 1.5. When running:

`tombo detect_modifications alternative_model --fast5-basedirs ./singleFast5s/ --statistics-file-basename human_cpg_test --alternate-bases CpG --processes 8`

On my resequiggled fast5s I got error:
[14:33:28] Parsing Tombo index file(s).
******************** WARNING ********************
        Failed to parse tombo index file for ./singleFast5s/ directory. Creating temporary index from FAST5 files.
[18:21:10] Performing alternative model testing.
******************** WARNING ********************
        Tombo default model for CpG in RNA does not exists.
******************** ERROR ********************
        No alternative models successfully loaded.

A) It said, "Creating temporary index from FAST5 files." The temp file is 6 bytes. Surely something is wrong there.
B) Does tombo recursively search for fast5s in the singleFast5 directory? I would assume so but you know what they say about assuming...
C) Tombo defaul model for CpG in RNA does not exists: this sample is dna. I know I can specify this and I will next time, but is this a default warning, or is tombo trying to assign my fast5s to the RNA model?

Thanks,
Dennis

**Comment by marcus1487** [comment]
A) The temporary index is created in memory (not on disk). So there must be something incorrectly formatted in the index file that is there (and that is probably why tombo shifted to the temporary in-memory index). Was the re-squiggle run on this directory completed successfully?

B) Yes tombo searches recursively for files ending in fast5. 

C) This does indicate that tombo is trying to process these reads with the RNA model. When the tombo index file is not found this is computed from the fast5 files. Here is the [hook for that in the code](https://github.com/nanoporetech/tombo/blob/master/tombo/tombo_helper.py#L894). The code has determined that these reads appear to be direct RNA reads from this function.
