### ISSUE TITLE
Tombo default model for 5mC in RNA does not exists.

### ISSUE THREAD

**Issue by dorothyzh** [nanoporetech/tombo#50]
Is there available to use Tombo to analyse RNA modifications? 

When I use
>tombo test_significance --fast5-basedirs test/reads/ --alternate-bases 5mC 6mA --statistics-file-basename sample

The error comes: 
Parsing tombo index file(s).
Performing alternative model testing
******************** WARNING ********************
	Tombo default model for 5mC in RNA does not exists.
******************** WARNING ********************
	Tombo default model for 6mA in RNA does not exists.
******************** ERROR ********************
	No alternative models successfully loaded.

**Comment by marcus1487** [comment]
Tombo does not currently have models trained to specifically test for 5mC or 6mA in RNA. You can still use the 2 other testing methods ([canonical sample comparison](https://nanoporetech.github.io/tombo/modified_base_detection.html#canonical-sample-comparison-method) or [de novo testing](https://nanoporetech.github.io/tombo/modified_base_detection.html#de-novo-non-canonical-base-method)) for analysis of RNA data.

I will keep this issue open as we are hoping to add specific alternative RNA models, so I will close this issue once release is made available that includes these models.
