### ISSUE TITLE
missing cowplot

### ISSUE THREAD

**Issue by Blosberg** [nanoporetech/tombo#6]
Hi there. I have an installation issue that I believe differs from the [other one posted](https://github.com/nanoporetech/tombo/issues/1). Starting from the instructions on your README:

```

$ conda install -c bioconda ont-tombo
Fetching package metadata .............
Solving package specifications: 

PackageNotFoundError: Packages missing in current channels:
            
  - ont-tombo -> r-cowplot

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch

```

I am as yet unfamiliar with `cowplot` , but my attempts to install this package independently have been in vain --Brew found no formulae, and from within R, `install.packages("cowplot")` yielded failed compilations, I believe because of an imcompatible R version (but I believe this is the latest). Here is some session info:

```

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan 10.11.6

```

If you have any suggestions I would greatly appreciate it. Thanks.

**Comment by marcus1487** [comment]
I believe this is a conda channels issue. Try running the [set up channels](https://bioconda.github.io/#set-up-channels) commands recommended by bioconda and hopefully that will resolve the problem.

**Comment by Blosberg** [comment]
I had, indeed, neglected to add the appropriate channels in conda. Thank you!
