### ISSUE TITLE
how does sequencing depth affect 'test_significance'?

### ISSUE THREAD

**Issue by Huanle** [nanoporetech/tombo#60]
Hi Marcus,

I have been trying to detect modified bases via comparing to a control sample.
We have prior knowledge of the positions of modified bases, but in the end, only very few (less than 0.1%) of them were found among the testing results.
I do not know why.
But I did notice that the control (--control-fast5-basedirs) was sequenced more than the samples (--fast5-basedirs) and the former one has  much more successfully resquiggled reads than the sample.
So, i wonder this might be the factor leading to not-very-successful detection of known modifications.
It would be nice if you can let me know whether and how biased sequencing yield is going to affect tombo performance.

Kind Regards,
Huanle

**Comment by marcus1487** [comment]
Certainly having more coverage will make Tombo testing results more consistent, but I have made efforts to minimize this effect. The statistic in the current version of Tombo used to rank genomic positions in terms of modified base content is the estimated fraction of modified bases. This value (by default) includes pseudo-counts for modified and unmodified reads to each estimated fraction of modified reads (as specified by the `--coverage-dampen-counts` option to all Tombo commands outputting statistics results). This option defaults to adding 2 un-modified reads and half a modified read to each genomic position, which should dampen the effects for regions with very low coverage, though a minimum of around 5-10X coverage to test is recommended.

For results from higher coverage samples, I have not tested this thoroughly, but I suspect that there is some effect, but results from the original nanoraw manuscript ([supp. figure 9](https://www.biorxiv.org/content/early/2017/04/10/094672) in particular), indicate that above 10-15X average coverage does not have too much effect on performance (though this may be different for the current Tombo algorithm that is quite divergent from the nanoraw manuscript).
