### ISSUE TITLE
Question on Motif-centered Statistic Plotting

### ISSUE THREAD

**Issue by VernLee** [nanoporetech/tombo#64]
Hi Marcus,

I'm relatively new to bioinformatics so apologies if my understanding about the issue is poor, but I've been analysing some direct rna data and visualising the analysis using the plot_motif_with_stats command. We used the 6mA consensus motif as a test and the resulted distribution plot is as attached. Strangely (or not) the distribution indicates that a much higher fraction of bases around the motif is modified rather than the motif itself. I'd expect the opposite to be true, ie a mirror of the plot. Is there something inherently wrong with my data/analysis or understanding?

Many thanks,
Vern

[tombo_results.motif_statistics.pdf](https://github.com/nanoporetech/tombo/files/2007681/tombo_results.motif_statistics.pdf)

**Comment by marcus1487** [comment]
I will also note that some of these ideas about relative position and intensity of signal shifts were discussed in issue #62 . This discussion might give some insight here as well.

**Comment by VernLee** [comment]
Ah, I will certainly try that. Thanks very much for the speedy reply.
