### ISSUE TITLE
Installing v1.3 with conda

### ISSUE THREAD

**Issue by tungufoss** [nanoporetech/tombo#67]
I'm trying to install tombo [version 1.3](https://anaconda.org/bioconda/ont-tombo/1.3/download/linux-64/ont-tombo-1.3-py36r3.4.1_0.tar.bz2) using conda v4.4.10: 
`conda install ont-tombo-1.3-py36r3.4.1_0.tar.bz2`
Which seems to be successful, but when I run it I get the error `ModuleNotFoundError: No module named 'tqdm'` -- shouldn't that be handled with conda?

**Comment by marcus1487** [comment]
It appears as though this is an issue with conda installs from a tar ball (see [this issue](https://github.com/conda/conda/issues/1884)). It looks like installation from a tarball will require either a bit of setup (described [here](https://groups.google.com/a/continuum.io/d/msg/conda/V1mtkZ-N9aQ/N13ga6XbAwAJ)) or a manual conda install of the dependencies. For Tombo v1.3, you could perform the dependencies install with the following command: 
```
conda install -y setuptools hdf5 h5py==2.7.0 numpy scipy cython mappy>=2.10 future pyfaidx tqdm rpy2 r-base r-gridextra r-ggplot2
```
