### ISSUE TITLE
Resquiggle: Filed reads summary - 'mappy.Aligner' object has no attribute 'seq'

### ISSUE THREAD

**Issue by bs2810** [nanoporetech/tombo#69]
I'm trying to run the resquiggle command for 8000 reads:
> tombo resquiggle --overwrite fast5_basedir reference 

I get the following error message:
> Failed reads summary (8000 total failed):
>       'mappy.Aligner' object has no attribute 'seq' : 6340
>       Alignment not produced : 1608
>       Fastq slot not present in --basecall-group : 52

I already ran the preprocess annotate_raw_with_fastqs and it worked for 7948 reads so I understand the last part of the error message but I'm not sure what is causing the first two?

Also what could be causing these 52 to fail in the preprocess step?

**Comment by marcus1487** [comment]
Tombo requires the most recent version of mappy (2.10), which contains a new feature to extract a bit of genomic sequence from an aligner mappy object. This should have been caught by either pip or conda on install, but it is possible that another installation of mappy may be loaded or installed at a later time in this case.

I will add an explicit check for this case in the next release, but updating your mappy install should resolve this issue.

For the pre-processing step, This usually means that the read ID values in the fastq and fast5s don't match exactly. If you are just processing the first batch of fast5s (as it appears here) then these are not ordered exactly the same as the output fastq. So some of the basecalls for the fast5s might be in another fastq. The other likely reason for failed reads in pre-processing is that some reads fail basecalling and thus produce nothing in the fastq file to be added to a fast5.
