### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by rojinsafavi** [nanoporetech/tombo#7]
I used [full] installation, and I got this error:

rpy2 is no longer supporting Python < 3. Consider using an older rpy2 release when using an older Python release.

I thought tombo is created on python 2.7. Any clue how to get around this?

Thanks!

**Comment by marcus1487** [comment]
Yes, tombo only runs on python2, but the most recent version of rpy2 does not support python2. I ran into this myself recently. You can install the most recent compatible version of rpy2 with `pip install rpy2==2.8.6`. I will also make a change to the package setup script to handle this rpy2 package version requirement in the future (probably released later this week).

**Comment by rojinsafavi** [comment]
Great, thanks!
