### ISSUE TITLE
resquiggle hangs

### ISSUE THREAD

**Issue by phiweger** [nanoporetech/tombo#70]
I run tombo preprocess like so (from a snakemake file):

```
        tombo preprocess annotate_raw_with_fastqs \
            --overwrite \
            --fast5-basedir {input.signal} \
            --fastq-filenames {input.reads} \
            --sequencing-summary-filenames {input.map_} \
            --processes {threads}

        tombo resquiggle \
            {input.signal} \
            {input.consensus} \
            --processes {threads}
```

`input.signal` is the `/path/to/fast5` and `input.reads` is the path to the concatenated fastq files from one barcode of a flow cell run w/ native barcoding. `input.consensus` is the nanopolished assembly of the barcoded reads.

Tombo starts but only annotates a part of the FAST5s (i.e. stops at iteration 297949/2046309 -- this coincides w/ the number of reads assigned to the barcode). It then seems to continue w/ the resquiggle command, but the CPU is idle, i.e. nothing happens anymore. There is no error thrown.

```
[16:10:12] Getting read filenames.
[16:10:47] Parsing sequencing summary files.
[16:10:54] Annotating FAST5s with sequence from FASTQs.
 15%|███████▊                                              | 297949/2046309 [06:36<38:47, 751.21it/s]
[16:17:31] Added sequences to a total of 297949 reads.
[16:17:32] Loading minimap2 reference.
[16:17:33] Getting file list.
[16:18:06] Using default canonical ***** DNA ***** model.
```

What could be the issue here?

Thank you,
Adrian

**Comment by marcus1487** [comment]
For the first part, the progress bar is over the full list of read IDs that were extracted. When sequencing summary files are provided, these read IDs are extracted from there. When sequencing summary files are not provided these are extracted from the FAST5 files. So if only a subset of those read IDs are present in the FASTQ files then the progressbar will not run to completion.

The second part is more concerning. The step being performed here is the spawning of all the Tombo child processes and population of the processing queues (read IDs). This process should generally take very little time. I have had more issues getting this interface working on python2, so if you are working on a python2 build you may consider upgrading to a python3 installation. The multiprocessing modules in python seem a bit more robust. Hopefully that resolves the issue, but let me know if this issue is happening with a python3 build.

**Comment by phiweger** [comment]
Thank you for the quick response. I am working off a python3.6 build.

**Comment by marcus1487** [comment]
On what kind of system are you running this? mac? unix? Server/local machine? Is this through a job scheduler (like SGE or slurm; not snakemake)?

I am thinking that something in the system setup might not be agreeing with the Tombo/python multicore usage setup. Unfortunately, I may need to have you apply a custom patch to a github clone to track down this hanging, but hopefully we can track down at what point the code is hanging.

**Comment by phiweger** [comment]
I run it on a Mac HighSierra 10.13.5

I also confirmed that the problem is not due to snakemake, i.e. trying to run resquiggle on the command line (no scheduler) does pose the same problem.

**Comment by marcus1487** [comment]
How did you install tombo? Is this within a conda environment?

**Comment by phiweger** [comment]
I installed Tombo via:

```bash
conda install -c bioconda ont-tombo
```

I did some more tests:

First I fired up a Vagrant instance w/ Ubuntu Trusty 64 -- result: Tombo hangs, but passes one step further:

```bash
vagrant@vagrant-ubuntu-trusty-64:~$ tombo resquiggle /vagrant_data/fast5/ /vagrant_data/barcode04/results/consensus.fa
[18:43:32] Loading minimap2 reference.
[18:43:32] Getting file list.
[18:43:32] Using default canonical ***** DNA ***** model.
[18:43:32] Re-squiggling reads (raw signal to genomic sequence alignment).
  8%|████▌                                                        | 300/4000 [00:19<03:59, 15.48it/s]
# here it does not continue
```

So I created a Docker image based on the [miniconda]() container and again, installed Tombo via bioconda. The image is based on Debian, and here Tombo works without any problems.

```bash
docker run \
    --cpus=4 \
    -v /path/to/data:$PWD \
    -w $PWD \
    --name methylation \
    -t \
    -a stderr \
    tombo resquiggle \
        fast5 \
        barcode04/results/consensus.fa \
        --processes 4 \
        --ignore-read-locks

# in another window
docker attach methylation
100%|████████████████████████████████████████████████████████████| 4000/4000 [02:17<00:00, 29.00it/s]
[19:03:20] Failed reads summary (3342 total failed):
	Alignment not produced :	5
	Fastq slot not present in --basecall-group :	2989
	Not enough raw signal around potential genomic deletion(s) :	5
	Poor raw to expected signal matching (revert with `tombo clear_filters`) :	9
	Read event to sequence alignment extends beyond --bandwidth :	7
	Tombo data exsists in [--corrected-group] and [--overwrite] is not set :	327
```

The warnings are ok I guess bc/ I only provided folder `fast5/0`, i.e. 4000 fast5 files to test.

Well, I am a bit at a loss as to what could be the problem. I agree that Python's multiprocessing could be a potential source of the problem.

**Comment by marcus1487** [comment]
Thank you for these tests! It is good that you can create an environment in which Tombo works this time. And yes the python multiprocessing interface has given me issues internally, especially as I am asking a lot of the modules in the re-squiggle code. I have a set of threads that are performing the file IO and mapping (in order to share the genome index in memory), and each thread connects to a process that performs the actual re-squiggle (DTW/DP) computations (to avoid the GIL). This construction was a bit of a challenge to implement (and debug), but I had hoped the current implementation was robust enough.

One item that would be helpful to know is this; when the process hangs, are you able to kill the processes with a keyboard interrupt? This could help determine if this is really hanging or if some process is just waiting for something to finish.

The more in depth step for investigation would be to clone the tombo git repo and then add a bit to the re-squiggle code to see if we can catch where the hang is occurring. I think the [hanging_threads package](https://pypi.org/project/hanging_threads/) might be useful here. If you could add the 2 lines of code (copied below) to activate the hanging_threads package to the top of the `tombo/tombo/resquiggle.py` file (I think they need to be after the `__future__` imports) from the clone and then install tombo via `pip install .` from the repo root (directory with the `setup.py` script) that should create an installation that will give some more verbose info about hanging threads.

`hanging_threads` code to add:
```
from hanging_threads import start_monitoring
monitoring_thread = start_monitoring()
```

**Comment by phiweger** [comment]
However, if I understand this correctly, it seems resquiggle finishes, despite the threading issue?

**Comment by marcus1487** [comment]
Yes this appears to be one of the successful installs (no hangs). The hang outputs from the `--overwrite` run are expected as the main thread is waiting for the workers to finish. Is this run from one of the installation setups that was hanging before? It is possible that something is slightly different from the local repo pip install (I have seen this before and I don't really get why it is the case).

Also yes the `--ignore-read-locks` flag is for exactly this case when `tombo resquiggle` is unexpected exited without having a chance to cleanup.

**Comment by phiweger** [comment]
I basically did `conda uninstall ont-tombo` and installed the cloned repo via `pip install .`, then reran resquiggle as before. I guess some data did get written to the fast5 from one of the attempts w/ the (hanging) conda install.

Well, thank you very much for helping me trouble shoot this issue. I think the local repo pip install works fine, and now I have a dockerized version too, but it is a bit worrying why there should be this issue in the first place, i.e. what you referred to as "slightly different". Probably the [Python environment](https://xkcd.com/1987/) ;)

Anyway, thanks a lot for this great piece of software and the quick help.

**Comment by phiweger** [comment]
It does not work, still. It is rather odd: If i pass `/path/to/fast5/0`, resquiggle executes:

```bash
tombo resquiggle /path/to/fast5/100/ analysis/data/barcode04/results/consensus.fa --processes 4 --overwrite --ignore-read-locks
[23:32:49] Loading minimap2 reference.
[23:32:49] Getting file list.
[23:32:49] Using default canonical ***** DNA ***** model.
[23:32:49] Re-squiggling reads (raw signal to genomic sequence alignment).
100%|████████████████████████████████████████████████████████████| 4000/4000 [01:07<00:00, 59.45it/s]
[23:33:56] Failed reads summary (3365 total failed):
	Alignment not produced :	10
	Analysis group not found at root of FAST5 :	3329
	Not enough raw signal around potential genomic deletion(s) :	9
	Poor raw to expected signal matching (revert with `tombo clear_filters`) :	14
	Read event to sequence alignment extends beyond --bandwidth :	3
```

However, if I pass it the whole `path/to/fast5`, it hangs at:

```bash
 Using default canonical ***** DNA ***** model.
```

The Docker image works for `path/to/fast5`.

On the side, what does `Analysis group not found at root of FAST5 :	3329` mean?

**Comment by phiweger** [comment]
Reinstalled Tombo w/ the two lines of thread monitoring added:

```bash
[00:06:31] Loading minimap2 reference.
[00:06:31] Getting file list.
[00:07:04] Using default canonical ***** DNA ***** model.
----------     Thread 123145563955200 hangs       ----------
    File "/path/to/miniconda3/envs/lab/lib/python3.6/threading.py", line 884, in _bootstrap
        self._bootstrap_inner()
    File "/path/to/miniconda3/envs/lab/lib/python3.6/threading.py", line 916, in _bootstrap_inner
        self.run()
    File "/path/to/miniconda3/envs/lab/lib/python3.6/threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
    File "/path/to/miniconda3/envs/lab/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
        send_bytes(obj)
    File "/path/to/miniconda3/envs/lab/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
        self._send_bytes(m[offset:offset + size])
    File "/path/to/miniconda3/envs/lab/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
        self._send(header + buf)
    File "/path/to/miniconda3/envs/lab/lib/python3.6/multiprocessing/connection.py", line 368, in _send
        n = write(self._handle, buf)
----------     Thread 140736152548224 hangs       ----------
    File "/path/to/miniconda3/envs/lab/bin/tombo", line 11, in <module>
        sys.exit(main())
    File "/path/to/miniconda3/envs/lab/lib/python3.6/site-packages/tombo/__main__.py", line 192, in main
        resquiggle._resquiggle_main(args)
    File "/path/to/miniconda3/envs/lab/lib/python3.6/site-packages/tombo/resquiggle.py", line 1494, in _resquiggle_main
        args.skip_sequence_rescaling, args.max_scaling_iterations)
    File "/path/to/miniconda3/envs/lab/lib/python3.6/site-packages/tombo/resquiggle.py", line 1306, in resquiggle_all_reads
        fast5_q.put(fast5_fn)
    File "/path/to/miniconda3/envs/lab/lib/python3.6/multiprocessing/queues.py", line 82, in put
        if not self._sem.acquire(block, timeout):
```

**Comment by marcus1487** [comment]
Ah. It looks like it is hanging on filling the queue with fast5/read filenames 

> (fast5_q.put(fast5_fn)).

My guess is that there must be some internal shared memory limit that is somehow different in these different environments. I have worked up a patch that should fix this issue. Could you apply the patch attached here to the repo (`git apply resquiggle_hang.txt`) and let me know if that resolves the hanging on your system? I hope that this should resolve the issue and then I will apply this patch to the repo.

Here is the patch in text form if there are issues with the attachment:
```
diff --git a/tombo/resquiggle.py b/tombo/resquiggle.py
index 5c735e4..2becbbd 100644
--- a/tombo/resquiggle.py
+++ b/tombo/resquiggle.py
@@ -1288,6 +1288,12 @@ def _get_index_queue(index_q, index_conn):
 
     return
 
+def _fill_files_queue(fast5_q, fast5_fns):
+    for fast5_fn in fast5_fns:
+        fast5_q.put(fast5_fn)
+
+    return
+
 def resquiggle_all_reads(
         fast5_fns, aligner, bc_grp, bc_subgrps, corr_grp, std_ref,
         bio_samp_type, outlier_thresh, overwrite, num_ps, threads_per_proc,
@@ -1297,17 +1303,20 @@ def resquiggle_all_reads(
     """
     Perform genomic alignment and re-squiggle algorithm
     """
-    fast5_q = mp.Queue()
+    fast5_q = mp.Queue(maxsize=1000)
     failed_reads_q = mp.Queue()
-    index_q = mp.Queue() if not skip_index else None
+    index_q = mp.Queue(maxsize=1000) if not skip_index else None
     progress_q = mp.Queue()
-    for fast5_fn in fast5_fns:
-        fast5_q.put(fast5_fn)
 
     # open all multiprocessing pipes and queues before threading
     # as opening threads before all process are open seems to cause
     # a deadlock when some processes are started.
     # starting all multiprocess objects seems to fix this.
+    files_p = mp.Process(target=_fill_files_queue,
+                         args=(fast5_q, fast5_fns))
+    files_p.daemon = True
+    files_p.start()
+
     map_conns = []
     rsqgl_ps = []
     for _ in range(num_ps):
@@ -1360,6 +1369,7 @@ def resquiggle_all_reads(
         resquiggle_ts.append(t)
 
     # wait for all mapping and re-squiggling workers to finish
+    files_p.join()
     for rsqgl_p in rsqgl_ps:
         rsqgl_p.join()
     for t in resquiggle_ts:
```

[resquiggle_hang.txt](https://github.com/nanoporetech/tombo/files/2106434/resquiggle_hang.txt)

**Comment by phiweger** [comment]
Yes, it now does what it says on the tin :)

I ran resquiggle including the subsequent methylation calling and everything works. So basically the bug was caused by an unlimited queue?

Thank you very much for your help in tracking this down. I'll leave the issue open and you can close it once the patch is applied.

**Comment by marcus1487** [comment]
Yes, it basically comes down to the unlimited queue size. I have just pushed the fix to the github version (won't be included in conda/pypi until next release). I guess I had figured that a queue with just the read filenames would not get to large, but it looks like this was the root of this issue!

Thank you again for helping to track down this issue!
