### ISSUE TITLE
Is tombo result sensitive to assembly errors?

### ISSUE THREAD

**Issue by phiweger** [nanoporetech/tombo#71]
Hi,

When assembling nanopore-only, the consensus usually has a lot of indels, even after polishing w/ e.g. nanopolish.

What is the effect of this -- if any -- on tombo? I guess it should affect the resquiggle, but my intuition would be that the downstream steps compare signal -- even though misplaced -- and thus there should be not much of an effect/ bias. 

The main error would then be to misplace a e.g. methylated C in regions w/ indels by a number of bases.

Is that the way you see it?

Thank you.

**Comment by marcus1487** [comment]
Assembly errors (whether from a reference or de novo assembly of any kind) will have an effect on Tombo in a number of ways, which is especially dependent on the mode of testing performed. The re-squiggle algorithm will try to assign signal over positions that do not match the ground truth of the sample being sequenced. This will result in signal being assigned to positions which do not match the expected signal levels.

Tombo provides [3 different modes of testing](https://nanoporetech.github.io/tombo/modified_base_detection.html#statistical-testing) for deviations in signal indicative of modified bases. Each of these will be effected differently by assembly errors. The control (PCR/IVT) sample comparison is likely the most robust to assembly errors as both native and control reads will have their signal assigned over these errors. When there are no modified bases in such a region the signal should be assigned similarly and thus no significant results should be produced.

The other 2 testing methods (de novo and alternative model) are more susceptible to assembly errors as these methods use an expected signal level model (using the reference sequence). The de novo testing method is the most susceptible to assembly errors and should ideally produce significant results as such positions don't match the "known" sequence which could be considered a "modification" (although this is not the main goal of Tombo). The alternative testing method should be more robust to these assembly errors as this method tests for deviations in the specific directions and magnitudes from an alternative model for a specific alternative base.

This may have made the issue a bit more complicated, but I hope the information helps. We will continue working to make all these methods more robust and easier to use!

**Comment by phiweger** [comment]
Thank you for this very comprehensive summary. Based on your comments, we will likely try to modify our experiments to include PCR controls (which I think is quite a clever trick, thank you).

**Comment by marcus1487** [comment]
I will add as an extra note here that the PCR sample comparison method currently performs worst out of the three comparison methods on internal validation data sets with a very good assembly. It seems that this is due to the unstable/non-robust nature of the model estimated from the canonical signal levels at a single base (used to test each native read against independently). I am hoping to roll in some updates to the PCR comparison method at some point, so hopefully those results will improve in future versions as avoiding these assembly errors with a robust high performance method is obviously of great value.

Best of luck!
