### ISSUE TITLE
Update Tombo from 1.2.1. to 1.3

### ISSUE THREAD

**Issue by cweldo00** [nanoporetech/tombo#74]
Dear Marcus,

How do I update my Tombo from version 1.2.1. to 1.3?

Regards,

Carika

**Comment by marcus1487** [comment]
You can install a specific version with either `conda install ont-tombo==1.3` or `pip install ont-tombo==1.3`. There are other update/upgrade commands available from conda and pip, but in my experience this is the most reliable way to make sure the correct version is installed.

**Comment by cweldo00** [comment]
Perfect! It worked like a dream
