### ISSUE TITLE
tombo CLI

### ISSUE THREAD

**Issue by phiweger** [nanoporetech/tombo#77]
Writing a Snakefile around Tombo, these are some observations about the API I'd like to share -- maybe they can help in future refactoring:

1. It would be good if one could set the output location of the resquiggle index explicitly -- That way it can be used more easily as a target for a snakemake rule.

2. When calling modifications, I think in terms of {5mC, de novo, 6mA}. However, they have 2 different subcommands at the moment. Only one would be very convenient. Additionally, for "de novo" only `.tombo.stats` is appended to the output prefix, while for "5mC" `.5mC.tombo.stats` is appended. Of course, this is a consequence of the 2 subcommands. Practically, this requires some command line fu when one writes a workflow.

Thanks

**Comment by marcus1487** [comment]
Thank you for the interest!

First, I think of these as the command line interface (CLI) issues. The API will be via the tombo python module that can give access to more low level processed data from Tombo within user python scripts. But this is really just a clarification (which I will add as an edit to the title).

For the first suggestion, I do think that this is reasonable, but for most users I think keeping track of both the directory used the index file might be a bit confusing. I am considering (as a longer term goal) adding the fast5s directory as an attribute to the index (and including much more information in the index). But this change will likely be a little ways out right now.

As for the consequences of explicitly setting the index file name in the current version, I am not sure I see how this would effect pipeline work. Is this just in terms of cleanup for the pipeline (if so the FAST5s are edited themselves, and so full cleanup to the original state is quite complex)? In any case, I don't think the index file should be touched explicitly in most workflows, so most work should proceed through the directory name anyways, right?

For the second suggestion, the addition of the "5mC" to the statistics filename from the `tombo detect_modifications alternative_model` command actually comes from the fact that you can call multiple alternative models within the same command (without reloading the data via multiple calls). So if you specify `--alternate-bases 5mC 6mA`, then you will produce 2 statistics files with names ending in `.5mC.tombo.stats` and `.6mA.tombo.stats`.

In terms of having only one command, this was actually a recent change (in version 1.3) as having a single command made it a bit confusing for users as to which method was being run. In previous versions the single call to the `test_significance` command would determine which method to use based on the arguments passed (was an alternative model specified? was a control sample provided?). I think that having drastically different underlying methods called from the same command was a bit confusing, but I am certainly open to switching back if there are strong reasons.

I hope this helps!

**Comment by phiweger** [comment]
I agree about the index.

With the command to call modifications, I think users will not "care" about the underlying differences in the algos used. Instead, you care about the abstraction. I guess many will just try all of the options that tombo gives them, and the use of something like `--modifications 5mC 6mA de_novo moretocome` is then quite convenient. However, I see your point about the actual difficulty in implementing this, given that different algos need different input files.
