### ISSUE TITLE
supplemental figure 1

### ISSUE THREAD

**Issue by rojinsafavi** [nanoporetech/tombo#8]
Hi Marcus, 

I'm trying to create a graph similar to your supplemental figure 1. I'm not sure if I'm using the right plotting command, but I'm getting this error:

**1**. (tombo-env) -bash-4.2$ tombo resquiggle ../all-subsets/  ../RNA-test/referenceFastaFiles/cdna/Homo_sapiens.GRCh38.cdna.all.fa --minimap2-executable minimap2 --processes 4 --overwrite --tombo-model-filename tombo/tombo/tombo_models/tombo.RNA.200mV.model
Correcting 11318 files with 1 subgroup(s)/read(s) each (Will print a dot for each 500 reads completed).
......................
Failed reads summary (4469 total failed):
	Alignment not produced (if all reads failed check for index files) :	120
	Fewer changepoints found than requested. :	8
	No valid path found through raw signal of long read :	3
	No valid path found through raw signal of short read :	3922
	No valid path found through start of raw signal :	15
	Read event to sequence alignment extends beyond --bandwidth :	2
	Too little signal around event-aligned genomic deletion :	399

**2**.(tombo-env) -bash-4.2$ tombo plot_correction  --fast5-basedirs ../all-subsets/
Preparing plot data.
Parsing tombo index file(s).
ERROR: No reads were able to be processed. Check --fast5-basedirs for FAST5 files and that --corrected-group and --basecall-subgroup are correct for the reads provided 

I would really appreciate if I can get some help regarding this error.

**Comment by marcus1487** [comment]
This plot was specific to the model unaware re-squiggle algorithm (found in the now deprecated nanoraw package and still available via the `tombo event_resquiggle` command). Thus this command is only applicable to read processed with the event_resquiggle command. Basically, the new resquiggle method does not use the events table, even if it is available, so this plot does not really make sense in the new tombo resquiggle framework.

I have a note in the main tombo help command (`tombo -h`) for this, but I understand that this is not the most obvious place for this note. I will add a note to this error message in the next release to make debugging this a bit easier.

![image](https://user-images.githubusercontent.com/13755444/33904579-cf3c72f6-df30-11e7-8bd6-764e9b1eb8c5.png)
