### ISSUE TITLE
How to improve the efficiency of  "resquiggle"

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#81]
Hi:
     I'm using resquiggle to preprocess my data(more than 700 GB size basecalled fast5 files).I have realized that is a big project.So I have set 16 process for tombo resquiggle through parameter `--processes 16` .
    But it was expected to take more than 100 hours to finish the whole work.Can I use ` --threads-per-process`  to allocate more threads to tombo for increasing the speed?

**Comment by marcus1487** [comment]
If you are seeing full utilization of the requested 16 processors then the threads per process option won’t help much. If you are not seeing full utilization of the cpu then on some architectures the threads per process option may help a bit. 

If you are not seeing full cpu utilization the other thing to look into would be moving to data to a disk with better performance. 

If you are seeing full cpu utilization then unfortunately that is probably the fastest that tombo can run currently. We will implement some potential speed ups in future versions.

**Comment by weir12** [comment]
Thanks
