### ISSUE TITLE
re-squiggle error

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#84]
Hi:
when I try re-squiggle fast5 files which were base-called by Albacore. fast5 files path is "my/output/path/workspace/pass"
[13:27:57] Failed reads summary (6751885 total failed):
	Alignment not produced :	5531894
	Analysis group not found at root of FAST5 :	6413
	Fastq slot not present in --basecall-group :	1211669
	Not enough raw signal around potential genomic deletion(s) :	40
	Poor raw to expected signal matching (revert with `tombo clear_filters`) :	937
	Read contains too many potential genomic deletions :	7
	Read event to sequence alignment extends beyond --bandwidth :	100
	Read failed sequence-based signal re-scaling parameter estimation. :	623
	Too much raw signal for mapped sequence :	202
I guess this trouble was caused by upstream processing step.

**Comment by marcus1487** [comment]
This looks like most of the reads either did not produce basecalls (`Fastq slot not present in --basecall-group`) or did not map to your reference genome/transcriptome (`Alignment not produced`). Tombo cannot proceed without basecalls and a valid genomic mapping.
