### ISSUE TITLE
Tombo default model for 6mA in RNA does not exists.

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#86]
When I use `tombo detect_modifications alternative_model` with parameter：`--alternate-bases 6mA --rna`
Such error was reported:
`******************** WARNING ********************
        Tombo default model for 6mA in RNA does not exists.
******************** ERROR ********************
        No alternative models successfully loaded.
`
So,I have to use [https://nanoporetech.github.io/tombo/modified_base_detection.html#canonical-sample-comparison-method](url) and [https://nanoporetech.github.io/tombo/modified_base_detection.html#de-novo-non-canonical-base-method](url) to achieve my goal?

**Comment by marcus1487** [comment]
Yes. At the moment the de novo and sample comparison methods are the methods available for specific 6mA detection in RNA. You can use the `--print-available-models` option to see the models available with any tombo version (command: `tombo detect_modifications alternative_model --print-available-model`).

**Comment by Runsheng** [comment]
May I ask do you still have a plan for the RNA 6mA model?

**Comment by marcus1487** [comment]
We are hoping to include an RNA 6mA model, but there are no immediate plans for the release of this model at this time.

**Comment by langkilfeather** [comment]
Is there any update on RNA models, such as 6mA being available in the near future?

**Comment by marcus1487** [comment]
There is no imminent plan to make a 6mA RNA model available at this time.
