### ISSUE TITLE
what is alternate

### ISSUE THREAD

**Issue by rei1011** [nanoporetech/tombo#88]
What is the meaning of "Alternate" ?

>chr5:134260518:- Est. Frac. Alternate: 0.99  Coverage: 261
CTTCTTACAAGCCAA

Thanks a lot.
Rei

**Comment by marcus1487** [comment]
Alternate means non-canonical base. So this is the estimated fraction of reads at a position indicating the presence of a non-canonical base (or a specific non-canonical base for `alternative_model` testing).

**Comment by rei1011** [comment]
Very helpful. Thank you again!

**Comment by zmy24** [comment]
> 

Hello Marcus

What's the connection between Alternate and the fraction of every base?
