### ISSUE TITLE
Recursivity in resquiggle command

### ISSUE THREAD

**Issue by alexredon** [nanoporetech/tombo#91]
Hi !

I have an issue when I run the resquiggle command on tombo 1.3 : 
```
tombo resquiggle myDirfast5 ref.fasta --processes 4 --overwrite 
[11:26:19] Loading minimap2 reference.
[11:26:19] Getting file list.
[11:26:27] Using default canonical ***** DNA ***** model.


```

and after that nothing happens. So I tried to run the command in a subdirectory and it worked.
It looks like if there were no recursivity to treat all fast5 repertories. And I don't know what I should do to resolve that, do you have an idea ?

Thanks,
Alex

**Comment by marcus1487** [comment]
I think this is the same core issue as found in #70. This issue should be solved by an installation from the github repo.

**Comment by alexredon** [comment]
I tried to apply the patch resquiggle_hang.txt. But when I run `git apply resquiggle_hang.txt` I have : 
```
error : tombo/resquiggle.py: No such file or directory
```

I put the patch in the same directory of `resquiggle.py`, I don't know how to resolve it

**Comment by marcus1487** [comment]
The patch is applied to the master branch on github so you should be able to install this fix via ‘git+https://github.com/nanoporetech/tombo.git’. 

For the patch, I think I could be applied from the root of the project. So in the same directory as the setup.py script.

**Comment by alexredon** [comment]
It is working now, thanks a lot.
