### ISSUE TITLE
error in preprocessing

### ISSUE THREAD

**Issue by ma-diroma** [nanoporetech/tombo#92]
Hi Marcus,

I am trying to use tombo (v1.3, python 2.7) for annotation of raw fast5 files with fastq.

`tombo preprocess annotate_raw_with_fastqs --fast5-basedir myfast5_dir --fastq-filenames myfastq --overwrite --processes 10 2> annotate.err`

I got this error

`tail annotate.err`

 ```
20%|##        | 2796620/13943419 [3:09:03<12:33:34, 246.53it/s]
[00:13:47] Annotating FAST5s with sequence from FASTQs.
Traceback (most recent call last):
  File "/home/madiroma/bin/anaconda2/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
IOError: [Errno 32] Broken pipe
  0%|          | 0/2796620 [00:00<?, ?it/s]******************** WARNING ********************
	Some records contain read identifiers not found in any FAST5 files or sequencing summary files.
 69%|######9   | 1937702/2796620 [1:15:03<33:16, 430.28it/s]
[01:29:18] Added sequences to a total of 1937702 reads.
```

I retried also without using multiple threads, similar error

```
[12:19:55] Preparing reads and extracting read identifiers.
  5%|5         | 699426/13943419 [2:11:01<41:21:06, 88.97it/s]
[14:31:00] Annotating FAST5s with sequence from FASTQs.
Traceback (most recent call last):
  File "/home/madiroma/bin/anaconda2/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
IOError: [Errno 32] Broken pipe
  0%|          | 0/699426 [00:00<?, ?it/s]******************** WARNING ********************
	Some records contain read identifiers not found in any FAST5 files or sequencing summary files.
 10%|9         | 69500/699426 [15:26<2:19:55, 75.03it/s]
```

Could you please help me?

Thanks, 
Maria Angela

**Comment by marcus1487** [comment]
I have not seen this behavior before. My guess would be that the large number if read files is somehow giving the python 2.7 multiprocessing library issues. I have set a max size on the fastqs queue, but there must be something else going on here. My first recommendation would be to upgrade to python3. I have found many of the core libraries to be much more stable. Hope this helps.
