### ISSUE TITLE
What is the meaning of the Y-axis in Per-read Statistic Plotting?

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#97]
Hi:
    I don't quite understand the Y-axis in Per-read Statistic Plotting.Which kind of factors specifies the vertical coordinate for each dot?

**Comment by marcus1487** [comment]
The y axis in the per-read plot indicates the individual reads. So each row indicates the test results from an individual read.

**Comment by weir12** [comment]
So,all the dots with same value of y axis mean they come from the same read?

**Comment by marcus1487** [comment]
Yes. That is correct.
