### ISSUE TITLE
How to get the fraction of raw signal data of reads which is mapping to specific genomic positon?

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#99]
Hi:
    Can the tombo output the raw signal data of reads which are mapped to specific genomic positon?
    thanks~

**Comment by marcus1487** [comment]
The raw signal for a read can be extracted from a read using the `tombo_helper.get_raw_read_slot(fast5_fn)['Signal'].value` function from the Tombo python API. This interface will be updated in the next release though, so look back soon for a much easier interface for this type processing step.

**Comment by weir12** [comment]
I don't know the meaning of variables such as 'r_data' and 'fast5_data' in tombo_helper script.Should I pass argument（e.g ,absolute path of fast5 files ）to paramenter?

**Comment by marcus1487** [comment]
These variables are currently not well documented, defined or maintained. The next release will have full API documentation and examples. For the above snippet of code I shared `fast5_fn` is just the path to a fast5 file of interest.

**Comment by weir12** [comment]
Thanks.
So,if I want to get partial raw signals of a set of reads which are mapping to specific genomic locus,I can only wait for the releasing of next version of tombo.Is that right?Could you give me some hints&tips,If I intend to  implement this functionality by modifying the scripts.thanks again

**Comment by weir12** [comment]
To be more precise,I just want to export treated data which was used to plot.

**Comment by marcus1487** [comment]
I think the easiest thing to do (before the new python API) might be to edit the R script that plots the data to save all of the plotting data to an [R data object](https://www.rdocumentation.org/packages/base/versions/3.5.1/topics/save). You could modify [this script](https://github.com/nanoporetech/tombo/blob/master/tombo/R_scripts/plotGroupComp.R) (from an installation from source) to save the `eventData` object like this `save(eventDat, file='eventDat.RData')`. Then when you run a plot command with the `Density` overplot type option (`--overplot-type`) with the `--overplot-threshold` set to 0, you will save all of the event data included in that plot to an R data file that would be read into R (using the [load function](https://www.rdocumentation.org/packages/base/versions/3.5.1/topics/load)) and processed further.

Again this will be much easier in the new python API, but this is probably the easiest way to do this from the current release.

**Comment by weir12** [comment]
Thanks,it does really work.

**Comment by marcus1487** [comment]
With the updated python API this task can now be completed in a much more intuitive manner. You can see that this is now the first example case from the Tombo API [here](https://nanoporetech.github.io/tombo/tombo.html). Do note here if there is any trouble with the API for this task.
